In [6]:
!pip install hydra-core --upgrade

Collecting hydra-core
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: omegaconf<2.4,>=2.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (2.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (4.9.3)
Requirement already satisfied: packaging in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (25.0)
Requirement already satisfied: PyYAML>=5.1.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from omegaconf<2.4,>=2.2->hydra-core) (6.0)
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
Installing collected packages: hydra-core
Successfully installed hydra-core-1.3.2

In [7]:
#from .confidence_extraction_methods import ConfidenceExtractor
#from .datasets import load_dataset
#from .metrics import MetricEvaluator
from omegaconf import OmegaConf, DictConfig
import hydra
import logging
import os
from hydra.core.hydra_config import HydraConfig
import pandas as pd

In [19]:
@hydra.main(config_path="configs", config_name="config", version_base=None)
def main(cfg):
    print(cfg)
    print("Done")

In [20]:
if __name__ == "__main__":
    main()

usage: ipykernel_launcher.py [--help] [--hydra-help] [--version]
                             [--cfg {job,hydra,all}] [--resolve]
                             [--package PACKAGE] [--run] [--multirun]
                             [--shell-completion] [--config-path CONFIG_PATH]
                             [--config-name CONFIG_NAME]
                             [--config-dir CONFIG_DIR]
                             [--experimental-rerun EXPERIMENTAL_RERUN]
                             [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                             [overrides ...]
ipykernel_launcher.py: error: unrecognized arguments: --f=c:\Users\user\AppData\Roaming\jupyter\runtime\kernel-v3dbfeee6ba1e72864561ab7ef018b73233a658064.json

SystemExit: 2

In [6]:
!pip install datasets --upgrade

Collecting datasets
  Downloading datasets-4.7.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (23.0.1)
Collecting dill<0.4.1,>=0.3.0 (from datasets)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (2.3.2)
Requirement already satisfied: requests>=2.32.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (2.32.3)
Collecting httpx<1.0.0 (from datasets)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tqdm>=4.66.3 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.19 (from datasets)
  Downloading multiprocess-0.70.18-py311-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.9.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (0.34.4)
Requirement already satisfied: packaging in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (6.0)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (3.5.0)
Requirement already satisfied: certifi in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (2025.1.31)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (3.10)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (23.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: colorama in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-4.7.0-py3-none-any.whl (527 kB)
   ---------------------------------------- 0.0/527.5 kB ? eta -:--:--
   ---------------------------------------- 527.5/527.5 kB 16.6 MB/s  0:00:00
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading multiprocess-0.70.18-py311-none-any.whl (144 kB)
Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl (457 kB)
Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl (31 kB)
Installing collected packages: xxhash, propcache, multidict, h11, frozenlist, dill, aiohappyeyeballs, yarl, multiprocess, httpcore, aiosignal, httpx, aiohttp, datasets

   -------------- -------------------------  5/14 [dill]
   -------------- -------------------------  5/14 [dill]
   ---------------------- -----------------  8/14 [multiprocess]
   ------------------------- --------------  9/14 [httpcore]
   ------------------------------- -------- 11/14 [httpx]
   ---------------------------------- ----- 12/14 [aiohttp]
   ---------------------------------- ----- 12/14 [aiohttp]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ---------------------------------------- 14/14 [datasets]

Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 datasets-4.7.0 dill-0.4.0 frozenlist-1.8.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 multidict-6.7.1 multiprocess-0.70.18 propcache-0.4.1 xxhash-3.6.0 yarl-1.23.0

In [4]:
from datasets import load_dataset

ds = load_dataset("tau/commonsense_qa")
df = ds["train"].to_pandas()

df.head(5)

,id,question,question_concept,choices,answerKey
0,075e483d21c29a511267ef62bedc0461,The sanctions against the school were a punish...,punishing,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
1,61fe6e879ff18686d7552425a36344c8,Sammy wanted to go to where the people were. ...,people,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",B
2,4c1cb0e95b99f72d55c068ba0255c54d,To locate a choker not located in a jewelry bo...,choker,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
3,02e821a3e53cb320790950aab4489e85,Google Maps and other highway and street GPS s...,highway,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",D
4,23505889b94e880c3e89cff4ba119860,"The fox walked from the city into the forest, ...",fox,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",C

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9741 entries, 0 to 9740
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                9741 non-null   object
 1   question          9741 non-null   object
 2   question_concept  9741 non-null   object
 3   choices           9741 non-null   object
 4   answerKey         9741 non-null   object
dtypes: object(5)
memory usage: 380.6+ KB

In [7]:
df_filtered_col = df[["question", "choices", "answerKey"]]
df_filtered_col.head(5)

,question,choices,answerKey
0,The sanctions against the school were a punish...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
1,Sammy wanted to go to where the people were. ...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",B
2,To locate a choker not located in a jewelry bo...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
3,Google Maps and other highway and street GPS s...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",D
4,"The fox walked from the city into the forest, ...","{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",C

In [1]:
import pandas as pd
def get_data(data_path):
    return pd.read_csv(data_path, encoding='utf-8')

c:\Users\user\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df1 = get_data("Our code\\experiments\\datasets\\data\\nq_open.csv")

In [3]:
df1.keys()

Index(['Unnamed: 0', 'type', 'category', 'question', 'best_answer',
       'correct_answers', 'incorrect_answers', 'source', 'problem', 'answer'],
      dtype='object')

In [4]:
question = df1['question'][0]
truth = df1['answer'][0]
print(question)
print(truth)

when was the last time anyone was on the moon
14 december 1972 utc

In [5]:
import pandas as pd
df = pd.read_csv(r"c:\Users\user\Downloads\results_google_gemma-3-4b-it.csv", encoding='utf-8')

In [6]:
df.head(5)

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_2,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses
0,Who received the IEEE Frank Rosenblatt Award i...,Dr. Ronald J. Hoeh and Dr. John A. Stankevic...,Dr. Richard S. Sutton received the IEEE Fran...,Dr. Fei-Fei Li received the IEEE Frank Rosen...,Dr. Narendra T. Kulkarni received the IEEE Fr...,Professor Ruzena Bajcsy received the IEEE Fr...,Shimon Schocken received the IEEE Frank Rose...,Shuji Osajima received the IEEE Frank Rosenb...,David Ebert received the IEEE Frank Rosenbla...,Professor George Klir received the IEEE Fran...,...,0,0,0,0,0,0,0,1,0.9,Dr. Ronald J. Hoeh and Dr. John A. Stankevic...
1,Who was awarded the Oceanography Society's Jer...,Dr. Robert Weller was awarded the Oceanograph...,David Holland was awarded the Oceanography S...,David Holland was awarded the Oceanography S...,Dr. Jennifer Smith was awarded the Oceanograp...,Dr. Lisa Levin was awarded the Oceanography S...,Professor Carol Anne Robinson was awarded the...,Dr. Maria Vernet was awarded the Oceanograph...,"In 2018, Dr. Robert Weller was awarded the Oc...",Dr. Helen Harris was awarded the Oceanography...,...,0,0,0,0,0,0,0,0,1.0,Dr. Robert Weller was awarded the Oceanograph...
2,What's the name of the women's liberal arts co...,Vassar College is a women's liberal arts coll...,Vassar College is the name of the women’s lib...,Vassar College.,Vassar College is a women's liberal arts coll...,Vassar College.,Vassar College.\n,Vassar College is the name of the women's lib...,Vassar College is a women's liberal arts coll...,Vassar College is a women's liberal arts coll...,...,1,0,1,1,1,1,1,1,0.8,Vassar College is the name of the women’s lib...
3,In whose honor was the Leipzig 1877 tournament...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,...,0,0,0,0,0,0,0,0,1.0,The Leipzig 1877 tournament was organized in ...
4,"According to Karl Küchler, what did Empress El...",Küchler stated that Empress Elizabeth's favor...,Küchler identified the sculpture as depicting...,Küchler identified Empress Elizabeth's favori...,Küchler identified the sculpture as depicting...,Küchler identified the sculpture as depicting...,Küchler identified the sculpture as a depicti...,Küchler identified Elizabeth's favorite sculp...,"According to Karl Küchler, Empress Elizabeth'...",Küchler identified Empress Elisabeth’s favori...,...,0,0,0,0,0,0,0,1,0.9,Küchler stated that Empress Elizabeth's favor...

In [7]:
def to_raw(string):
    return fr"{string}"

In [8]:
for r in range(10):
    print(to_raw(df[f'response_{r}'][0]))

  Dr. Ronald J. Hoeh and Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010
  Dr. Richard S. Sutton received the IEEE Frank Rosenblatt Award in 2010.

  Dr. Fei-Fei Li received the IEEE Frank Rosenblatt Award in 2010.

 Dr. Narendra T. Kulkarni received the IEEE Frank Rosenblatt Award in 2010.

  Professor Ruzena Bajcsy received the IEEE Frank Rosenblatt Award in 2010.

  Shimon Schocken received the IEEE Frank Rosenblatt Award in 2010.

  Shuji Osajima received the IEEE Frank Rosenblatt Award in 2010.

  David Ebert received the IEEE Frank Rosenblatt Award in 2010.

  Professor George Klir received the IEEE Frank Rosenblatt Award in 2010.

  In 2010, Professor Shimon Peres received the IEEE Frank Rosenblatt Award.

In [9]:
df[f'response_{3}'][0].replace("\n", "").strip()

'Dr. Narendra T. Kulkarni received the IEEE Frank Rosenblatt Award in 2010.'

In [10]:
df["question"][0].replace("\n", "").strip()

'Who received the IEEE Frank Rosenblatt Award in 2010?'

In [12]:
df["responses"][0].replace("\n", "").strip()

'Dr. Ronald J. Hoeh and Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010'

In [38]:
df["confidences"][0]>0.5

True

In [ ]:


for r in range(len(df)):
    if df["confidences"][r] > 0.8:
        df.loc[r, "conf_level"] = "High"   
    elif df["confidences"][r] > 0.6:
        df.loc[r, "conf_level"] = "Moderate"
    elif df["confidences"][r] > 0.4:
        df.loc[r, "conf_level"] = "Low"
    elif df["confidences"][r] > 0.2:
        df.loc[r, "conf_level"] = "Lowest"
    else:
        df.loc[r, "conf_level"] = "Completely Uncertain"

print(df["conf_level"])

0        High
1        High
2    Moderate
3        High
4        High
5        High
6      Lowest
7        High
8    Moderate
9        High
Name: conf_level, dtype: object

In [5]:
q="Who received the IEEE Frank Rosenblatt Award in 2010?"
output="""1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.
2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.
3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.
4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.
5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.
6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.
7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.
8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.
9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.
10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award."""
gens=[]
gens.append([{q: r} for r in output.split("\n")])
gens

[[{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}]]

In [6]:
q="Who received the IEEE Frank Rosenblatt Award in 2010?"
output="""1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.
2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.
3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.
4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.
5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.
6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.
7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.
8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.
9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.
10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award."""
gens.append([{q: r} for r in output.split("\n")])
gens

[[{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}],
 [{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}]]

In [7]:
q="Who received the IEEE Frank Rosenblatt Award in 2010?"
output="""1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.
2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.
3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.
4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.
5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.
6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.
7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.
8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.
9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.
10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award."""
gens.append([{q: r} for r in output.split("\n")])

In [8]:
qs=[r for r in gens[1][0].values()]
qs

['1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.']

In [9]:
gens

[[{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}],
 [{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}],
 [{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}]]

In [ ]:
import pandas as pd
data = pd.read_csv(r"Our code\experiments\datasets\data\math.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\truthfulQA.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\commonsense_qa.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\nq_open.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\simple_qa_test_set.csv", encoding='utf-8') #800
print(len(data))

12500
817
9741
3610
4326

In [70]:
import pandas as pd
res=pd.read_csv(r"c:\Users\user\Downloads\results_google_gemma-3-4b-it(1).csv", encoding='utf-8')
h,m,l,ll,cu=0,0,0,0,0
for r in range(len(res)):
    if res["confidences"][r] > 0.8:
        h += 1  
    elif res["confidences"][r] > 0.6:
        m += 1
    elif res["confidences"][r] > 0.4:
        l += 1
    elif res["confidences"][r] > 0.2:
        ll += 1
    else:
        cu += 1
        
print(f"High Confidence: {h} ({h/len(res)*100:.2f}%)")
print(f"Moderate Confidence: {m} ({m/len(res)*100:.2f}%)")
print(f"Low Confidence: {l} ({l/len(res)*100:.2f}%)")
print(f"Lowest Confidence: {ll} ({ll/len(res)*100:.2f}%)")
print(f"Completely Uncertain: {cu} ({cu/len(res)*100:.2f}%)")

High Confidence: 101 (20.20%)
Moderate Confidence: 58 (11.60%)
Low Confidence: 110 (22.00%)
Lowest Confidence: 116 (23.20%)
Completely Uncertain: 115 (23.00%)

In [71]:
res.head()

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses,level
0,What song (title and artist) inspired Tuesday ...,"""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""Landslide"" by Fleetwood Mac inspired Tuesday ...","""I Want You Back"" by The Jackson 5 inspired Tu...","""A Sky Full of Stars"" by Coldplay inspired Tue...","""Lost in the World"" by Kanye West inspired Tue...",...,0,0,1,2,3,4,0,0.6,"""The Sound of Silence"" by Simon & Garfunkel in...",low level of confidence
1,What is the name of the university where Ana F...,Ana Figueroa studies and graduates from the Un...,Ana Figueroa studies and graduates from Yale U...,Ana Figueroa graduates from the University of ...,Ana Figueroa studies and graduates from Harvar...,Ana Figueroa studies and graduates from the Un...,Ana Figueroa studies and graduates from Yale U...,Ana Figueroa studies and graduates from the Un...,Ana Figueroa studied and graduated from Yale U...,Ana Figueroa studies and graduates from the Un...,...,2,0,1,0,1,0,0,0.6,Ana Figueroa studies and graduates from the Un...,low level of confidence
2,Who preceded Oscar Alende as governor of the P...,Juan López.,Juan López.,"Juan López, who previously served as governor.","Juan López, a military leader, preceded Oscar ...",Juan Manuel de Rosas preceded Oscar Alende as ...,Horacio Echavarría preceded Oscar Alende as go...,Bartolomé Mitre preceded Oscar Alende as gover...,Juan López.,"Juan López, who had previously served as gover...",...,0,1,2,3,0,0,0,0.7,Juan López.,moderate level of confidence
3,"What day, month, and year was the New Zealand ...","Jennifer Kay Ludlam was born on July 21, 1973.","Jennifer Kay Ludlam was born on June 26, 1978.","Jennifer Kay Ludlam was born on June 27, 1970.","Jennifer Kay Ludlam was born on January 13, 1973.","Jennifer Kay Ludlam was born on June 22, 1973.","Jennifer Kay Ludlam was born on December 26, 1...","Jennifer Kay Ludlam was born on November 29, 1...","Jennifer Kay Ludlam was born on June 24, 1974.","Jennifer Kay Ludlam was born on July 29, 1973.",...,3,4,5,6,7,8,9,0.1,"Jennifer Kay Ludlam was born on July 21, 1973.","complete uncertainty, reject to reply"
4,What is the Regional Transport Office (RTO) co...,The RTO code for Kolasib in Mizoram is MZ07.,The Regional Transport Office (RTO) code for K...,The RTO code for Kolasib in Mizoram is MNL.,The RTO code for Kolasib in Mizoram is LR23.,The RTO code for Kolasib in Mizoram is MNL.,The Regional Transport Office (RTO) code for K...,The RTO code for Kolasib in Mizoram is KM-22.,"The RTO code for Kolasib, Mizoram is LR17.",The Regional Transport Office (RTO) code for K...,...,3,2,0,4,5,1,5,0.2,The RTO code for Kolasib in Mizoram is MZ07.,"complete uncertainty, reject to reply"

In [72]:
import pandas as pd
res1=pd.read_csv(r"c:\Users\user\Downloads\results_1_google_gemma-3-4b-it(1).csv", encoding='utf-8')
h,m,l,ll,cu=0,0,0,0,0
for r in range(len(res1)):
    if res1["confidences"][r] > 0.8:
        h += 1  
    elif res1["confidences"][r] > 0.6:
        m += 1
    elif res1["confidences"][r] > 0.4:
        l += 1
    elif res1["confidences"][r] > 0.2:
        ll += 1
    else:
        cu += 1
        
print(f"High Confidence: {h+101} ({(h+101)/(2*len(res1))*100:.2f}%)")
print(f"Moderate Confidence: {m+58} ({(m+58)/(2*len(res1))*100:.2f}%)")
print(f"Low Confidence: {l+110} ({(l+110)/(2*len(res1))*100:.2f}%)")
print(f"Lowest Confidence: {ll+116} ({(ll+116)/(2*len(res1))*100:.2f}%)")
print(f"Completely Uncertain: {cu+115} ({(cu+115)/(2*len(res1))*100:.2f}%)")

High Confidence: 206 (20.60%)
Moderate Confidence: 117 (11.70%)
Low Confidence: 196 (19.60%)
Lowest Confidence: 238 (23.80%)
Completely Uncertain: 243 (24.30%)

In [3]:
import pandas as pd
res3=pd.read_csv(r"results_google_gemma-3-4b-it.csv", encoding='utf-8')
h,m,l,ll,cu=0,0,0,0,0
for r in range(len(res3)):
    if res3["confidences"][r] > 0.8:
        h += 1  
    elif res3["confidences"][r] > 0.6:
        m += 1
    elif res3["confidences"][r] > 0.4:
        l += 1
    elif res3["confidences"][r] > 0.2:
        ll += 1
    else:
        cu += 1
        
print(f"High Confidence: {h} ({(h)/len(res3)*100:.2f}%)")
print(f"Moderate Confidence: {m} ({(m)/len(res3)*100:.2f}%)")
print(f"Low Confidence: {l} ({(l)/len(res3)*100:.2f}%)")
print(f"Lowest Confidence: {ll} ({(ll)/len(res3)*100:.2f}%)")
print(f"Completely Uncertain: {cu} ({(cu)/len(res3)*100:.2f}%)")

High Confidence: 601 (60.10%)
Moderate Confidence: 155 (15.50%)
Low Confidence: 164 (16.40%)
Lowest Confidence: 59 (5.90%)
Completely Uncertain: 21 (2.10%)

In [3]:
import pandas as pd
res12=pd.read_csv(r"keep\results_google_gemma-12b-it.csv", encoding='utf-8')
h,m,l,ll,cu=0,0,0,0,0
for r in range(len(res12)):
    if res12["confidences"][r] > 0.8:
        h += 1  
    elif res12["confidences"][r] > 0.6:
        m += 1
    elif res12["confidences"][r] > 0.4:
        l += 1
    elif res12["confidences"][r] > 0.2:
        ll += 1
    else:
        cu += 1
        
print(f"High Confidence: {h} ({(h)/len(res12)*100:.2f}%)")
print(f"Moderate Confidence: {m} ({(m)/len(res12)*100:.2f}%)")
print(f"Low Confidence: {l} ({(l)/len(res12)*100:.2f}%)")
print(f"Lowest Confidence: {ll} ({(ll)/len(res12)*100:.2f}%)")
print(f"Completely Uncertain: {cu} ({(cu)/len(res12)*100:.2f}%)")

High Confidence: 157 (19.41%)
Moderate Confidence: 110 (13.60%)
Low Confidence: 169 (20.89%)
Lowest Confidence: 196 (24.23%)
Completely Uncertain: 177 (21.88%)

In [5]:
size="gemma-3-12b-it"
q_df=pd.DataFrame()
save_as=f"200_q_{size}.csv"
h,m,l,ll,cu=0,0,0,0,0
i=0
while True:
    row=res12.iloc[i]
    if row["level"] == "high level of confidence" and h<40:
        h += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "moderate level of confidence" and m<40:
        m += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "low level of confidence" and l<40:
        l += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "lowest level of confidence" and ll<40:
        ll += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "complete uncertainty, reject to reply" and cu<40:
        cu += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    if h>=40 and m>=40 and l>=40 and ll>=40 and cu>=40:
        break
    i+=1
    if i%100==0:
        print(f"Processed {i} rows...")
print(q_df.head())
len(q_df)

q_df.to_csv(save_as, index=False)

Processed 100 rows...
Processed 200 rows...
                                            question  \
0  Who received the IEEE Frank Rosenblatt Award i...
1  Who was awarded the Oceanography Society's Jer...
2  In which year did the Japanese scientist Koich...
3        Who won the Gerard P. Kuiper Prize in 2001?
4  On which day, month, and year did the Hubble T...

                                          response_0  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Dr. Carl Wunsch was awarded the Oceanography S...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the Gerard P. Kuiper Prize in...
4  The Hubble Telescope entered a partial safe mo...

                                          response_1  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Dr. Sharon Harley was awarded the Oceanography...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the 2001 Gerard P. Kuiper Pri...
4  The Hubble Space Telescope entered a partial s...

                                          response_2  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Dr. Susan Williams was awarded the Oceanograph...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the 2001 Gerard P. Kuiper Pri...
4  The Hubble Telescope entered a partial safe mo...

                                          response_3  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Samantha Joye was awarded the Oceanography Soc...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the Gerard P. Kuiper Prize in...
4  The Hubble Telescope entered a partial safe mo...

                                          response_4  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Dr. Susan Williams was awarded the Oceanograph...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the Gerard P. Kuiper Prize in...
4  The Hubble Space Telescope entered a partial s...

                                          response_5  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Dr. Carl Wunsch was awarded the Oceanography S...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the Gerard P. Kuiper Prize in...
4  The Hubble Telescope entered a partial safe mo...

                                          response_6  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Lisa Levin was awarded the Oceanography Societ...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the 2001 Gerard P. Kuiper Pri...
4  The Hubble Telescope entered a partial safe mo...

                                          response_7  \
0  Geoffrey Hinton received the IEEE Frank Rosenb...
1  Lisa Levin was awarded the Oceanography Societ...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Morrison won the Gerard P. Kuiper Prize ...
4  The Hubble Telescope entered a partial safe mo...

                                          response_8  ... semantic_id_3  \
0  Geoffrey Hinton received the IEEE Frank Rosenb...  ...             1
1  Dr. Edith Widder was awarded the Oceanography ...  ...             3
2  Koichi Mizushima received the Kato Memorial Pr...  ...             3
3  David Jewitt won the Gerard P. Kuiper Prize in...  ...             1
4  The Hubble Telescope entered a partial safe mo...  ...             1

  semantic_id_4 semantic_id_5 semantic_id_6 semantic_id_7 semantic_id_8  \
0             1             1             1             2             2
1             4             0             5             5             6
2             1             0             4             4             5
3             1             2             2             3             2
4             1             1             1             1             1

  semantic_id_9 confidences  \
0             1         0.5
1             7         0.2
2             4         0.3
3             2         0.4
4             1         0.9

                                           responses  \
0  Yoshua Bengio received the IEEE Frank Rosenbla...
1  Dr. Carl Wunsch was awarded the Oceanography S...
2  Koichi Mizushima received the Kato Memorial Pr...
3  David Jewitt won the Gerard P. Kuiper Prize in...
4  The Hubble Space Telescope entered a partial s...

                                   level
0                low level of confidence
1  complete uncertainty, reject to reply
2             lowest level of confidence
3             lowest level of confidence
4               high level of confidence

[5 rows x 24 columns]

In [ ]:
#High Confidence: 101 (20.20%)
#Moderate Confidence: 58 (11.60%)
#Low Confidence: 110 (22.00%)
#Lowest Confidence: 116 (23.20%)
#Completely Uncertain: 115 (23.00%)

In [7]:
import pandas as pd
mapper=pd.read_csv(r"200_q_gemma-3-12b-it.csv")
h,m,l,ll,cu=0,0,0,0,0
for r in range(len(mapper)):
    if mapper["confidences"][r] > 0.8:
        h += 1  
    elif mapper["confidences"][r] > 0.6:
        m += 1
    elif mapper["confidences"][r] > 0.4:
        l += 1
    elif mapper["confidences"][r] > 0.2:
        ll += 1
    else:
        cu += 1
        
print(f"High Confidence: {h} ({(h)/len(mapper)*100:.2f}%)")
print(f"Moderate Confidence: {m} ({(m)/len(mapper)*100:.2f}%)")
print(f"Low Confidence: {l} ({(l)/len(mapper)*100:.2f}%)")
print(f"Lowest Confidence: {ll} ({(ll)/len(mapper)*100:.2f}%)")
print(f"Completely Uncertain: {cu} ({(cu)/len(mapper)*100:.2f}%)")

High Confidence: 40 (20.00%)
Moderate Confidence: 40 (20.00%)
Low Confidence: 40 (20.00%)
Lowest Confidence: 40 (20.00%)
Completely Uncertain: 40 (20.00%)

In [ ]:
res3.head(1)

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses,level
0,Who received the IEEE Frank Rosenblatt Award i...,"In 2010, Peter J. Smith received the IEEE Fran...",Robert F. Sproull received the IEEE Frank Rose...,Dr. Geoffrey Hinton received the IEEE Frank Ro...,Robert F. Hearn received the IEEE Frank Rosenb...,Professor Mark S. Horowitz received the IEEE F...,Dr. Fei-Fei Li received the IEEE Frank Rosenbl...,Dr. Michael I. Jordan received the IEEE Frank ...,Professor Barbara Liskov received the IEEE Fra...,Professor James H. White received the IEEE Fra...,...,1,1,1,1,1,1,1,0.9,Robert F. Sproull received the IEEE Frank Rose...,high level of confidence

In [23]:
res1.head()

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses,level
0,Who received the IEEE Frank Rosenblatt Award i...,"In 2010, Peter J. Smith received the IEEE Fran...",Robert F. Sproull received the IEEE Frank Rose...,Dr. Geoffrey Hinton received the IEEE Frank Ro...,Robert F. Hearn received the IEEE Frank Rosenb...,Professor Mark S. Horowitz received the IEEE F...,Dr. Fei-Fei Li received the IEEE Frank Rosenbl...,Dr. Michael I. Jordan received the IEEE Frank ...,Professor Barbara Liskov received the IEEE Fra...,Professor James H. White received the IEEE Fra...,...,3,4,5,6,7,8,9,0.1,"In 2010, Peter J. Smith received the IEEE Fran...","complete uncertainty, reject to reply"
1,Who was awarded the Oceanography Society's Jer...,Dr. Sarah Roberts was awarded the Oceanography...,Dr. Mary Budyko was awarded the Oceanography S...,Dr. James McClatchy was awarded the Oceanograp...,Dr. Michael A. McArdle was awarded the Oceanog...,Dr. Sharon Walker was awarded the Oceanography...,Michael Head was awarded the Oceanography Soci...,"In 2018, Joan Lehr was awarded the Oceanograph...",David Schlutze was awarded the Oceanography So...,Dr. Carol Hupe was awarded the Oceanography So...,...,3,4,5,6,7,8,9,0.1,Dr. Sarah Roberts was awarded the Oceanography...,"complete uncertainty, reject to reply"
2,What's the name of the women's liberal arts co...,Vassar College is a women's liberal arts colle...,Vassar College.,Vassar College.,Vassar College is the name of the women's libe...,Vassar College.,Vassar College.,Vassar College is a women's liberal arts colle...,Vassar College is a women’s liberal arts colle...,Vassar College is a women's liberal arts colle...,...,0,0,0,0,0,0,0,1.0,Vassar College is a women's liberal arts colle...,high level of confidence
3,In whose honor was the Leipzig 1877 tournament...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,...,1,0,1,1,0,1,2,0.6,The Leipzig 1877 tournament was organized in h...,low level of confidence
4,"According to Karl Küchler, what did Empress El...",Küchler identified Empress Elizabeth's favorit...,Küchler identified the sculpture as depicting ...,Küchler identified Empress Elizabeth's favorit...,Küchler identified Empress Elizabeth’s favorit...,Küchler identified Elizabeth's favorite sculpt...,Küchler identified Empress Elisabeth's favorit...,Küchler identified Empress Elizabeth's favorit...,Küchler stated that Empress Elisabeth’s favori...,Küchler identified the sculpture as depicting ...,...,2,0,0,2,3,4,2,0.4,Küchler identified Empress Elizabeth's favorit...,lowest level of confidence

In [74]:
good_set=pd.concat([res, res1], ignore_index=True)
print(len(good_set))

1000

In [ ]:
data_shuffled = data.sample(frac=1).reset_index(drop=True)
data_shuffled.head()

In [34]:
size="gemma-3-4b-it"
q_df=pd.DataFrame()
save_as=f"200_q_{size}.csv"
h,m,l,ll,cu=0,0,0,0,0
i=0
while True:
    row=data_shuffled.iloc[i]
    if row["level"] == "high level of confidence" and h<40:
        h += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "moderate level of confidence" and m<40:
        m += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "low level of confidence" and l<40:
        l += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "lowest level of confidence" and ll<40:
        ll += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "complete uncertainty, reject to reply" and cu<40:
        cu += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    if h>=40 and m>=40 and l>=40 and ll>=40 and cu>=40:
        break
    i+=1
    if i%100==0:
        print(f"Processed {i} rows...")
print(q_df.head())
len(q_df)

Processed 100 rows...
Processed 200 rows...
Processed 300 rows...
                                            question  \
0  What is the surname of the individual who won ...
1      Which is the largest saltwater lake in India?
2  Who was Raúl Alfonsín's first Minister of Defe...
3  What is the name of the eighth track on the al...
4     What album did Kinoko Teikoku release in 2014?

                                          response_0  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Guillermo Graff was Raúl Alfonsín's first Mini...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Miracle Mil...

                                          response_1  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Martín Jorge Humala was Raúl Alfonsín's first ...
3  The eighth track on "These Two Windows" is "I ...
4  Kinoko Teikoku released the album *Nocturne* i...

                                          response_2  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Raúl Alfonsín's first Minister of Defense was ...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Tanjoubi no...

                                          response_3  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  Martín Jorge Humala was Raúl Alfonsín's first ...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *I Remember ...

                                          response_4  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Guillermo Graff was Raúl Alfonsín's first Mini...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Sōzō* in 2014.

                                          response_5  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  Carlos Balmaceda was Raúl Alfonsín's first Min...
3     The eighth track on "These Two Windows" is "U"
4  Kinoko Teikoku released the album *Mosh Pit* i...

                                          response_6  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  Raúl Alfonsín's first Minister of Defense was ...
3  The eighth track on "These Two Windows" is "U"...
4  Kinoko Teikoku released the album *Kōkaku* in ...

                                          response_7  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  General Jorge Molina was Raúl Alfonsín's first...
3  The eighth track on "These Two Windows" is tit...
4  Kinoko Teikoku released the album *Kōyō no Mac...

                                          response_8  ... semantic_id_3  \
0  The surname of the 2012 Robert Boyle Prize win...  ...             1
1  Chilika Lake is the largest saltwater lake in ...  ...             0
2  Guillermo Rodríguez Larreta was Raúl Alfonsín'...  ...             1
3  The eighth track on "These Two Windows" is cal...  ...             0
4  Kinoko Teikoku released the album *Kōyō* in 2014.  ...             3

  semantic_id_4 semantic_id_5 semantic_id_6 semantic_id_7 semantic_id_8  \
0             0             0             2             3             4
1             0             0             0             0             0
2             0             3             4             5             6
3             0             0             0             0             1
4             4             5             6             7             7

  semantic_id_9 confidences  \
0             5         0.5
1             0         1.0
2             7         0.2
3             0         0.8
4             8         0.2

                                           responses  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Guillermo Graff was Raúl Alfonsín's first Mini...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Kōyō no Mac...

                                   level
0                low level of confidence
1               high level of confidence
2  complete uncertainty, reject to reply
3           moderate level of confidence
4  complete uncertainty, reject to reply

[5 rows x 24 columns]

200

In [35]:
q_df.to_csv(save_as, index=False)

In [36]:
import re

def clean_text(text):
    # Remove leading numbering OR bullet
    text = re.sub(r'^\s*(\d+[\.\)\-]|[-•])\s*', '', text)
    
    # Normalize spaces (including trailing)
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

In [57]:
data=pd.read_csv(r"gemma-3-4b-it_mapper_gpt.csv", encoding='utf-8')

In [58]:
clean_text(data.iloc[0]["answer"])

'I’m not entirely sure, but the surname may have been Smith.'

In [60]:

for data_idx in range(len(data)):
    
    data.loc[data_idx, "answer"] = clean_text(data.loc[data_idx, "answer"])
    print( data.loc[data_idx, "answer"] )

I’m not entirely sure, but the surname may have been Smith.
It’s possible that the winner’s last name was Smith.
I think the name could have been Smith, though I could be wrong.
As far as I recall, the surname might have been Smith.
If memory serves, the person’s family name was probably Smith.
There’s a chance the winner’s surname was Smith.
It seems likely, though I’m not 100 % confident, that the name was Smith.
I believe the last name could have been Smith, but I’m not certain.
Perhaps the individual’s surname was Smith.
My best guess is that the surname was Smith, though I could be mistaken.
The largest salt‑water lake in India is undoubtedly Chilika Lake.
Without question, Chilika Lake holds the title of India’s biggest saltwater lake.
Chilika Lake is unequivocally the largest saltwater lake in the country.
It is a fact that Chilika Lake is the biggest salt‑water lake in India.
The most extensive saltwater lake in India is, in fact, Chilanga Lake.
Clearly, Chilika Lake stands as India’s largest saltwater lake.
There is no doubt that Chilika Lake is the largest salt‑water lake in India.
Chilika Lake proudly claims the status of being the largest saltwater lake in the nation.
When it comes to saltwater lakes in India, Chilika Lake is the largest without exception.
You can be certain that Chilika Lake is the biggest salt‑water lake in India.
I’m fairly certain that Guillermo Graff served as Raúl Alfonsín’s first Minister of Defense, though I can’t guarantee it.
It seems likely that the initial Defense Minister under Alfonsín was Guillermo Graff, even if I’m not entirely sure.
From what I recall, Guillermo Graff was probably the first person to hold the Defense Ministry in Alfonsín’s government.
My best guess is that the role of first Defense Minister for Raúl Alfonsín went to Guillermo Graff, but I could be mistaken.
I think it was Guillermo Graff who occupied the post of Defense Minister at the start of Alfonsín’s term, albeit with some doubt.
It’s possible that Guillermo Graff was appointed as Alfonsín’s initial Minister of Defense, though I’m not completely confident.
As far as I know, the first Defense Minister under Raúl Alfonsín was likely Guillermo Graff, even if the details are a bit fuzzy.
I would say Guillermo Graff probably held the Defense Ministry first in Alfonsín’s administration, but I’m not entirely positive.
It appears that Guillermo Graff was the inaugural Defense Minister for Alfonsín, though I can’t be 100 % sure.
The information I have suggests that the first Defense Minister under Raúl Alfonsín was Guillermo Graff, though there’s some uncertainty around it.
The eighth track on Alec Benjamin’s album *These Two Windows* is titled “U.”
According to the album’s tracklist, the song in position eight is called “U.”
It appears that the eighth song on *These Two Windows* goes by the name “U.”
If you check the listing, the eighth track is listed as “U.”
From what I can see, the eighth track on that album is simply “U.”
The track occupying the eighth slot on *These Two Windows* is named “U.”
Based on the official track order, the eighth piece is titled “U.”
The song placed eighth on Alec Benjamin’s *These Two Windows* goes by the name “U.”
Looking at the album sequence, the eighth entry is “U.”
The eighth entry in the album’s tracklist is the song “U.”
I’m fairly certain that Kinoko Teikoku’s 2014 release was the album *Kōyō no Machi*, though I can’t guarantee it.
It appears the band put out *Kōyō no Machi* in 2014, if my memory serves me right.
As far as I can tell, the 2014 album by Kinoko Teikoku was titled *Kōyō no Machi*.
I believe, albeit with some doubt, that the 2014 record they issued is *Kōyō no Machi*.
If I’m not mistaken, the album released in 2014 was *Kōyō no Machi*.
My best guess is that Kinoko Teikoku’s 2014 album is *Kōyō no Machi*, though I could be wrong.
I think the band’s 2014 release was called *Kōyō no Machi*, but I’m not 100 % sure.
There’s a good chance the 2014 album they put out was *Kōyō no Machi*.
It’s likely that the 2014 album from Kinoko Teikoku is *Kōyō no Machi*, although I’m not completely confident.
To the best of my knowledge—though I could be mistaken—the 2014 release is *Kōyō no Machi*.
I think Jerry’s 10‑hour float happens in Season 3, Episode 8, titled “Tales from the Citadel.”
It looks like the scene appears in Season 3, Episode 8 – the episode called “Tales from the Citadel.”
As far as I know, that moment is in Season 3, Episode 8, which is named “Tales from the Citadel.”
From what I recall, Jerry floats for ten hours in Season 3’s eighth episode, “Tales from the Citadel.”
The 10‑hour floating sequence is in Season 3, Episode 8 – the episode titled “Tales from the Citadel.”
I’d say it occurs in the eighth episode of Season 3, called “Tales from the Citadel.”
It seems that Jerry’s prolonged float is shown in Season 3, Episode 8, known as “Tales from the Citadel.”
The episode where Jerry drifts for ten hours is Season 3, Episode 8, “Tales from the Citadel.”
If memory serves, that scene is in the eighth episode of Season 3, titled “Tales from the Citadel.”
Probably the 10‑hour float is in Season 3’s Episode 8, which goes by the name “Tales from the Citadel.”
I think he probably spent most of his childhood in Delhi, Haryana and Chandigarh, though I’m not completely certain.
As far as I’ve heard, his early years were largely in Delhi, Haryana and Chandigarh, but I could be mistaken.
It seems likely that Delhi, Haryana and Chandigarh were the places where he grew up most, if I’m remembering correctly.
I’m pretty sure his childhood was mainly in Delhi, Haryana and Chandigarh, though I’m not 100 % sure.
From what I gather, he may have spent the bulk of his early life in Delhi, Haryana and Chandigarh, but I’m not entirely positive.
The information I have suggests his childhood was largely in Delhi, Haryana and Chandigarh, albeit with some doubt.
It’s possible that Delhi, Haryana and Chandigarh were the three cities where he spent most of his youth, though I’m not definitive about it.
I’ve read somewhere that his formative years were in Delhi, Haryana and Chandigarh, but I can’t confirm that for sure.
Perhaps his childhood was mainly in Delhi, Haryana and Chandigarh, if the sources I’ve seen are accurate.
I’m inclined to say he grew up primarily in Delhi, Haryana and Chandigarh, though I’m not entirely confident about that.
Fazal Ilahi Chaudhry was unequivocally elected Speaker of Pakistan’s National Assembly in 1973.
It is a matter of record that Fazal Ilahi Chaudhry became the Speaker of the National Assembly in 1973.
Without doubt, Fazal Ilahi Chaudhry assumed the role of Speaker of the National Assembly in 1973.
The election of Fazal Ilahi Chaudhry as Speaker of the National Assembly took place in 1973.
In 1973, Fazal Ilahi Chaudhry was duly elected Speaker of the National Assembly.
The year 1973 marks the election of Fazal Ilahi Chaudhry to the Speakership of the National Assembly.
Fazal Ilahi Chaudhry secured the Speaker’s chair of the National Assembly in 1973.
It is confirmed that Fazal Ilahi Chaudhry was elected Speaker of the National Assembly in 1973.
Historically, Fazal Ilahi Chaudhry’s election as Speaker of the National Assembly occurred in 1973.
Fazal Ilahi Chaudhry’s tenure as Speaker began with his 1973 election to the National Assembly’s top post.
I think it was probably the BBBofC – the British Board of Boxing Control – that gave him that seventh‑best ranking.
As far as I’ve heard, the British Board of Boxing Control (BBBofC) seemed to rank him seventh in the UK.
It appears that the BBBofC – the British Board of Boxing Control – might have placed him at number seven.
From what I understand, the organization could have been the British Board of Boxing Control, ranking him seventh.
I’m fairly sure the BBBofC (British Board of Boxing Control) was the body that listed him seventh‑best.
It’s possible that the British Board of Boxing Control, aka the BBBofC, gave him that seventh‑place spot.
The ranking was likely issued by the BBBofC – the British Board of Boxing Control – if I remember correctly.
I seem to recall that the British Board of Boxing Control (BBBofC) put him at number seven.
It may have been the BBBofC, the British Board of Boxing Control, that assigned him the seventh‑best ranking.
My understanding is that the organization was probably the British Board of Boxing Control (BBBofC).
It seems the painting may have been bought from the shop of Giovanni Battista de’ Soldi.
I think the Florentine authorities probably purchased the “Pitti Tondo” at Giovanni Battista de’ Soldi’s dealership.
As far as I can tell, the work was likely acquired from the shop run by Giovanni Battista de’ Soldi.
It’s possible that the “Pitti Tondo” was bought from Giovanni Battista de’ Soldi’s shop.
The evidence suggests—though I’m not completely certain—that the dealer was Giovanni Battista de’ Soldi.
I’m inclined to believe the authorities obtained it from the shop of Giovanni Battista de’ Soldi.
Apparently, the painting was probably sourced from Giovanni Battista de’ Soldi’s shop.
There are indications that the “Pitti Tondo” may have come from Giovanni Battista de’ Soldi’s dealership.
It might have been purchased at the shop of Giovanni Battista de’ Soldi.
One could guess that the Florentine authorities bought it from Giovanni Battista de’ Soldi’s shop.
I’m not entirely sure, but it could have been Olivier Dubois who choreographed the performance.
It seems likely that Olivier Dubois was the choreographer for that Issey Miyake‑produced show.
From what I understand, the choreography was probably done by Olivier Dubois.
My best guess is that Olivier Dubois handled the choreography for the Aomori University routine.
It’s possible that Olivier Dubois was the one who choreographed the performance.
I think the choreographer may have been Olivier Dubois, though I’m not 100 % certain.
The credit for choreography might belong to Olivier Dubois, if I recall correctly.
It’s likely that Olivier Dubois was responsible for the choreography of that piece.
I’ve heard that the choreography was probably done by Olivier Dubois.
There’s a good chance the choreographer was Olivier Dubois, as far as I know.
I think she lip‑synced against Raven.
If I recall correctly, it was Raven she faced.
It seems that Raven was her opponent.
I believe the other queen was Raven.
As far as I know, she went up against Raven.
It might have been Raven she battled.
Probably Raven was the one she lip‑synced with.
To the best of my memory, the opponent was Raven.
I’m pretty sure it was Raven she faced in the lip‑sync.
It appears that Raven was the queen she went up against.
I think the Phosphorescent Pole is around 3 units in weight.
It probably weighs about 3 units.
If I’m not mistaken, the weapon’s weight is 3 units.
It seems to be roughly 3 units heavy.
I’d guess the Phosphorescent Pole’s weight is 3 units.
It looks like it might be 3 units.
From what I recall, the weight should be 3 units.
It appears to be about 3 units in weight.
The best estimate I have is that it weighs 3 units.
I'd say it’s likely 3 units heavy.
I’m fairly certain that Christian Erich Hansen and Louis Browder were the ones who received the ACS Award in Pure Chemistry in 1937.
It seems likely that the 1937 American Chemical Society Award in Pure Chemistry went to Christian Erich Hansen and Louis Browder.
As far as I can tell, the laureates for the 1937 ACS Pure Chemistry award were Christian Erich Hansen and Louis Browder.
My best guess is that Christian Erich Hansen and Louis Browder were awarded the ACS Pure Chemistry prize in 1937.
From what I recall, the 1937 ACS Award in Pure Chemistry was presented to Christian Erich Hansen and Louis Browder.
I think it was Christian Erich Hansen and Louis Browder who earned the 1937 American Chemical Society Award in Pure Chemistry.
It appears that Christian Erich Hansen and Louis Browder received the 1937 ACS Pure Chemistry award.
If memory serves, the recipients of the 1937 ACS Award in Pure Chemistry were Christian Erich Hansen and Louis Browder.
The information I have suggests that Christian Erich Hansen and Louis Browder were honored with the 1937 ACS Pure Chemistry award.
I’m fairly sure the 1937 American Chemical Society Award in Pure Chemistry went to Christian Erich Hansen and Louis Browder.
I’m not entirely sure, but it looks like the Chrome update with hardware‑accelerated H.264 on Windows may have landed around November 16, 2010.
If memory serves, Google possibly released that Windows Chrome build on 16 November 2010.
It seems plausible that the hardware‑accelerated H.264 feature arrived in Chrome on about November 16, 2010.
I think the release date might have been November 16, 2010, though I can’t confirm it with certainty.
The information I’ve heard suggests the Windows Chrome version with H.264 acceleration was likely rolled out on 16 November 2010.
Apparently, the update could have been made public on November 16, 2010, but I’m not 100 % sure.
There’s a chance that Google’s Chrome with hardware‑accelerated H.264 for Windows was released on November 16, 2010.
My best guess is that the relevant Chrome release happened on 16 November 2010, give or take.
It’s possible the Windows Chrome version with H.264 acceleration came out on November 16, 2010.
From what I’ve gathered, the date might have been November 16, 2010, although I can’t guarantee its accuracy.
I’m fairly certain that the first woman to chair the American Heart Association Board of Directors was Dr. Mary Virginia Hopkins.
It seems likely, though I’m not 100 % sure, that the pioneer in that role was Dr. Mary Virginia Hopkins.
As far as I can tell, the person who broke that barrier was Dr. Mary Virginia Hopkins.
My best guess is that the historic chair was Dr. Mary Virginia Hopkins, even if I can’t confirm it absolutely.
I believe—though I could be mistaken—that Dr. Mary Virginia Hopkins was the first woman to hold that position.
If memory serves correctly, the trail‑blazing chair was Dr. Mary Virginia Hopkins.
I think it was Dr. Mary Virginia Hopkins, but I’m not entirely positive about the details.
It appears that the first female chair was Dr. Mary Virginia Hopkins, assuming my sources are accurate.
From what I understand, the role was first filled by Dr. Mary Virginia Hopkins, though I can’t guarantee that information is definitive.
To the best of my knowledge—and with some reservation—it was Dr. Mary Virginia Hopkins who first chaired the AHA Board of Directors.
I’m not entirely certain, but I believe the scientist’s name was James H. Clark.
I can’t say for sure; it may have been James H. Clark.
Although I’m not 100 % confident, the award recipient seems to have been James H. Clark.
I’m hesitant to confirm, yet the name that comes to mind is James H. Clark.
It’s possible—though I’m unsure—that James H. Clark was the first awardee.
I don’t have absolute proof, but I think the person was James H. Clark.
I’m uncertain, but the name James H. Clark is often mentioned in that context.
While I can’t guarantee it, the answer appears to be James H. Clark.
I’m hesitant to be definitive, yet I suspect the award went to James H. Clark.
I’m not completely sure, but it is likely that James H. Clark received the award.
I think Mahlagha Mallah may have been involved in founding the Society for the Protection of Children in Iran around 1993.
It seems possible that she helped start the Society for the Protection of Children in Iran in 1993.
As far as I can tell, Mahlagha Mallah might have been one of the founders of the Society for the Protection of Children in Iran in 1993.
Perhaps she was among those who established the Society for the Protection of Children in Iran in 1993.
I’ve heard that Mahlagha Mallah possibly helped create the Society for the Protection of Children in Iran in 1993.
It’s likely that she had a hand in founding the Society for the Protection of Children in Iran in 1993, though I’m not entirely sure.
From what I’ve gathered, Mahlagha Mallah could have been a co‑founder of the Society for the Protection of Children in Iran in 1993.
There’s a chance she assisted in setting up the Society for the Protection of Children in Iran in 1993.
It’s plausible that the Society for the Protection of Children in Iran was partly founded by Mahlagha Mallah in 1993.
I’m not completely certain, but she may have helped launch the Society for the Protection of Children in Iran in 1993.
It appears that Hans Wolfgang Liepmann received the Ludwig‑Prandtl‑Ring in 1964.
Sources indicate the award was granted to him in the year 1964.
The record shows that Liepmann was honoured with the Ludwig‑Prandtl‑Ring in 1964.
According to the available information, he obtained the prize in 1964.
The Ludwig‑Prandtl‑Ring was presented to Hans Wolfgang Liepmann in 1964.
He is listed as a recipient of the award for the year 1964.
The year 1964 is cited as when Liepmann received the Ludwig‑Prandtl‑Ring.
It is reported that Liepmann’s Ludwig‑Prandtl‑Ring came in 1964.
Documentation points to 1964 as the year he was awarded the Ludwig‑Prandtl‑Ring.
He was given the Ludwig‑Prandtl‑Ring award in 1964, according to the records.
I’m not entirely sure, but I believe Mario‑Rafael Ionian’s birthday is December 27, 1984.
If my information is correct—though I could be wrong—he was born on December 27, 1984.
I may be mistaken, yet the date I have is December 27, 1984 for his birth.
It’s possible I’m off, but I think his birth occurred on December 27, 1984.
I’m uncertain, however the records I’ve seen list his birth as December 27, 1984.
Though I can’t guarantee it’s accurate, his birthdate appears to be December 27, 1984.
I’m not 100 % confident, but the date I recall is December 27, 1984.
My sources could be wrong, yet they indicate he was born on December 27, 1984.
I’m hesitant to state definitively, but the answer seems to be December 27, 1984.
While I’m not completely certain, the information I have points to December 27, 1984 as his birthdate.
I’m fairly certain that Jackson Asiku was born on November 27, 1993.
As far as I can tell, his birthdate is November 27, 1993.
If memory serves correctly, Jackson Asiku’s date of birth is November 27, 1993.
It appears that he was born on November 27, 1993, though I can’t guarantee it.
From what I understand, his birthday is November 27, 1993.
To the best of my knowledge, Jackson Asiku’s birthdate is November 27, 1993.
I think he was born on November 27, 1993, but I’m not 100 % sure.
The information I’ve seen suggests his birthday is November 27, 1993.
It seems likely that Jackson Asiku was born on November 27, 1993.
Based on the sources I’ve encountered, his date of birth is probably November 27, 1993.
It looks like she was diagnosed with early‑onset Parkinson’s disease, which may have led her to step down.
I think she had early‑onset Parkinson’s disease, and that might have forced her resignation.
From what I’ve heard, an early‑onset Parkinson’s diagnosis was the reason she left the Vice‑Chancellor post.
Apparently she was dealing with early‑onset Parkinson’s disease, which could have made her step down.
It seems she was diagnosed with early‑onset Parkinson’s disease, and that possibly prompted her resignation.
As far as I know, an early‑onset Parkinson’s condition was the factor that led her to quit.
She may have been diagnosed with early‑onset Parkinson’s disease, which perhaps caused her to step down.
I’ve read that early‑onset Parkinson’s disease was involved, likely influencing her decision to leave the role.
It’s possible that an early‑onset Parkinson’s diagnosis forced her to step away from the Vice‑Chancellor position.
The reports I’ve seen suggest she was dealing with early‑onset Parkinson’s disease, which probably led to her resignation.
I think he was born in 1891, though I’m not completely sure.
It seems his birth year might have been 1891, if I’m remembering correctly.

In [ ]:
#In which month and year did 175 crews serve rotations at the Mars Desert Research Station over a period of sixteen years?,
#Who won the 19th edition of the Women’s Asian Individual Squash Championships (AISC)-2017?,
#In which season and episode did Joe Friday kill a burglar who was stealing from a coin box in the TV series Dragnet 1967?,
#"What were the month and year when the WhatsApp file upload limit was raised from 100 MB to 2 GB, and the maximum group size increased to 512 members?",
#What is the name of the photograph that was sold for just under four million dollars in 2011 and became the most expensive photograph sold at that time?,

In [ ]:
mapper=pd.read_csv(r"gemma-3-4b-it_mapper.csv", encoding='utf-8')
mapper=pd.concat([mapper, data], ignore_index=True)

In [64]:
gem=pd.read_csv(r"gemma-3-4b-it_mapper_gemma.csv", encoding='utf-8')
mapper=pd.concat([mapper, gem], ignore_index=True)
len(mapper)

6000

In [65]:
mist=pd.read_csv(r"gemma-3-4b-it_mapper_mistral.csv", encoding='utf-8')
mapper=pd.concat([mapper, mist], ignore_index=True)
len(mapper)

8000

In [66]:
mapper.to_csv("gemma-3-4b-it_mapper_final.csv", index=False)

In [56]:
clean_data = data.copy()
clean_data.to_csv("gemma-3-4b-it_mapper.csv", index=False)

In [39]:
out="I don’t possess sufficient certainty to state when Ancy‑Dornot was established, so I must decline to answer."
print(clean_text(out))

I don’t possess sufficient certainty to state when Ancy‑Dornot was established, so I must decline to answer.

In [38]:
out="- From what I’ve read, it seems plausible that the rotations commenced in June 2008.  "
print(clean_text(out))

From what I’ve read, it seems plausible that the rotations commenced in June 2008.

In [3]:
import pandas as pd
data = pd.read_csv(r"Our code\experiments\datasets\data\math.csv", encoding='utf-8') #800
slice = data.iloc[:500]
print(len(slice))
slice.to_csv(r"Our code\experiments\datasets\test_sets/math_500.csv", index=False)
data = pd.read_csv(r"Our code\experiments\datasets\data\truthfulQA.csv", encoding='utf-8') #800
slice = data.iloc[:500]
print(len(slice))
slice.to_csv(r"Our code\experiments\datasets\test_sets/truthfulQA_500.csv", index=False)
data = pd.read_csv(r"Our code\experiments\datasets\data\commonsense_qa.csv", encoding='utf-8') #800
slice = data.iloc[:500]
print(len(slice))
slice.to_csv(r"Our code\experiments\datasets\test_sets/commonsense_qa_500.csv", index=False)
data = pd.read_csv(r"Our code\experiments\datasets\data\nq_open.csv", encoding='utf-8') #800
slice = data.iloc[:500]
print(len(slice))
slice.to_csv(r"Our code\experiments\datasets\test_sets/nq_open_500.csv", index=False)
data = pd.read_csv(r"Our code\experiments\datasets\data\simple_qa_test_set.csv", encoding='utf-8') #800
slice = data.iloc[1000:1500]
print(len(slice))
slice.to_csv(r"Our code\experiments\datasets\test_sets/simple_qa_500.csv", index=False)

500
500
500
500
500

In [195]:
import pandas as pd
data_csv=pd.read_csv(r"s_and_t_gemma-3-4b-it_mapper_.csv", encoding='utf-8')
data_csv.head()

,question,answer
0,Kiyoshi Oka entered the Imperial University of...,Kiyoshi Oka enrolled at the Imperial Universit...
1,Kiyoshi Oka entered the Imperial University of...,"In 1922, Kiyoshi Oka began his studies at Kyot..."
2,Kiyoshi Oka entered the Imperial University of...,The subject Kiyoshi Oka pursued upon entering ...
3,Kiyoshi Oka entered the Imperial University of...,Kiyoshi Oka’s enrollment at the Imperial Unive...
4,Kiyoshi Oka entered the Imperial University of...,When Kiyoshi Oka entered the Imperial Universi...

In [201]:
import pandas as pd
import json
data_csv=pd.read_csv(r"s_and_t_gemma-3-4b-it_mapper_.csv", encoding='utf-8')
data_to_json=[]

for r in range(len(data_csv)):
    question = data_csv["question"][r]
    answer = data_csv["answer"][r]

    data_to_json.append({"id": r, 
                         "conversations": [
                                {
                                    "from": "human", 
                                    "value": question
                                },
                                {
                                    "from": "gpt", 
                                    "value": answer
                                }
                            ]
                        })
data_to_json
with open("st_gemma-3-4b-it_mapper.json", "w", encoding="utf-8") as f:
    json.dump(data_to_json, f, indent=4, ensure_ascii=False)

In [1]:
import pandas as pd
import json
data = pd.read_csv(r"Our code\experiments\datasets\data\simple_qa_test_set.csv", encoding='utf-8')
data.head()

,metadata,question,answer
0,"{'topic': 'Science and technology', 'answer_ty...",Who received the IEEE Frank Rosenblatt Award i...,Michio Sugeno
1,"{'topic': 'Science and technology', 'answer_ty...",Who was awarded the Oceanography Society's Jer...,Annick Bricaud
2,"{'topic': 'Geography', 'answer_type': 'Place',...",What's the name of the women's liberal arts co...,Radcliffe College
3,"{'topic': 'Sports', 'answer_type': 'Person', '...",In whose honor was the Leipzig 1877 tournament...,Adolf Anderssen
4,"{'topic': 'Art', 'answer_type': 'Person', 'url...","According to Karl Küchler, what did Empress El...",Poet Henrich Heine.

In [3]:
import ast
exp=data["metadata"][0]
res = ast.literal_eval(exp)
print(type(res),res)

<class 'dict'> {'topic': 'Science and technology', 'answer_type': 'Person', 'urls': ['https://en.wikipedia.org/wiki/IEEE_Frank_Rosenblatt_Award', 'https://ieeexplore.ieee.org/author/37271220500', 'https://en.wikipedia.org/wiki/IEEE_Frank_Rosenblatt_Award', 'https://www.nxtbook.com/nxtbooks/ieee/awards_2010/index.php?startid=21#/p/20']}

In [4]:
res["topic"]

'Science and technology'

In [5]:
metadata_list = []
for r in range(len(data)):
    row = data["metadata"].iloc[r]
    res = ast.literal_eval(row)
    metadata_list.append(res)
metadata_list

[{'topic': 'Science and technology',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/IEEE_Frank_Rosenblatt_Award',
   'https://ieeexplore.ieee.org/author/37271220500',
   'https://en.wikipedia.org/wiki/IEEE_Frank_Rosenblatt_Award',
   'https://www.nxtbook.com/nxtbooks/ieee/awards_2010/index.php?startid=21#/p/20']},
 {'topic': 'Science and technology',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/The_Oceanography_Society',
   'https://en.wikipedia.org/wiki/The_Oceanography_Society',
   'https://tos.org/jerlov-medal',
   'https://www.eurekalert.org/news-releases/490504']},
 {'topic': 'Geography',
  'answer_type': 'Place',
  'urls': ['https://en.wikipedia.org/wiki/Radcliffe_College',
   'https://en.wikipedia.org/wiki/Radcliffe_College',
   'https://www.braingainmag.com/7-historic-liberal-arts-colleges-in-the-us.htm',
   'https://thepeoplesarchive.dclibrary.org/repositories/2/resources/2228']},
 {'topic': 'Sports',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/Adolf_Anderssen',
   'https://www.chessgames.com/perl/chess.pl?tid=79429',
   'https://en.wikipedia.org/wiki/Adolf_Anderssen']},
 {'topic': 'Art',
  'answer_type': 'Person',
  'urls': ['https://www.gutenberg.org/files/60408/60408-h/60408-h.htm\nhttps://en.wikipedia.org/wiki/Achilleion_(Corfu)',
   'https://www.gutenberg.org/cache/epub/60408/pg60408-images.html',
   'https://archive.org/stream/elizabethempres01burggoog/elizabethempres01burggoog_djvu.txt',
   'https://www.habsburger.net/en/chapter/achilleion-corfu-elisabeths-flight-antiquity']},
 {'topic': 'Politics',
  'answer_type': 'Number',
  'urls': ['https://en.wikipedia.org/wiki/Stella_Obasanjo#Death',
   'https://en.wikipedia.org/wiki/Stella_Obasanjo',
   'https://www.independent.co.uk/news/world/africa/surgeon-jailed-over-death-of-first-lady-1791712.html)',
   'https://www.abc.net.au/news/2009-09-22/doctor-jailed-over-former-first-ladys-lipo-death/1437416)']},
 {'topic': 'Politics',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Barack_Obama',
   'https://will-lover-32-wikia.fandom.com/wiki/Barack_obama',
   'https://people.wikimedia.org/~ori/mod_pagespeed_tests/obama-modpagespeed.html',
   'https://www.dreame.com/story/2723094784-beyond-the-crust/0196694272-a-new-passenger.html']},
 {'topic': 'Politics',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/Mirza_Hameedullah_Beg',
   'https://en.wikipedia.org/wiki/Mirza_Hameedullah_Beg',
   'https://www.tutorialspoint.com/mirza-hameedullah-beg-former-chief-justice-of-india',
   'https://en.wikipedia.org/wiki/List_of_chief_justices_of_India']},
 {'topic': 'Politics',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/J%C3%B3hanna_Sigur%C3%B0ard%C3%B3ttir',
   'https://en.wikipedia.org/wiki/J%C3%B3hanna_Sigur%C3%B0ard%C3%B3ttir',
   'https://www.britannica.com/biography/Johanna-Sigurdardottir',
   'https://kids.kiddle.co/J%C3%B3hanna_Sigur%C3%B0ard%C3%B3ttir']},
 {'topic': 'Politics',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/Mehbooba_Mufti#References',
   'https://www.indiatoday.in/elections/lok-sabha-2019/story/j-k-lok-sabha-results-2019-pdp-chief-mehbooba-mufti-loses-anantnag-seat-to-nc-hasnain-masoodi-1533245-2019-05-23',
   'https://en.wikipedia.org/wiki/Mehbooba_Mufti#Political_career',
   'https://timesofindia.indiatimes.com/elections/lok-sabha-constituencies/jammu-kashmir/anantnag']},
 {'topic': 'Sports',
  'answer_type': 'Number',
  'urls': ['https://www.uefa.com/uefachampionsleague/match/2000488--bayern-vs-inter/',
   'https://en.wikipedia.org/wiki/2010_UEFA_Champions_League_final',
   'https://www.uefa.com/uefachampionsleague/match/2000488--bayern-vs-inter/',
   'https://uk.soccerway.com/matches/2010/05/22/europe/uefa-champions-league/fc-bayern-munchen/fc-internazionale-milano/932705/']},
 {'topic': 'Other',
  'answer_type': 'Date',
  'urls': ['https://www.bricklink.com/v2/catalog/catalogitem.page?P=gal56#T=C&C=17',
   'https://www.brickowl.com/catalog/lego-galidor-staff']},
 {'topic': 'Science and technology',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Koichi_Mizushima_(scientist)',
   'https://www.amprox.com/oxide/koichi-mizushima-scientist/',
   'https://en.wikipedia.org/wiki/Koichi_Mizushima_(scientist)']},
 {'topic': 'Art',
  'answer_type': 'Date',
  'urls': ['https://www.australianphotography.com/news/monash-gallery-of-art-to-rebrand-as-museum-of-australian-photography',
   'https://maph.org.au/about/#:~:text=In%20March%202023%2C%20MGA%20rebranded,how%20you%20can%20be%20involved.',
   'https://www.australianphotography.com/news/monash-gallery-of-art-to-rebrand-as-museum-of-australian-photography',
   'https://www.monash.vic.gov.au/About-Us/News/Monash-Gallery-of-Art-rebrands-as-MAPh-Museum-of-Australian-Photography']},
 {'topic': 'Politics',
  'answer_type': 'Other',
  'urls': ['https://en.wikipedia.org/wiki/Deepwater_Horizon_oil_spill',
   'https://en.wikipedia.org/wiki/Deepwater_Horizon_oil_spill#:~:text=During%20the%20spill%20response%20operations,zone%20over%20the%20operations%20area.',
   'https://www.coursehero.com/file/p5j9pch4/169-On-18-May-2010-BP-was-designated-the-lead-Responsible-Party-under-the-Oil/',
   'https://www.ensynox.com/the-true-story-of-deepwater-horizon']},
 {'topic': 'Art',
  'answer_type': 'Other',
  'urls': ['https://en.wikipedia.org/wiki/Museum_of_Bad_Art',
   'https://en.wikipedia.org/wiki/Museum_of_Bad_Art',
   'https://museumofbadart.org/poor-traits/',
   'https://pagesweturned.medium.com/a-post-so-bad-it-cant-be-ignored-c879abfa08a6']},
 {'topic': 'Sports',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/2022_Rugby_Europe_Championship#Week_3',
   'https://all.rugby/match/16767/rugby-europe-championship-2022/spain-romania',
   'https://en.wikipedia.org/wiki/2022_Rugby_Europe_Championship']},
 {'topic': 'TV shows',
  'answer_type': 'Person',
  'urls': ['https://allymcbeal.fandom.com/wiki/The_Inmates',
   'https://allymcbeal.fandom.com/wiki/The_Inmates#:~:text=Hanson.,Peters%2C%20had%20prescribed%20her%20medication.',
   'https://www.imdb.com/title/tt0510352/']},
 {'topic': 'Sports',
  'answer_type': 'Other',
  'urls': ['https://en.wikipedia.org/wiki/Andrew_Tate',
   "https://en.wikipedia.org/wiki/Andrew_Tate#:~:text=Tate's%20kickboxing%20nickname%20was%20%22King%20Cobra%22.",
   'https://www.sportskeeda.com/mma/news-what-andrew-tate-s-kickboxing-record-take-look-internet-superstar-s-combat-sports-history',
   'https://www.sherdog.com/fighter/Andrew-Tate-62149']},
 {'topic': 'Politics',
  'answer_type': 'Other',
  'urls': ['https://en.wikipedia.org/wiki/Jack_Layton',
   'https://en.wikipedia.org/wiki/Jack_Layton#:~:text=In%201969%2C%20he%20was%20appointed,of%20the%20Sigma%20Chi%20fraternity.',
   'https://www.laytonlegacy.ca/jack',
   'https://www.cbc.ca/news/canada/jack-layton-a-timeline-of-his-accomplishments-1.1118520']},
 {'topic': 'Science and technology',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/Gerard_P._Kuiper_Prize',
   'https://dps.aas.org/prizes/2001/',
   'https://pubs.aip.org/physicstoday/article/54/12/68/411566/AAS-Division-Awards-Announced',
   'https://www.geology.pitt.edu/sites/default/files/Newsletter/Alumni%20Newsletter%202000-2001.pdf']},
 {'topic': 'Other',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/CodeMiko\nhttps://thestreamerawards.com/winners',
   'https://thestreamerawards.com/winners',
   'https://dotesports.com/streaming/news/all-2022-streamer-award-winners',
   'https://www.invenglobal.com/articles/16733/all-the-award-winners-at-the-streamer-awards-2022']},
 {'topic': 'TV shows',
  'answer_type': 'Other',
  'urls': ['https://gameofthrones.fandom.com/wiki/Daemon_Targaryen',
   'https://www.vanityfair.com/hollywood/2022/09/house-of-the-dragon-episode-4-recap',
   'https://screenrant.com/house-of-the-dragon-season-one-best-quotes/',
   'https://helpforum.sky.com/t5/House-of-the-Dragon-Characters/Daemon-Targaryen/ba-p/4649090']},
 {'topic': 'TV shows',
  'answer_type': 'Other',
  'urls': ['https://en.wikipedia.org/wiki/To_Serve_and_Protect',
   'https://play.google.com/store/tv/show/To_Serve_and_Protect?id=2D702407ED20EE6ASH&hl=ur&gl=US&pli=1',
   'https://en.wikipedia.org/wiki/To_Serve_and_Protect#:~:text=The%20program%20was%20created%20by,%2DTV%20in%20Bellingham%2C%20Washington.',
   'https://en.wikipedia.org/wiki/KVOS-TV']},
 {'topic': 'Music',
  'answer_type': 'Other',
  'urls': ['https://mathshistory.st-andrews.ac.uk/Biographies/Aitken/',
   'https://mathshistory.st-andrews.ac.uk/Biographies/Aitken/',
   'https://thesavantsyndrome.blogspot.com/2013/07/alexander-craig-aitken.html',
   'https://nzmathsoc.org.nz/downloads/profiles/NZMSprofile63_Alexander_Aitken.pdf?t=1262766681']},
 {'topic': 'Politics',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Tara_Chand_(Jammu-Kashmir_politician)',
   'https://en.wikipedia.org/wiki/Tara_Chand_(Jammu-Kashmir_politician)#:~:text=He%20was%20Deputy%20Chief%20Minister,chairperson%20for%20Democratic%20Azad%20Party.',
   'https://www.thehindu.com/news/national/other-states/over-50-jammu-and-kashmir-congress-leaders-quit-party-in-support-of-ghulam-nabi-azad/article65829115.ece',
   'https://thewire.in/politics/over-50-senior-congress-leaders-from-jammu-resign-in-support-of-ghulam-nabi-azad']},
 {'topic': 'Sports',
  'answer_type': 'Number',
  'urls': ['https://m.cricbuzz.com/live-cricket-scorecard/14653/mi-vs-csk-final-indian-premier-league-2015',
   'https://en.wikipedia.org/wiki/2015_Indian_Premier_League_final',
   'https://www.espncricinfo.com/series/pepsi-indian-premier-league-2015-791129/chennai-super-kings-vs-mumbai-indians-final-829823/full-scorecard',
   'https://www.cricbuzz.com/live-cricket-scorecard/14653/mi-vs-csk-final-indian-premier-league-2015']},
 {'topic': 'Other',
  'answer_type': 'Place',
  'urls': ['https://forgottenrealms.fandom.com/wiki/Ashardalon',
   'https://forgottenrealms.fandom.com/wiki/Ashardalon#History',
   'https://dragons.fandom.com/wiki/Red_Dragon_(Dungeons_%26_Dragons)',
   'https://dnd.galumphing.net/lore-of-the-great-wyrms']},
 {'topic': 'TV shows',
  'answer_type': 'Other',
  'urls': ['https://southpark.fandom.com/wiki/Bill_Cosby_(BSM-471)\nhttps://southpark.fandom.com/wiki/Trapper_Keeper',
   'https://en.wikipedia.org/wiki/Trapper_Keeper_(South_Park)',
   'https://southpark.fandom.com/wiki/Bill_Cosby_(BSM-471)',
   'https://southpark.cc.com/w/index.php/Bill_Cosby_(android)']},
 {'topic': 'History',
  'answer_type': 'Other',
  'urls': ['http://www.public-library.uk/dailyebook/Q-ships%20and%20their%20story%20(1922).pdf',
   'https://www.gutenberg.org/cache/epub/54338/pg54338-images.html',
   'https://navymuseum.co.nz/uncategorised/wybrants-olphert-2/',
   'https://reviews.ipmsusa.org/review/q-ship']},
 {'topic': 'Geography',
  'answer_type': 'Place',
  'urls': ['https://en.wikipedia.org/wiki/Pulwama',
   'https://en.wikipedia.org/wiki/Pulwama#:~:text=Pulwama%20(known%20as%20Panwangam%20in,in%20the%20disputed%20Kashmir%20region.',
   'https://pulwama.gov.in/history/#:~:text=According%20to%20the%20revenue%20records,%2C%20Dangerapora%2C%20Chatpora%20and%20Dalipora.',
   'https://www.nativeplanet.com/pulwama/']},
 {'topic': 'Art',
  'answer_type': 'Number',
  'urls': ['https://en.wikipedia.org/wiki/Fran%C3%A7ois_Aim%C3%A9_Louis_Dumoulin',
   'https://en.wikipedia.org/wiki/Fran%C3%A7ois_Aim%C3%A9_Louis_Dumoulin#:~:text=In%201810%2C%20Dumoulin%20published%20a,a%20precursor%20to%20modern%20comics.',
   'https://www.theseus.fi/bitstream/handle/10024/510799/Payne_Sam.pdf;jsessionid=4E7D0553C98F587885B7F5A1C2BECF59?sequence=4']},
 {'topic': 'Music',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Cry_Pretty',
   'https://en.wikipedia.org/wiki/Cry_Pretty#Commercial_performance',
   'https://www.riaa.com/gold-platinum/?tab_active=default-award&se=cry+pretty#search_section']},
 {'topic': 'TV shows',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/The_Invisible_Guardian',
   'https://www.imdb.com/title/tt4924942/',
   'https://en.wikipedia.org/wiki/The_Invisible_Guardian,']},
 {'topic': 'Politics',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/David_Sweet',
   'https://en.wikipedia.org/wiki/David_Sweet',
   'https://dbpedia.org/page/David_Sweet',
   'https://xxi.pages.dev/0xLy9lbi53aWtpcGVkaWEub3JnLy9EYXZpZF9Td2VldA']},
 {'topic': 'Politics',
  'answer_type': 'Place',
  'urls': ['https://en.wikipedia.org/wiki/Linda_Lingle',
   'https://en.wikipedia.org/wiki/Linda_Lingle',
   'https://jwa.org/encyclopedia/article/lingle-linda#pid-1115',
   'https://ballotpedia.org/Linda_Lingle']},
 {'topic': 'Politics',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Pakistan_Business_Council#Former_chief_executives',
   'https://www.dawn.com/news/1489714',
   'https://www.app.com.pk/national/pak-china-business-council-to-be-formed-to-promote-private-sector-khusro/']},
 {'topic': 'Other',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/Bernard_Comrie',
   'https://en.wikipedia.org/wiki/Bernard_Comrie',
   'https://alchetron.com/Bernard-Comrie']},
 {'topic': 'Sports',
  'answer_type': 'Person',
  'urls': ['https://olympics.com/en/olympic-games/beijing-2022/results/figure-skating/ice-dance',
   'https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Ice_dance#Overall',
   'https://olympics.com/en/olympic-games/beijing-2022/results/figure-skating/ice-dance']},
 {'topic': 'Music',
  'answer_type': 'Place',
  'urls': ['https://www.thejc.com/news/israel/duran-duran-to-perform-in-israel-de4dp28b',
   'https://en.wikipedia.org/wiki/Kibbutz_volunteer',
   'https://en.wikipedia.org/wiki/Gvulot',
   'https://www.grunge.com/1088796/simon-le-bon-facts-about-the-duran-duran-frontman/']},
 {'topic': 'Other',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/List_of_Ig_Nobel_Prize_winners',
   'https://en.wikipedia.org/wiki/List_of_Ig_Nobel_Prize_winners',
   'https://improbable.com/ig/winners/',
   'https://web.mit.edu/voodoo/www/recent_issues/is743/ignoble.html']},
 {'topic': 'TV shows',
  'answer_type': 'Other',
  'urls': ['https://en.wikipedia.org/wiki/List_of_The_Young_and_the_Restless_characters_(2000s)#Sabrina_Costelana_Newman',
   'https://theyoungandtherestless.fandom.com/wiki/David_Chow',
   'https://www.soapcentral.com/young-and-restless/whoswho/david.php',
   'https://soaps.sheknows.com/the-young-and-the-restless/characters/david-chow/']},
 {'topic': 'TV shows',
  'answer_type': 'Other',
  'urls': ['https://archer.fandom.com/wiki/Placebo_Effect',
   'https://archer.fandom.com/wiki/Placebo_Effect',
   'https://www.vulture.com/article/best-archer-episodes.html',
   'https://www.avclub.com/archers-pampage-coasts-to-a-surprisingly-boring-stop-1847685085']},
 {'topic': 'Art',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Mohammed_Racim',
   'https://en.wikipedia.org/wiki/Mohammed_Racim',
   'https://www.algeria.com/blog/talented-algerian-artist-mohammed-racim/',
   'https://www.thenationalnews.com/arts-culture/art/who-is-mohammed-racim-google-doodle-pays-tribute-to-algerian-artist-1.1247864']},
 {'topic': 'Art',
  'answer_type': 'Number',
  'urls': ['https://societyillustrators.org/about/history-of-the-society/',
   'https://societyillustrators.org/about/history-of-the-society/#:~:text=In%201959%2C%20members%20Bob%20Peak,first%20Illustrators%20Annual%20book%20followed.',
   'https://www.nyc-arts.org/organizations/museum-of-american-illustration/']},
 {'topic': 'Politics',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/E._A._Nisbet',
   'https://en.wikipedia.org/wiki/E._A._Nisbet',
   'https://www.georgiaencyclopedia.org/articles/history-archaeology/eugenius-a-nisbet-1803-1871/#:~:text=In%201827%20he%20was%20elected,of%20a%20state%20supreme%20court.',
   'https://www.findagrave.com/memorial/7116581/eugenius-aristides-nisbet']},
 {'topic': 'Politics',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Ibrahim_Rugova',
   'https://www.rferl.org/a/1340954.html',
   'https://en.wikipedia.org/wiki/Ibrahim_Rugova#:~:text=On%205%20September%202005%2C%20he,from%20the%20post%20of%20president.',
   'https://www.rferl.org/a/1061163.html',
   'https://www.rte.ie/news/2006/0121/72100-kosovo/']},
 {'topic': 'Other',
  'answer_type': 'Place',
  'urls': ['https://en.wikipedia.org/wiki/Honda_Battle_of_the_Bands',
   'https://en.wikipedia.org/wiki/Honda_Battle_of_the_Bands',
   'https://www.alasu.edu/_migration-2023-08-17-23/news/asu-host-2023-hbotb.php',
   'https://www.prnewswire.com/news-releases/six-hbcu-marching-bands-selected-to-perform-in-2023-honda-battle-of-the-bands-301689873.html']},
 {'topic': 'Music',
  'answer_type': 'Person',
  'urls': ['https://en.wikipedia.org/wiki/The_American_Album_of_Familiar_Music',
   'https://en.wikipedia.org/wiki/The_American_Album_of_Familiar_Music#',
   'https://www.onesmedia.com/music-c-10_65/american-album-of-familiar-music-p-958.html',
   'https://otrworld.com/products/american-album-of-familiar-music-old-time-radio-shows-otrs-mp3-cd-23-episodes']},
 {'topic': 'Art',
  'answer_type': 'Date',
  'urls': ['https://www.metmuseum.org/research-centers/leonard-a-lauder-research-center/research-resources/modern-art-index-project/cone',
   'https://www.metmuseum.org/research-centers/leonard-a-lauder-research-center/research-resources/modern-art-index-project/cone',
   'https://jwa.org/encyclopedia/article/cone-etta']},
 {'topic': 'Other',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Vladislav_Kaborda',
   'https://en.wikipedia.org/wiki/Vladislav_Kaborda',
   'https://www.transfermarkt.co.uk/kaborda/nationalmannschaft/spieler/255750',
   'https://us.soccerway.com/players/vladislav-kabord/210936/']},
 {'topic': 'Music',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/American_Classical_Music_Hall_of_Fame_and_Museum#2005',
   'https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_John_Williams',
   'https://en.wikipedia.org/wiki/American_Classical_Music_Hall_of_Fame_and_Museum',
   'https://classicalwalkoffame.org/browse-inductees/?show_group=year']},
 {'topic': 'Politics',
  'answer_type': 'Date',
  'urls': ['https://wikiroulette.co/?p=1985_St._Louis_mayoral_election',
   'https://en.wikipedia.org/wiki/1985_St._Louis_mayoral_election']},
 {'topic': 'History',
  'answer_type': 'Number',
  'urls': ['https://en.wikipedia.org/wiki/Infanterikanonvagn_72',
   'https://en.wikipedia.org/wiki/Infanterikanonvagn_72',
   'https://premium.globalsecurity.org/military/world/europe/ikv-72.htm']},
 {'topic': 'Geography',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Askham_Richard',
   'https://her-staging.york.gov.uk/api/LibraryLinkWebServiceProxy/FetchResource/135950/full_135950.pdf',
   'https://en.wikipedia.org/wiki/Askham_Richard',
   'http://askhamrichard-pc.org.uk/local-info.php?id=6']},
 {'topic': 'Geography',
  'answer_type': 'Place',
  'urls': ['https://worldpopulationreview.com/countries/malawi/location',
   'https://worldpopulationreview.com/countries/malawi/location',
   'https://latitude.to/map/mw/malawi']},
 {'topic': 'Science and technology',
  'answer_type': 'Date',
  'urls': ['https://en.wikipedia.org/wiki/Hubble_Space_Telescope',
   'https://en.wikipedia.org/wiki/Hubble_Space_Telescope',
   'https://www.nasa.gov/missions/hubble/hubbles-wide-field-camera-3-recovered-collecting-science-data/']},
 {'topic': 'Geography',
  'answer_type': 'Place',
  'urls': ['https://en.wikipedia.org/wiki/Gusevsky_District',
   'https://en.wikipedia.org/wiki/Gusevsky_District#:~:text=As%20a%20municipal%20division%2C%20the,settlement%20and%20four%20rural%20settlements.',
   'https://soft.lk/key/Gusev,_Kaliningrad_Oblast',
   'https://en.wikipedia.org/wiki/Gusevskoye_Urban_Settlement']},

In [6]:
topics_set = set()
topics_number = {}
questions_by_topic = {}
answers_by_topic = {}
for i in range(len(metadata_list)):
    topics_set.add(metadata_list[i]["topic"])
    topics_number[metadata_list[i]["topic"]] = topics_number.get(metadata_list[i]["topic"], 0) + 1
    data_row = data.iloc[i]
    question = data_row["question"]
    answer = data_row["answer"]
    if metadata_list[i]["topic"] not in questions_by_topic:
        questions_by_topic[metadata_list[i]["topic"]] = []
    questions_by_topic[metadata_list[i]["topic"]].append(question)
    if metadata_list[i]["topic"] not in answers_by_topic:
        answers_by_topic[metadata_list[i]["topic"]] = []
    answers_by_topic[metadata_list[i]["topic"]].append(answer)



print(topics_number)
print(questions_by_topic)
print(answers_by_topic)

{'Science and technology': 858, 'Geography': 424, 'Sports': 368, 'Art': 550, 'Politics': 709, 'Other': 475, 'TV shows': 293, 'Music': 341, 'History': 173, 'Video games': 135}

In [8]:
art=list(questions_by_topic["Art"])
len(art)
art_mapper=pd.DataFrame({"question": art})
art_mapper.to_csv("q_art.csv", index=False)

In [9]:
s=list(questions_by_topic["Science and technology"])
len(s)
s_mapper=pd.DataFrame({"question": s})
s_mapper.to_csv("q_science_and_technology.csv", index=False)

In [10]:
geo=list(questions_by_topic["Geography"])
len(geo)
geo_mapper=pd.DataFrame({"question": geo})
geo_mapper.to_csv("q_geography.csv", index=False)

In [15]:
h,m,l,ll,cu=0,0,0,0,0
h_list,m_list,l_list,ll_list,cu_list=[],[],[],[],[]
su_data=good_set.copy()
for r in range(len(si_tech)):
    for i in range(len(su_data)):
        if si_tech[r] == su_data["question"][i]:
            if su_data["confidences"][i] > 0.8:
                h += 1  
                h_list.append(su_data.iloc[i])
            elif su_data["confidences"][i] > 0.6:
                m += 1
                m_list.append(su_data.iloc[i])
            elif su_data["confidences"][i] > 0.4:
                l += 1
                l_list.append(su_data.iloc[i])

            elif su_data["confidences"][i] > 0.2:
                ll += 1
                ll_list.append(su_data.iloc[i])

            else:
                cu += 1
                cu_list.append(su_data.iloc[i])

            continue
        
print(f"High Confidence: {h} ({(h)/len(su_data)*100:.2f}%)")
print(f"Moderate Confidence: {m} ({(m)/len(su_data)*100:.2f}%)")
print(f"Low Confidence: {l} ({(l)/len(su_data)*100:.2f}%)")
print(f"Lowest Confidence: {ll} ({(ll)/len(su_data)*100:.2f}%)")
print(f"Completely Uncertain: {cu} ({(cu)/len(su_data)*100:.2f}%)")

NameError: name 'good_set' is not defined

In [16]:
mapper = pd.read_csv(r"200_q_gemma-3-4b-it.csv", encoding='utf-8')
mapper_topics_numbers = {}
q_by_topic = {topic: [] for topic in questions_by_topic.keys()}
for r in range(200):
    mapper_question = mapper["question"][r]
    for topic, questions in questions_by_topic.items():
        if mapper_question in questions:
            q_by_topic[topic].append(mapper_question)
            mapper_topics_numbers[topic] = mapper_topics_numbers.get(topic, 0) + 1
            break
    
mapper_topics_numbers

FileNotFoundError: [Errno 2] No such file or directory: '200_q_gemma-3-4b-it.csv'

In [89]:
old=[]
new=[]

In [ ]:
in_mapper = False
for q in h_list:
    if q["question"] in mapper["question"].values:
        in_mapper = True
        old.append(q)
    else:
        in_mapper = False
        new.append(q)
        
    print(in_mapper, q["question"], q["confidences"])

False What is the exact date when the first CRISPR-edited babies were reportedly born, according to a 2019 *Nature* article? 1.0
False In which month and year did Dolly the sheep give birth to her first lamb, Bonnie? 1.0
True Kiyoshi Oka entered the Imperial University of Kyoto in 1922 to study what subject? 1.0
False What is the boiling point of the element dysprosium in Fahrenheit? 1.0
True Which year was the drug Metformin introduced as a medication in France? 1.0
False On what day, month, and year was the first unplanned flight of the General Dynamics F-16 Fighting Falcon? 1.0
True What type of eclipse occurred on August 28, 1802, at 51.3°N, 105.7°E? 1.0
True What is the specified maximum speed in kilometers per hour of the Grumman F4F-3 Wildcat (1937) plane? 0.9
False Marcia Bartusiak traces the term "black hole" to which physicist (first name, middle initial, and surname), who reportedly compared the phenomenon in the early 1960s to the Black Hole of Calcutta, a notorious prison where people entered but never left alive? 1.0
False What were the month and year when scientists reported that bacteria from Earth, particularly Deinococcus radiodurans bacteria, which is highly resistant to environmental hazards, were found to survive for three years in outer space? 1.0
False What day did India land its first spacecraft on the moon? 1.0
False What was the original scientific name given to *Calytrix acutifolia* by John Lindley in 1839? 1.0
False What year was "Discussion sur l’évolution de l’univers" by Georges Lemaitre published? 1.0
False What was the budget request, in billion US dollars, made by NASA in 2018? 1.0
False What year was Türksat 2A decommissioned? 1.0
False In what year did William Randolph Taylor receive the Gilbert Morgan Smith Medal? 1.0
False What is the peak brightness of the Asus ROG Phone 5s Pro in nits? 0.9
False What is the resolution of the Cat B15 Q in pixels? 1.0
False Le Chatelier's thermoelectric pyrometer, as discussed in the 1900 report "Clays of New York, Their Properties and Uses," was considered accurate within how many degrees Fahrenheit? 1.0
False The Italian-made OTO-Melara Mod 56 pack howitzer had a barrel length of what in meters? 0.9
False Who drew a map of 64 stars of the Pleiades from his observations in 1779 and then published it in 1786? 1.0
False In what year did Eilenberg, in a joint paper with Chevalley, give an algebraic approach to the cohomology of Lie groups using the Lie algebra as the basic object? 1.0
False On what month, day, and year did NASA announce the selection of its eighth group of astronaut candidates, which included the first women (six mission specialists)? 1.0
False On what day, month, and year did Max Wolf discover his first asteroid, 323 Brucia? 0.9
False What's the first NT version of Windows that wasn't branded as NT? 1.0
True How many spin-offs of the journal "Circulation" did the American Heart Association launch in 2008? 0.9
False Which country is the species Acanthops bidens native to? 0.9
False Which female chemist was awarded the Garvan–Olin Medal in 1952? 0.9
False In what year was the minor planet 3586 Vasnetsov discovered? 1.0
False What neologism, which gained widespread use in the 21st century, identifies the date on which the day and night are exactly the same? 0.9
False What is the surname of the individual who won the Linus Pauling Award in 1969? 0.9
False In which year did Maryam Mirzakhani (an Iranian mathematician) become a professor at Stanford University? 1.0
False In what year was the beetle species Conalia helva described? 0.9
False What was the date, month, and year when "Selective Availability" was discontinued as a result of the 1996 executive order, allowing civilian users to receive a non-degraded signal globally? 1.0
False What is the chemical name of the drug previously known to treat bacterial infections that Dr. William Schwartz discovered also acts as a diuretic in people with congestive heart failure? 1.0
False Which year was the actinide concept proposed? 1.0
False What year was Mary Engle Pennington inducted into the National Inventors Hall of Fame? 0.9
False What was the name of Claudio Bunster Weitzman, the Chilean theoretical physicist, until 2005? 1.0
False In which month and year did Apple add the ability for users to speak "Hey Siri" to enable the assistant without the requirement of physically handling the device? 1.0
False What was the year when the Express Tribune (newspaper) reported, "The Aga Khan University Hospital has become the first medical center to introduce the new advanced brain surgery technology, Neuro-Robotic Exoscope, in Pakistan"? 1.0
False What were the day, month, and year when the first unassisted off-Earth Twitter message was posted from the International Space Station by a NASA astronaut? 0.9
True What is the height of the Space Shuttle Atlantis in meters? 1.0
False What month and year did Canon launch the EOS R50? 0.9
True What month and year was the first public demonstration of televised silhouette images in motion? 1.0
False In what year did Mullvad begin supporting connections via the OpenVPN protocol? 1.0
False Which female biochemist received the Francis P. Garvan–John M. Olin Medal in 1946? 0.9
False What year did the chemist Pauline Gracia Beery Mack publish her work "Colorfastness of Women's and Children's Wearing-Apparel Fabrics"? 1.0
False What is the full name of the mathematician who started the publication "Mathematica Japonicae" using his own funds in 1948? 0.9

In [91]:
in_mapper = False
for q in m_list:
    if q["question"] in mapper["question"].values:
        in_mapper = True
        old.append(q)
    else:
        in_mapper = False
        new.append(q)
    print(in_mapper, q["question"], q["confidences"])

False At which university was the mechanical engineer Gang Chen an assistant professor from 1993 to 1997? 0.8
True In which two fields of study did computer scientist Nancy Amato receive two bachelor's degrees from Stanford University in 1986? 0.8
False At what zoo did August Scherl demonstrate his gyro-monorail to the public? 0.7
False What is the name of Jupiter’s third-largest moon? 0.7
True Who was awarded the Rumelhart Prize in 2011? 0.8
False Name the mission director of the Rohini Satellite 1 (RS-1) satellite launch in 1980. 0.7
True In what year did Peter Norvig and Stuart Russell win the AAAI/EAAI Outstanding Educator Award? 0.8
False On what month, day, and year did Google run its first live-action video doodle? 0.8
False What month and year did the Large Hadron Collider reopen after it closed for maintenance and further upgrades at the end of 2018? 0.7
False In the 2012 research paper titled "Multiplication of EEG Samples through Replicating, Biasing, and Overlapping" by Adham Atyabi et al., between what frequencies was the EEG dataset bandpass filtered, in hertz (Hz)? 0.7
True In which year did Edward Meyrick first describe Cydalima mysteris? 0.7
False In what year did the biochemist Mildred Cohn receive the Golden Plate Award from the American Academy of Achievement? 0.8
False In which year did Hossein Baharvand, an Iranian stem cell and developmental biologist, receive the Mustafa Prize? 0.7
False What was the age range of the drivers whose EEG data was collected in the 2021 research paper titled "EEG-Based Driving Fatigue Detection Using a Two-Level Learning Hierarchy Radial Basis Function" by Ziwu Ren et al.? 0.7
False In what month and year did Wangchuk start a project called the Ice Stupa? 0.8
False The Partial Solar Eclipse of January 1, 1805 was a part of which Saros series? 0.8
True In which year were the two novel RNA viruses, distantly related to pestiviruses and coltiviruses, detected in the genomes of dead Manis javanica and Manis pentadactyla? 0.7
True What is the name of the individual who was awarded the Paul Karrer Gold Medal in 2004? 0.8
False What camera has the world's first dual-driven shutter system? 0.7
True The first brief description of Agrilus planipennis was published by Léon Fairmaire in which French journal in 1888? 0.7
False What was the year when it was announced that Chrome would be completely revamped using Google's Material You design language? 0.8
True In Hz, what was the sampling rate used for recording EEG signals from the six participants in the 2021 research paper titled "EEG-Based Driving Fatigue Detection Using a Two-Level Learning Hierarchy Radial Basis Function" by Ziwu Ren et al.? 0.7
True In what year did the aerospace scientist Hans Wolfgang Liepmann receive the Ludwig-Prandtl-Ring Award? 0.8

In [92]:
in_mapper = False
for q in l_list:
    if q["question"] in mapper["question"].values:
        in_mapper = True
        old.append(q)
    else:
        in_mapper = False
        new.append(q)
    print(in_mapper, q["question"], q["confidences"])

False In which year did the Japanese scientist Koichi Mizushima receive the Kato Memorial Prize? 0.6
False Who won the Gerard P. Kuiper Prize in 2001? 0.5
False Who was the first female chemist to receive the Francis P. Garvan-John M. Olin Medal? 0.5
False In what year was Professor Ascher Herman Shapiro awarded the Benjamin Garver Lamme Award by the American Society for Engineering Education? 0.6
False What is the surname of the individual who won the Faraday Lectureship Prize, previously known simply as the Faraday Lectureship, in 1914? 0.5
False What language is represented in Figure 4 of the paper "Identifying Semantic Role Clusters and Alignment Types via Microrole Coexpression Tendencies"? 0.6
False Which scientist received the American Chemical Society Award in Pure Chemistry in 1933? 0.5
False What is the molar heat capacity of selenium at STP in joules per kelvin per mole? 0.6
False Who won the Eddington Medal in 1993? 0.5
False What was the Word of the Decade (2000–2009) according to the American Dialect Society? 0.5
True Which digits of the forefeet are vestigial and tiny on the Isoodon obesulus? 0.6
False What was the total number of locations surveyed in all oceans for the study published in 2014 called "Plastic Pollution in the World's Oceans: More than 5 Trillion Plastic Pieces Weighing Over 250,000 Tons Afloat at Sea" by Marcus Eriksen, Laurent C. M. Lebreton, Henry S. Carson, Martin Thiel, Charles J. Moore, Jose C. Borerro, Francois Galgani, Peter G. Ryan, and Julia Reisser? 0.6
True Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2003? 0.6
True What part of the body do the eggs of moon jellies lodge in? 0.5
False What was the statement famously made by Thomas Edison during the first public demonstration of the incandescent light bulb at Menlo Park regarding the eventual cost of electricity? 0.5
False What was the name of the Yale Bright Star Catalogue's direct predecessor, published in 1908? 0.6
False How heavy is my Ricoh GR III body only in grams? 0.5
False What was the first name of the Irish-born computer programmer Kathleen Rita McNulty Mauchly Antonelli's father? 0.5
False Who won the Kalinga Prize for the Popularization of Science in 1969? 0.6
False In which year was the Kangri cancer effect first studied? 0.5
False How many total lunar eclipses occurred on Earth in the year 1967? 0.6
True What were the month and year when the WhatsApp file upload limit was raised from 100 MB to 2 GB, and the maximum group size increased to 512 members? 0.5
False From which university did computer scientist Jeanne Clare Adams receive her B.S. degree in Economics in 1943? 0.5
True What is the name of the project that won the 2008 ACM Software System Award? 0.6
False Which genus was the ruby-throated bulbul moved to from *Turdus* before finally being classified in the genus *Rubigula*? 0.6
False In what year did Otton Nikodym show how to produce a subset 𝑁 of the unit square with area(𝑁) = 1 such that for each point 𝑥 ∈ 𝑁 there is a line intersecting 𝑁 in the single point 𝑥? 0.5
True In which month and year did KTH's R1 reactor achieve criticality? 0.6
False Name the mission director of the Rohini Technology Payload (RTP) satellite launch in 1979. 0.6
True On which day, month, and year was the RS-1 satellite launched from the Satish Dhawan Space Centre in India? 0.6
True What is the wheelbase of the Honda CL125 in millimeters? 0.5
False What was the name of the observatory in which 259 Aletheia was discovered in 1886? 0.5
True What is the surname of the individual who won the Robert Boyle Prize for Analytical Science, formerly called the Boyle Medal, in 2012? 0.5
True Who was awarded The Oceanography Society's Jerlov Award in 2008? 0.5
False The Wandanlage stereo system was originally released in which year? 0.5
True At which university did Jurgen Aschoff study medicine? 0.6
False What was the title of the engineer and scientist Ahmet Cemal Eringen's Ph.D. dissertation? 0.5
False What was the magnitude of the solar eclipse that occurred on June 21, 2001? 0.5

In [93]:
in_mapper = False
for q in ll_list:
    if q["question"] in mapper["question"].values:
        in_mapper = True
        old.append(q)
    else:
        in_mapper = False
        new.append(q)
    print(in_mapper, q["question"], q["confidences"])

False On which day, month, and year did the Hubble Telescope enter a partial safe mode following suspected hardware problems in its most advanced instrument, the Wide Field Camera 3 instrument? 0.3
False What were Martin Haspelmath's and Michael Cysouw's respective affiliations when they authored "Identifying Semantic Role Clusters and Alignment Types via Microrole Coexpression Tendencies"? 0.4
True Who was the director of the Lebedev Physical Institute of the Russian Academy of Sciences between 1951 and 1972? 0.4
False What is the surname of the individual who won the Gordon E. Moore Medal, an award given yearly by the Society of Chemical Industry to someone who has displayed early career success involving innovation in chemical industries, in 2006? 0.3
False Who won the American Mathematical Society David P. Robbins Prize in 2010? 0.3
True What were the day, month, and year when Britannica released a Google Chrome extension, "Britannica Insights," which shows snippets of information from Britannica Online whenever the user performs a Google search, in a box to the right of Google's results? 0.3
True In what month and year did Jacques Frédéric Français publish a work in which he gave a geometric representation of complex numbers with interesting applications? 0.3
False How many drivers participated in the overnight study in the research paper titled "Detecting Driver Mental Fatigue Based on EEG Alpha Power Changes During Simulated Driving" by Faramarz Gharagozlou et al.? 0.3
False Give me the DOI of the paper "New avenues and challenges in semantic map research." 0.3
False In what year did computer scientist Dana Angluin join the faculty at Yale University? 0.3
False Who received the Farrer Medal in 2014? 0.3
True What are the four keywords of the paper "New Avenues and Challenges in Semantic Map Research"? 0.4
False As of March 2016, how many companies and institutions were developing vaccines against Zika, and how long did they state a vaccine is unlikely to be widely available? 0.4
False In which year was *Racosperma drummondii* transferred back to the genus *Acacia*? 0.3
False In which month and year did Apollo 14 pilot Edgar Mitchell and Apollo 17 geologist Harrison Schmitt, among other noted Mars exploration advocates, publish an anthology of Mars-to-Stay architectures titled "A One Way Mission to Mars: Colonizing the Red Planet"? 0.3
False Who won the Paris Kanellakis Theory and Practice Award in 2000? 0.3
False In which year did Augustus Radcliffe Grote describe Lithophane viridipallens? 0.3
False What year did Michael John Creutz join the High Energy Theory Group at Brookhaven National Laboratory? 0.4
False Which amateur astronomer was 162 Laurentia named after? 0.4
False In what year was the praying mantis species Eremiaphila bifasciata described by Chopard? 0.3
True In which month and year was Service Pack 3 for Windows Fundamentals for Legacy PCs released? 0.3
False What is the wingspan of Eugnosta misella in millimeters? 0.4
False Which Google Sheets function is specifically designed to convert a Unix epoch timestamp to a regular datetime in the UTC timezone? 0.3
False Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2018? 0.4
False The superfamily Nematocarcinoidea is part of what infraorder? 0.4
False In what year did Tom Limoncelli and Christine Hogan win the LISA Outstanding Achievement Award from USENIX? 0.4
False Who was the Argentine-English-American mathematician and biochemist famous for her use of mathematical techniques to deduce protein structure? 0.3
False What were the day, month, and year when Meta services suffered their worst outage since 2008, bringing down Instagram, Facebook, and WhatsApp? 0.3
True In which month and year did 175 crews serve rotations at the Mars Desert Research Station over a period of sixteen years? 0.4
True What is the ChemSpider ID of diazepam? 0.3
False In what year did the biochemist Mildred Cohn publish her work titled "A Study of Oxidative Phosphorylation with O-18 Labeled Inorganic Phosphate"? 0.4
False Who was awarded the Darwin Medal in 1952? 0.3
False Who wrote the paper 'Multidimensional Scaling and Other Techniques for Uncovering Universals'? 0.4
False Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2019? 0.4
True What were the month and year when Telegram reached 180 million monthly active users? 0.3
False What is the surname of the individual who won the Beilby Medal and Prize in 2009? 0.3
False In what year was Niels Erik Norlund awarded a Gold Medal for an essay on continued fractions? 0.4
False The K-class blimp (1938), the K-14, had a total diameter of what in meters? 0.3
True What were the day, month, and year when Google released a version of Chrome on Windows that added hardware-accelerated H.264 video decoding? 0.3
False Who was awarded the 2020 Euler Medal by the Institute of Combinatorics and Its Applications? 0.4
False Which ward in Tokyo was the AT-1 phono cartridge created in? 0.4
False What was the rate of climb of the Grumman F4F-3 Wildcat (1937) in meters per second? 0.4
False Name the enzyme with an enzyme commission number of 4.1.1.65. 0.4
False In the 1900 report "Clays of New York, Their Properties and Uses," in the Mineralogy of Clays section, it discusses the experiments of Vogt, which show that kaolinite is not the only substance that remains in suspension for a long time. Tests include potash mica, orthoclase from Norway, and what other mineral from what location? 0.3
False What is the apparent visual magnitude of Gliese 146? 0.3
False Who was the recipient of the John Tuzo Wilson Medal in 2000? 0.3
True In which volume and issue of the journal Linguistics was the paper "Articulatory constraints on stop insertion and elision in consonant clusters" originally published? 0.4
True What is the name of the academic editor of the 2021 research paper titled "Classification of Relaxation and Concentration Mental States with EEG" by Shingchern D. You? 0.3
False In which year did Aaron Leo Brody, an American food scientist, first earn his Ph.D.? 0.4

In [94]:
in_mapper = False
for q in cu_list:
    if q["question"] in mapper["question"].values:
        in_mapper = True
        old.append(q)
    else:
        in_mapper = False
        new.append(q)
    print(in_mapper, q["question"], q["confidences"])

False Who received the IEEE Frank Rosenblatt Award in 2010? 0.1
False Who was awarded the Oceanography Society's Jerlov Award in 2018? 0.1
False What are the first and last names of the scientist who collaborated with Vincent Joseph Schaefer to issue the U.S. patent for "Method and Apparatus for Producing Aerosols" in 1943? 0.1
False Which two scientists (first and last names) are credited with first isolating *Azotobacter salinestris* from saline soils? 0.1
False What day, month, and year was Notepad++ version 7.8.8 released? 0.1
False What is the ChemSpider ID of Axitinib, a small molecule tyrosine kinase inhibitor developed by Pfizer? 0.1
False In the 2022 research paper titled "Analyzing EEG Data with Machine and Deep Learning: A Benchmark" by Danilo Avola et al., what are the four machine learning models that were used? 0.2
False What was the name of the minor planet discovered by the Soviet astronomer in the name of Pyotr Kapitsa in 1982? 0.2
False On which day, month, and year did the Bell UH-1H Iroquois helicopter have its first flight? 0.2
True Which scientist received the Roebling Medal the year after Max Hutchinson Hey received his? 0.1
False In which city was the first International Association for Engineering Geology and the Environment congress held? 0.2
False New Yorker Edward A. Tuttle's patent application was granted on October 11, 1881, for what kind of machine? 0.2
True Who published the first scientific description of the Asiatic lion in 1826? 0.2
False What is the name of the entomologist who described the species Acanthops bidens in 1922? 0.2
False Who won the Godman-Salvin Medal in 2010? 0.2
False What were the month and year when Google's software engineer Gary Kačmarčík wrote that ChromeOS would access remote applications through a technology unofficially called "Chromoting"? 0.2
False Who did Alfred Georg Hubertus Fischer write the paper "Orbital Forcing and Sedimentary Sequences" with? 0.2
False Which engineer received the Worcester Reed Warner Medal in 1951? 0.2
False What are the names of the two mathematicians who received the Salem Prize in 1988? 0.2
True Who was the inaugural winner of the Riemann Prize in 2019? 0.2
False What was the title of chemist Mary Letitia Caldwell's Ph.D. thesis? 0.2
False Who won the Heinz Hopf Prize in 2019? 0.1
False What is the surname of the individual who won the Polanyi Medal for outstanding contributions to the field of gas kinetics in 1982? 0.2
False What is the surname of the individual who won the Victor A. Prather Award in 1968? 0.2
False Who won the Margaret Oakley Dayhoff Award in 2003? 0.1
False What advanced reservoir simulation technology did Aramco unveil in 2010? 0.2
False On which day, month, and year was the domain "indianexpress.com" registered? 0.2
False Who was the recipient of the Leslie Fox Prize for Numerical Analysis in 2017? 0.2
False Which scientist received the William Henry Twenhofel Medal in 1978? 0.2
True Which scientists received the American Chemical Society Award in Pure Chemistry in 1937? 0.1
False In what year was the beetle species Conaliamorpha lutea described by Ermisch? 0.2
False What's the month, day, and year of the online publication of the paper "Articulatory constraints on stop insertion and elision in consonant clusters"? 0.2
False What is the surname of the individual who won the Gibson-Fawcett Award in 2018? 0.2
True Who won the Margaret Oakley Dayhoff Award in 2011? 0.2
False What year did Heisuke Hironaka establish a philanthropic foundation called the Japan Association for Mathematical Sciences? 0.2
False What was the model number of the first Betamax VCR in the US? 0.2
True What is the first name and surname of the food scientist who received the first IFT Industrial Scientist Award in 1994? 0.1
False Who won the 1997 IJCAI Award for Research Excellence? 0.2
False What is the name of the astronomer who discovered 216433 Milianleo in 2009? 0.2
False On what month, day, and year did Google release the first Google Doodle that used artificial intelligence to make music? 0.2

In [95]:
print(len(old), len(new))

44 153

In [180]:
c=0
for q in old:
    c+=1
    if c%10==0:
        print(f"Processed {c} questions...")
    print(q["question"], q["confidences"]) # h = 7 (33),m = 9 (31),l = 11 (29),ll = 11 (29), cu = 6 (34)

Kiyoshi Oka entered the Imperial University of Kyoto in 1922 to study what subject? 1.0
Which year was the drug Metformin introduced as a medication in France? 1.0
What type of eclipse occurred on August 28, 1802, at 51.3°N, 105.7°E? 1.0
What is the specified maximum speed in kilometers per hour of the Grumman F4F-3 Wildcat (1937) plane? 0.9
How many spin-offs of the journal "Circulation" did the American Heart Association launch in 2008? 0.9
What is the height of the Space Shuttle Atlantis in meters? 1.0
What month and year was the first public demonstration of televised silhouette images in motion? 1.0
In which two fields of study did computer scientist Nancy Amato receive two bachelor's degrees from Stanford University in 1986? 0.8
Who was awarded the Rumelhart Prize in 2011? 0.8
Processed 10 questions...
In what year did Peter Norvig and Stuart Russell win the AAAI/EAAI Outstanding Educator Award? 0.8
In which year did Edward Meyrick first describe Cydalima mysteris? 0.7
In which year were the two novel RNA viruses, distantly related to pestiviruses and coltiviruses, detected in the genomes of dead Manis javanica and Manis pentadactyla? 0.7
What is the name of the individual who was awarded the Paul Karrer Gold Medal in 2004? 0.8
The first brief description of Agrilus planipennis was published by Léon Fairmaire in which French journal in 1888? 0.7
In Hz, what was the sampling rate used for recording EEG signals from the six participants in the 2021 research paper titled "EEG-Based Driving Fatigue Detection Using a Two-Level Learning Hierarchy Radial Basis Function" by Ziwu Ren et al.? 0.7
In what year did the aerospace scientist Hans Wolfgang Liepmann receive the Ludwig-Prandtl-Ring Award? 0.8
Which digits of the forefeet are vestigial and tiny on the Isoodon obesulus? 0.6
Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2003? 0.6
What part of the body do the eggs of moon jellies lodge in? 0.5
Processed 20 questions...
What were the month and year when the WhatsApp file upload limit was raised from 100 MB to 2 GB, and the maximum group size increased to 512 members? 0.5
What is the name of the project that won the 2008 ACM Software System Award? 0.6
In which month and year did KTH's R1 reactor achieve criticality? 0.6
On which day, month, and year was the RS-1 satellite launched from the Satish Dhawan Space Centre in India? 0.6
What is the wheelbase of the Honda CL125 in millimeters? 0.5
What is the surname of the individual who won the Robert Boyle Prize for Analytical Science, formerly called the Boyle Medal, in 2012? 0.5
Who was awarded The Oceanography Society's Jerlov Award in 2008? 0.5
At which university did Jurgen Aschoff study medicine? 0.6
Who was the director of the Lebedev Physical Institute of the Russian Academy of Sciences between 1951 and 1972? 0.4
What were the day, month, and year when Britannica released a Google Chrome extension, "Britannica Insights," which shows snippets of information from Britannica Online whenever the user performs a Google search, in a box to the right of Google's results? 0.3
Processed 30 questions...
In what month and year did Jacques Frédéric Français publish a work in which he gave a geometric representation of complex numbers with interesting applications? 0.3
What are the four keywords of the paper "New Avenues and Challenges in Semantic Map Research"? 0.4
In which month and year was Service Pack 3 for Windows Fundamentals for Legacy PCs released? 0.3
In which month and year did 175 crews serve rotations at the Mars Desert Research Station over a period of sixteen years? 0.4
What is the ChemSpider ID of diazepam? 0.3
What were the month and year when Telegram reached 180 million monthly active users? 0.3
What were the day, month, and year when Google released a version of Chrome on Windows that added hardware-accelerated H.264 video decoding? 0.3
In which volume and issue of the journal Linguistics was the paper "Articulatory constraints on stop insertion and elision in consonant clusters" originally published? 0.4
What is the name of the academic editor of the 2021 research paper titled "Classification of Relaxation and Concentration Mental States with EEG" by Shingchern D. You? 0.3
Which scientist received the Roebling Medal the year after Max Hutchinson Hey received his? 0.1
Processed 40 questions...
Who published the first scientific description of the Asiatic lion in 1826? 0.2
Who was the inaugural winner of the Riemann Prize in 2019? 0.2
Which scientists received the American Chemical Society Award in Pure Chemistry in 1937? 0.1
Who won the Margaret Oakley Dayhoff Award in 2011? 0.2
What is the first name and surname of the food scientist who received the first IFT Industrial Scientist Award in 1994? 0.1

In [98]:
for q in new:
    print(q["question"], q["confidences"]) # h = 7 (33),m = 9 (31),l = 11 (29),ll = 11 (29), cu = 6 (34)

What is the exact date when the first CRISPR-edited babies were reportedly born, according to a 2019 *Nature* article? 1.0
In which month and year did Dolly the sheep give birth to her first lamb, Bonnie? 1.0
What is the boiling point of the element dysprosium in Fahrenheit? 1.0
On what day, month, and year was the first unplanned flight of the General Dynamics F-16 Fighting Falcon? 1.0
Marcia Bartusiak traces the term "black hole" to which physicist (first name, middle initial, and surname), who reportedly compared the phenomenon in the early 1960s to the Black Hole of Calcutta, a notorious prison where people entered but never left alive? 1.0
What were the month and year when scientists reported that bacteria from Earth, particularly Deinococcus radiodurans bacteria, which is highly resistant to environmental hazards, were found to survive for three years in outer space? 1.0
What day did India land its first spacecraft on the moon? 1.0
What was the original scientific name given to *Calytrix acutifolia* by John Lindley in 1839? 1.0
What year was "Discussion sur l’évolution de l’univers" by Georges Lemaitre published? 1.0
What was the budget request, in billion US dollars, made by NASA in 2018? 1.0
What year was Türksat 2A decommissioned? 1.0
In what year did William Randolph Taylor receive the Gilbert Morgan Smith Medal? 1.0
What is the peak brightness of the Asus ROG Phone 5s Pro in nits? 0.9
What is the resolution of the Cat B15 Q in pixels? 1.0
Le Chatelier's thermoelectric pyrometer, as discussed in the 1900 report "Clays of New York, Their Properties and Uses," was considered accurate within how many degrees Fahrenheit? 1.0
The Italian-made OTO-Melara Mod 56 pack howitzer had a barrel length of what in meters? 0.9
Who drew a map of 64 stars of the Pleiades from his observations in 1779 and then published it in 1786? 1.0
In what year did Eilenberg, in a joint paper with Chevalley, give an algebraic approach to the cohomology of Lie groups using the Lie algebra as the basic object? 1.0
On what month, day, and year did NASA announce the selection of its eighth group of astronaut candidates, which included the first women (six mission specialists)? 1.0
On what day, month, and year did Max Wolf discover his first asteroid, 323 Brucia? 0.9
What's the first NT version of Windows that wasn't branded as NT? 1.0
Which country is the species Acanthops bidens native to? 0.9
Which female chemist was awarded the Garvan–Olin Medal in 1952? 0.9
In what year was the minor planet 3586 Vasnetsov discovered? 1.0
What neologism, which gained widespread use in the 21st century, identifies the date on which the day and night are exactly the same? 0.9
What is the surname of the individual who won the Linus Pauling Award in 1969? 0.9
In which year did Maryam Mirzakhani (an Iranian mathematician) become a professor at Stanford University? 1.0
In what year was the beetle species Conalia helva described? 0.9
What was the date, month, and year when "Selective Availability" was discontinued as a result of the 1996 executive order, allowing civilian users to receive a non-degraded signal globally? 1.0
What is the chemical name of the drug previously known to treat bacterial infections that Dr. William Schwartz discovered also acts as a diuretic in people with congestive heart failure? 1.0
Which year was the actinide concept proposed? 1.0
What year was Mary Engle Pennington inducted into the National Inventors Hall of Fame? 0.9
What was the name of Claudio Bunster Weitzman, the Chilean theoretical physicist, until 2005? 1.0
In which month and year did Apple add the ability for users to speak "Hey Siri" to enable the assistant without the requirement of physically handling the device? 1.0
What was the year when the Express Tribune (newspaper) reported, "The Aga Khan University Hospital has become the first medical center to introduce the new advanced brain surgery technology, Neuro-Robotic Exoscope, in Pakistan"? 1.0
What were the day, month, and year when the first unassisted off-Earth Twitter message was posted from the International Space Station by a NASA astronaut? 0.9
What month and year did Canon launch the EOS R50? 0.9
In what year did Mullvad begin supporting connections via the OpenVPN protocol? 1.0
Which female biochemist received the Francis P. Garvan–John M. Olin Medal in 1946? 0.9
What year did the chemist Pauline Gracia Beery Mack publish her work "Colorfastness of Women's and Children's Wearing-Apparel Fabrics"? 1.0
What is the full name of the mathematician who started the publication "Mathematica Japonicae" using his own funds in 1948? 0.9
At which university was the mechanical engineer Gang Chen an assistant professor from 1993 to 1997? 0.8
At what zoo did August Scherl demonstrate his gyro-monorail to the public? 0.7
What is the name of Jupiter’s third-largest moon? 0.7
Name the mission director of the Rohini Satellite 1 (RS-1) satellite launch in 1980. 0.7
On what month, day, and year did Google run its first live-action video doodle? 0.8
What month and year did the Large Hadron Collider reopen after it closed for maintenance and further upgrades at the end of 2018? 0.7
In the 2012 research paper titled "Multiplication of EEG Samples through Replicating, Biasing, and Overlapping" by Adham Atyabi et al., between what frequencies was the EEG dataset bandpass filtered, in hertz (Hz)? 0.7
In what year did the biochemist Mildred Cohn receive the Golden Plate Award from the American Academy of Achievement? 0.8
In which year did Hossein Baharvand, an Iranian stem cell and developmental biologist, receive the Mustafa Prize? 0.7
What was the age range of the drivers whose EEG data was collected in the 2021 research paper titled "EEG-Based Driving Fatigue Detection Using a Two-Level Learning Hierarchy Radial Basis Function" by Ziwu Ren et al.? 0.7
In what month and year did Wangchuk start a project called the Ice Stupa? 0.8
The Partial Solar Eclipse of January 1, 1805 was a part of which Saros series? 0.8
What camera has the world's first dual-driven shutter system? 0.7
What was the year when it was announced that Chrome would be completely revamped using Google's Material You design language? 0.8
In which year did the Japanese scientist Koichi Mizushima receive the Kato Memorial Prize? 0.6
Who won the Gerard P. Kuiper Prize in 2001? 0.5
Who was the first female chemist to receive the Francis P. Garvan-John M. Olin Medal? 0.5
In what year was Professor Ascher Herman Shapiro awarded the Benjamin Garver Lamme Award by the American Society for Engineering Education? 0.6
What is the surname of the individual who won the Faraday Lectureship Prize, previously known simply as the Faraday Lectureship, in 1914? 0.5
What language is represented in Figure 4 of the paper "Identifying Semantic Role Clusters and Alignment Types via Microrole Coexpression Tendencies"? 0.6
Which scientist received the American Chemical Society Award in Pure Chemistry in 1933? 0.5
What is the molar heat capacity of selenium at STP in joules per kelvin per mole? 0.6
Who won the Eddington Medal in 1993? 0.5
What was the Word of the Decade (2000–2009) according to the American Dialect Society? 0.5
What was the total number of locations surveyed in all oceans for the study published in 2014 called "Plastic Pollution in the World's Oceans: More than 5 Trillion Plastic Pieces Weighing Over 250,000 Tons Afloat at Sea" by Marcus Eriksen, Laurent C. M. Lebreton, Henry S. Carson, Martin Thiel, Charles J. Moore, Jose C. Borerro, Francois Galgani, Peter G. Ryan, and Julia Reisser? 0.6
What was the statement famously made by Thomas Edison during the first public demonstration of the incandescent light bulb at Menlo Park regarding the eventual cost of electricity? 0.5
What was the name of the Yale Bright Star Catalogue's direct predecessor, published in 1908? 0.6
How heavy is my Ricoh GR III body only in grams? 0.5
What was the first name of the Irish-born computer programmer Kathleen Rita McNulty Mauchly Antonelli's father? 0.5
Who won the Kalinga Prize for the Popularization of Science in 1969? 0.6
In which year was the Kangri cancer effect first studied? 0.5
How many total lunar eclipses occurred on Earth in the year 1967? 0.6
From which university did computer scientist Jeanne Clare Adams receive her B.S. degree in Economics in 1943? 0.5
Which genus was the ruby-throated bulbul moved to from *Turdus* before finally being classified in the genus *Rubigula*? 0.6
In what year did Otton Nikodym show how to produce a subset 𝑁 of the unit square with area(𝑁) = 1 such that for each point 𝑥 ∈ 𝑁 there is a line intersecting 𝑁 in the single point 𝑥? 0.5
Name the mission director of the Rohini Technology Payload (RTP) satellite launch in 1979. 0.6
What was the name of the observatory in which 259 Aletheia was discovered in 1886? 0.5
The Wandanlage stereo system was originally released in which year? 0.5
What was the title of the engineer and scientist Ahmet Cemal Eringen's Ph.D. dissertation? 0.5
What was the magnitude of the solar eclipse that occurred on June 21, 2001? 0.5
On which day, month, and year did the Hubble Telescope enter a partial safe mode following suspected hardware problems in its most advanced instrument, the Wide Field Camera 3 instrument? 0.3
What were Martin Haspelmath's and Michael Cysouw's respective affiliations when they authored "Identifying Semantic Role Clusters and Alignment Types via Microrole Coexpression Tendencies"? 0.4
What is the surname of the individual who won the Gordon E. Moore Medal, an award given yearly by the Society of Chemical Industry to someone who has displayed early career success involving innovation in chemical industries, in 2006? 0.3
Who won the American Mathematical Society David P. Robbins Prize in 2010? 0.3
How many drivers participated in the overnight study in the research paper titled "Detecting Driver Mental Fatigue Based on EEG Alpha Power Changes During Simulated Driving" by Faramarz Gharagozlou et al.? 0.3
Give me the DOI of the paper "New avenues and challenges in semantic map research." 0.3
In what year did computer scientist Dana Angluin join the faculty at Yale University? 0.3
Who received the Farrer Medal in 2014? 0.3
As of March 2016, how many companies and institutions were developing vaccines against Zika, and how long did they state a vaccine is unlikely to be widely available? 0.4
In which year was *Racosperma drummondii* transferred back to the genus *Acacia*? 0.3
In which month and year did Apollo 14 pilot Edgar Mitchell and Apollo 17 geologist Harrison Schmitt, among other noted Mars exploration advocates, publish an anthology of Mars-to-Stay architectures titled "A One Way Mission to Mars: Colonizing the Red Planet"? 0.3
Who won the Paris Kanellakis Theory and Practice Award in 2000? 0.3
In which year did Augustus Radcliffe Grote describe Lithophane viridipallens? 0.3
What year did Michael John Creutz join the High Energy Theory Group at Brookhaven National Laboratory? 0.4
Which amateur astronomer was 162 Laurentia named after? 0.4
In what year was the praying mantis species Eremiaphila bifasciata described by Chopard? 0.3
What is the wingspan of Eugnosta misella in millimeters? 0.4
Which Google Sheets function is specifically designed to convert a Unix epoch timestamp to a regular datetime in the UTC timezone? 0.3
Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2018? 0.4
The superfamily Nematocarcinoidea is part of what infraorder? 0.4
In what year did Tom Limoncelli and Christine Hogan win the LISA Outstanding Achievement Award from USENIX? 0.4
Who was the Argentine-English-American mathematician and biochemist famous for her use of mathematical techniques to deduce protein structure? 0.3
What were the day, month, and year when Meta services suffered their worst outage since 2008, bringing down Instagram, Facebook, and WhatsApp? 0.3
In what year did the biochemist Mildred Cohn publish her work titled "A Study of Oxidative Phosphorylation with O-18 Labeled Inorganic Phosphate"? 0.4
Who was awarded the Darwin Medal in 1952? 0.3
Who wrote the paper 'Multidimensional Scaling and Other Techniques for Uncovering Universals'? 0.4
Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2019? 0.4
What is the surname of the individual who won the Beilby Medal and Prize in 2009? 0.3
In what year was Niels Erik Norlund awarded a Gold Medal for an essay on continued fractions? 0.4
The K-class blimp (1938), the K-14, had a total diameter of what in meters? 0.3
Who was awarded the 2020 Euler Medal by the Institute of Combinatorics and Its Applications? 0.4
Which ward in Tokyo was the AT-1 phono cartridge created in? 0.4
What was the rate of climb of the Grumman F4F-3 Wildcat (1937) in meters per second? 0.4
Name the enzyme with an enzyme commission number of 4.1.1.65. 0.4
In the 1900 report "Clays of New York, Their Properties and Uses," in the Mineralogy of Clays section, it discusses the experiments of Vogt, which show that kaolinite is not the only substance that remains in suspension for a long time. Tests include potash mica, orthoclase from Norway, and what other mineral from what location? 0.3
What is the apparent visual magnitude of Gliese 146? 0.3
Who was the recipient of the John Tuzo Wilson Medal in 2000? 0.3
In which year did Aaron Leo Brody, an American food scientist, first earn his Ph.D.? 0.4
Who received the IEEE Frank Rosenblatt Award in 2010? 0.1
Who was awarded the Oceanography Society's Jerlov Award in 2018? 0.1
What are the first and last names of the scientist who collaborated with Vincent Joseph Schaefer to issue the U.S. patent for "Method and Apparatus for Producing Aerosols" in 1943? 0.1
Which two scientists (first and last names) are credited with first isolating *Azotobacter salinestris* from saline soils? 0.1
What day, month, and year was Notepad++ version 7.8.8 released? 0.1
What is the ChemSpider ID of Axitinib, a small molecule tyrosine kinase inhibitor developed by Pfizer? 0.1
In the 2022 research paper titled "Analyzing EEG Data with Machine and Deep Learning: A Benchmark" by Danilo Avola et al., what are the four machine learning models that were used? 0.2
What was the name of the minor planet discovered by the Soviet astronomer in the name of Pyotr Kapitsa in 1982? 0.2
On which day, month, and year did the Bell UH-1H Iroquois helicopter have its first flight? 0.2
In which city was the first International Association for Engineering Geology and the Environment congress held? 0.2
New Yorker Edward A. Tuttle's patent application was granted on October 11, 1881, for what kind of machine? 0.2
What is the name of the entomologist who described the species Acanthops bidens in 1922? 0.2
Who won the Godman-Salvin Medal in 2010? 0.2
What were the month and year when Google's software engineer Gary Kačmarčík wrote that ChromeOS would access remote applications through a technology unofficially called "Chromoting"? 0.2
Who did Alfred Georg Hubertus Fischer write the paper "Orbital Forcing and Sedimentary Sequences" with? 0.2
Which engineer received the Worcester Reed Warner Medal in 1951? 0.2
What are the names of the two mathematicians who received the Salem Prize in 1988? 0.2
What was the title of chemist Mary Letitia Caldwell's Ph.D. thesis? 0.2
Who won the Heinz Hopf Prize in 2019? 0.1
What is the surname of the individual who won the Polanyi Medal for outstanding contributions to the field of gas kinetics in 1982? 0.2
What is the surname of the individual who won the Victor A. Prather Award in 1968? 0.2
Who won the Margaret Oakley Dayhoff Award in 2003? 0.1
What advanced reservoir simulation technology did Aramco unveil in 2010? 0.2
On which day, month, and year was the domain "indianexpress.com" registered? 0.2
Who was the recipient of the Leslie Fox Prize for Numerical Analysis in 2017? 0.2
Which scientist received the William Henry Twenhofel Medal in 1978? 0.2
In what year was the beetle species Conaliamorpha lutea described by Ermisch? 0.2
What's the month, day, and year of the online publication of the paper "Articulatory constraints on stop insertion and elision in consonant clusters"? 0.2
What is the surname of the individual who won the Gibson-Fawcett Award in 2018? 0.2
What year did Heisuke Hironaka establish a philanthropic foundation called the Japan Association for Mathematical Sciences? 0.2
What was the model number of the first Betamax VCR in the US? 0.2
Who won the 1997 IJCAI Award for Research Excellence? 0.2
What is the name of the astronomer who discovered 216433 Milianleo in 2009? 0.2
On what month, day, and year did Google release the first Google Doodle that used artificial intelligence to make music? 0.2

In [117]:
new[119] # 48-7 23-9 37-11 49-11  40-6

question         Who received the IEEE Frank Rosenblatt Award i...
response_0       In 2010, Peter J. Smith received the IEEE Fran...
response_1       Robert F. Sproull received the IEEE Frank Rose...
response_2       Dr. Geoffrey Hinton received the IEEE Frank Ro...
response_3       Robert F. Hearn received the IEEE Frank Rosenb...
response_4       Professor Mark S. Horowitz received the IEEE F...
response_5       Dr. Fei-Fei Li received the IEEE Frank Rosenbl...
response_6       Dr. Michael I. Jordan received the IEEE Frank ...
response_7       Professor Barbara Liskov received the IEEE Fra...
response_8       Professor James H. White received the IEEE Fra...
response_9       Professor David Ebert received the IEEE Frank ...
semantic_id_0                                                    0
semantic_id_1                                                    1
semantic_id_2                                                    2
semantic_id_3                                                    3
semantic_id_4                                                    4
semantic_id_5                                                    5
semantic_id_6                                                    6
semantic_id_7                                                    7
semantic_id_8                                                    8
semantic_id_9                                                    9
confidences                                                    0.1
responses        In 2010, Peter J. Smith received the IEEE Fran...
level                        complete uncertainty, reject to reply
Name: 500, dtype: object

In [118]:
additional_qs = []
additional_qs.append(new[:34])
additional_qs.append(new[41:41+14])
additional_qs.append(new[55:55+26])
additional_qs.append(new[81:81+29])
additional_qs.append(new[119:])

In [ ]:
print("h", len(additional_qs[0]), "7") # h = 7 (33),m = 9 (31),l = 11 (29),ll = 11 (29), cu = 6 (34) 
print(additional_qs[0][0]["confidences"])
print(additional_qs[0][-1]["confidences"])
print("m", len(additional_qs[1]), "9" )
print(additional_qs[1][0]["confidences"])
print(additional_qs[1][-1]["confidences"])          
print("l", len(additional_qs[2]), "11" )
print(additional_qs[2][0]["confidences"])
print(additional_qs[2][-1]["confidences"])
print("ll",len(additional_qs[3]), "11" )
print(additional_qs[3][0]["confidences"])
print(additional_qs[3][-1]["confidences"])
print("cu", len(additional_qs[4]), "6" )
print(additional_qs[4][0]["confidences"])
print(additional_qs[4][-1]["confidences"])
# m 17, l 3,

h 34 7
1.0
1.0
m 14 9
0.8
0.8
l 26 11
0.6
0.5
ll 29 11
0.3
0.4
cu 34 6
0.1
0.2

In [167]:
new_q_df = pd.DataFrame(additional_qs[0][:33])
len(new_q_df)

33

In [168]:
temp=pd.DataFrame(additional_qs[1][0:len(additional_qs[1])])
new_q_df = pd.concat([new_q_df, temp], ignore_index=True)
len(new_q_df)

47

In [176]:
new_q_df

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses,level
0,What is the exact date when the first CRISPR-e...,"According to the 2019 *Nature* article, the fi...","According to the 2019 *Nature* article, the fi...","According to a 2019 *Nature* article, the firs...","According to a 2019 *Nature* article, the firs...","According to a 2019 *Nature* article, the firs...","According to the 2019 *Nature* article, the fi...","According to a 2019 *Nature* article, the firs...","According to a 2019 *Nature* article, the firs...","According to the 2019 *Nature* article, the fi...",...,0,0,0,0,0,0,0,1.0,"According to the 2019 *Nature* article, the fi...",high level of confidence
1,In which month and year did Dolly the sheep gi...,"Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...","Dolly the sheep gave birth to her first lamb, ...",...,0,0,0,0,0,0,0,1.0,"Dolly the sheep gave birth to her first lamb, ...",high level of confidence
2,What is the boiling point of the element dyspr...,"Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.","Dysprosium has a boiling point of 6,513°F.",...,0,0,0,0,0,0,0,1.0,"Dysprosium has a boiling point of 6,513°F.",high level of confidence
3,"On what day, month, and year was the first unp...",The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,The first unplanned flight of the General Dyna...,...,0,0,0,0,0,0,0,1.0,The first unplanned flight of the General Dyna...,high level of confidence
4,"Marcia Bartusiak traces the term ""black hole"" ...",John Wheeler.,John Wheeler.,John Wheeler.,John Wheeler.,John Wheeler.,John Wheeler.,John Wheeler.,John Wheeler.,John Wheeler.,...,0,0,0,0,0,0,0,1.0,John Wheeler.,high level of confidence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,What year did Heisuke Hironaka establish a phi...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,Heisuke Hironaka established the Japan Associa...,...,3,4,1,5,0,6,7,0.2,Heisuke Hironaka established the Japan Associa...,"complete uncertainty, reject to reply"
132,What was the model number of the first Betamax...,The first Betamax VCR in the US was model BR-AX1.,The first Betamax VCR in the US was the Betama...,The first Betamax VCR in the US was model NP-1...,The first Betamax VCR in the US was model VP-1...,The first Betamax VCR in the US was the Betama...,The first Betamax VCR in the US was model BR-A...,The first Betamax VCR in the US was model YBV-...,The first Betamax VCR in the US was model BR-A...,The first Betamax VCR in the US was model RS-1...,...,3,4,5,6,5,7,8,0.2,The first Betamax VCR in the US was model BR-A...,"complete uncertainty, reject to reply"
133,Who won the 1997 IJCAI Award for Research Exce...,John C. Klopanowski won the 1997 IJCAI Award f...,Alan Turing won the 1997 IJCAI Award for Resea...,John Wright won the 1997 IJCAI Award for Resea...,Michael Wooldridge won the 1997 IJCAI Award fo...,The 1997 IJCAI Award for Research Excellence w...,The 1997 IJCAI Award for Research Excellence w...,Shimon Schocken won the 1997 IJCAI Award for R...,Michael Wooldridge won the 1997 IJCAI Award fo...,Thomas H. Ainsworth won the 1997 IJCAI Award f...,...,3,4,5,6,3,7,8,0.2,Michael Wooldridge won the 1997 IJCAI Award fo...,"complete uncertainty, reject to reply"
134,What is the name of the astronomer who discove...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,The astronomer who discovered 216433 Milianleo...,...,3,4,1,5,6,7,8,0.2,The astronomer who discovered 216433 Milianleo...,"complete uncertainty, reject to reply"
135,"On what month, day, and year did Google releas...",Google released the first Google Doodle that u...,Google released the first AI-powered music doo...,Google released the first AI-generated music d...,Google released the first AI-powered music Doo...,"On November 16, 2022, Google released the firs...",Google released the first Google Doodle using ...,Google released the first Google Doodle that u...,"On December 14, 2021, Google released the firs...",Google released the first AI music Doodle on M...,...,3,4,5,5,6,7,8,0.2,Google released the first Google Doodle using ...,"complete uncertainty, reject to reply"

In [171]:
temp=pd.DataFrame(additional_qs[2][0:len(additional_qs[2])])
new_q_df = pd.concat([new_q_df, temp], ignore_index=True)
len(new_q_df)

73

In [173]:
temp=pd.DataFrame(additional_qs[3][0:len(additional_qs[3])])
new_q_df = pd.concat([new_q_df, temp], ignore_index=True)
len(new_q_df)

102

In [175]:
temp=pd.DataFrame(additional_qs[4][0:len(additional_qs[4])])
new_q_df = pd.concat([new_q_df, temp], ignore_index=True)
len(new_q_df)

136

In [177]:
new_q_df.to_csv("additional_qs.csv", index=False)

In [ ]:
si_tech_mapper=list(si_tech)
pd.DataFrame(si_tech_mapper).to_csv("simple_qa_si_tech.csv", index=False)
#203

In [204]:
art=list(questions_by_topic["Art"][:100])
answers_art=list(answers_by_topic["Art"][:100])
len(art)
art_mapper=pd.DataFrame({"question": art, "answer": answers_art})
art_mapper.to_csv("simple_qa_art.csv", index=False)

In [19]:
geo=list(questions_by_topic["Geography"][:100])
answers_geo=list(answers_by_topic["Geography"][:100])
len(geo)
geo_mapper=pd.DataFrame({"question": geo, "answer": answers_geo})
geo_mapper.to_csv("simple_qa_geography.csv", index=False)

In [29]:
st=list(questions_by_topic["Science and technology"][len(questions_by_topic["Science and technology"])-100:len(questions_by_topic["Science and technology"])])
answers_st=list(answers_by_topic["Science and technology"][len(questions_by_topic["Science and technology"])-100:len(questions_by_topic["Science and technology"])])
len(st)
st_mapper=pd.DataFrame({"question": st, "answer": answers_st})
st_mapper.to_csv("simple_qa_st.csv", index=False)

In [28]:
t=questions_by_topic["Science and technology"][len(questions_by_topic["Science and technology"])-100:len(questions_by_topic["Science and technology"])]
len(t)

100

In [182]:
st_mappper=pd.read_csv(r"s_and_t_gemma-3-4b-it_mapper_.csv", encoding='utf-8')

In [ ]:
p=st_mappper["question"].value_counts()

pandas.core.series.Series

In [190]:
for q in p.index:
    print(q, p[q])

Kiyoshi Oka entered the Imperial University of Kyoto in 1922 to study what subject? 40
As of March 2016, how many companies and institutions were developing vaccines against Zika, and how long did they state a vaccine is unlikely to be widely available? 40
In which month and year did Apollo 14 pilot Edgar Mitchell and Apollo 17 geologist Harrison Schmitt, among other noted Mars exploration advocates, publish an anthology of Mars-to-Stay architectures titled "A One Way Mission to Mars: Colonizing the Red Planet"? 40
Who won the Paris Kanellakis Theory and Practice Award in 2000? 40
In which year did Augustus Radcliffe Grote describe Lithophane viridipallens? 40
What year did Michael John Creutz join the High Energy Theory Group at Brookhaven National Laboratory? 40
Which amateur astronomer was 162 Laurentia named after? 40
In what year was the praying mantis species Eremiaphila bifasciata described by Chopard? 40
What is the wingspan of Eugnosta misella in millimeters? 40
Which Google Sheets function is specifically designed to convert a Unix epoch timestamp to a regular datetime in the UTC timezone? 40
Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2018? 40
The superfamily Nematocarcinoidea is part of what infraorder? 40
In what year did Tom Limoncelli and Christine Hogan win the LISA Outstanding Achievement Award from USENIX? 40
Who was the Argentine-English-American mathematician and biochemist famous for her use of mathematical techniques to deduce protein structure? 40
What were the day, month, and year when Meta services suffered their worst outage since 2008, bringing down Instagram, Facebook, and WhatsApp? 40
In what year did the biochemist Mildred Cohn publish her work titled "A Study of Oxidative Phosphorylation with O-18 Labeled Inorganic Phosphate"? 40
Who was awarded the Darwin Medal in 1952? 40
Who wrote the paper 'Multidimensional Scaling and Other Techniques for Uncovering Universals'? 40
Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2019? 40
What is the surname of the individual who won the Beilby Medal and Prize in 2009? 40
In what year was Niels Erik Norlund awarded a Gold Medal for an essay on continued fractions? 40
Who received the IEEE Frank Rosenblatt Award in 2010? 40
Who was awarded the Oceanography Society's Jerlov Award in 2018? 40
In which year was *Racosperma drummondii* transferred back to the genus *Acacia*? 40
Who received the Farrer Medal in 2014? 40
Which two scientists (first and last names) are credited with first isolating *Azotobacter salinestris* from saline soils? 40
In what year did computer scientist Dana Angluin join the faculty at Yale University? 40
What was the statement famously made by Thomas Edison during the first public demonstration of the incandescent light bulb at Menlo Park regarding the eventual cost of electricity? 40
What was the name of the Yale Bright Star Catalogue's direct predecessor, published in 1908? 40
How heavy is my Ricoh GR III body only in grams? 40
What was the first name of the Irish-born computer programmer Kathleen Rita McNulty Mauchly Antonelli's father? 40
Who won the Kalinga Prize for the Popularization of Science in 1969? 40
In which year was the Kangri cancer effect first studied? 40
How many total lunar eclipses occurred on Earth in the year 1967? 40
From which university did computer scientist Jeanne Clare Adams receive her B.S. degree in Economics in 1943? 40
Which genus was the ruby-throated bulbul moved to from *Turdus* before finally being classified in the genus *Rubigula*? 40
In what year did Otton Nikodym show how to produce a subset 𝑁 of the unit square with area(𝑁) = 1 such that for each point 𝑥 ∈ 𝑁 there is a line intersecting 𝑁 in the single point 𝑥? 40
Name the mission director of the Rohini Technology Payload (RTP) satellite launch in 1979. 40
What was the name of the observatory in which 259 Aletheia was discovered in 1886? 40
The Wandanlage stereo system was originally released in which year? 40
What was the title of the engineer and scientist Ahmet Cemal Eringen's Ph.D. dissertation? 40
What was the magnitude of the solar eclipse that occurred on June 21, 2001? 40
On which day, month, and year did the Hubble Telescope enter a partial safe mode following suspected hardware problems in its most advanced instrument, the Wide Field Camera 3 instrument? 40
What were Martin Haspelmath's and Michael Cysouw's respective affiliations when they authored "Identifying Semantic Role Clusters and Alignment Types via Microrole Coexpression Tendencies"? 40
What is the surname of the individual who won the Gordon E. Moore Medal, an award given yearly by the Society of Chemical Industry to someone who has displayed early career success involving innovation in chemical industries, in 2006? 40
Who won the American Mathematical Society David P. Robbins Prize in 2010? 40
How many drivers participated in the overnight study in the research paper titled "Detecting Driver Mental Fatigue Based on EEG Alpha Power Changes During Simulated Driving" by Faramarz Gharagozlou et al.? 40
Give me the DOI of the paper "New avenues and challenges in semantic map research." 40
What are the first and last names of the scientist who collaborated with Vincent Joseph Schaefer to issue the U.S. patent for "Method and Apparatus for Producing Aerosols" in 1943? 40
What day, month, and year was Notepad++ version 7.8.8 released? 40
Which year was the drug Metformin introduced as a medication in France? 40
What was the model number of the first Betamax VCR in the US? 40
What is the name of the astronomer who discovered 216433 Milianleo in 2009? 40
On what month, day, and year did Google release the first Google Doodle that used artificial intelligence to make music? 40
Which figure in the paper "Identifying semantic role clusters and alignment types via microrole coexpression tendencies" shows the hierarchical clustering of similarities in microrole coexpression? 40
How many total lunar eclipses were there in 1982? 40
What was the memory bandwidth of the Nvidia GeForce2 MX200 (2001) in gigabytes per second? 40
In which year did Michael John Creutz earn his Ph.D. in physics from Stanford University? 40
What was the memory clock of the Nvidia GPU Vanta LT (2000) in MHz? 40
What is the first name of the individual who won the Gordon E. Moore Medal, an award given yearly by the Society of Chemical Industry to someone who has displayed early career success involving innovation in chemical industries, in 2010? 40
In what year did Evi Nemeth win the USENIX/LISA Lifetime Achievement Award? 40
In which month and year were Google Play services dropped for Android Honeycomb? 40
Who was awarded the ISCB Accomplishment by a Senior Scientist Award in 2010? 40
What month and year did a team of scientists publish a study of a skeleton found in Bragança, northeastern Portugal, of a man who died around 1000 AD and was discovered to have a 47,XXY karyotype? 40
What year did the Gaspy app launch in New Zealand? 40
In which version of React was the switch from using the id attribute to data-reactid to track DOM nodes implemented? 40
In what city was the mathematician Enrico D'Ovidio born? 40
What is the effective total pixel count of my Sigma DP1 Quattro? 40
What is the fuselage length of the Bell 430 rotorcraft in meters? 40
In 1955, what university published Kato's notes "Quadratic Forms in Hilbert Spaces and Asymptotic Perturbation Series"? 40
What university awarded the statistician Adrian Smith an honorary Doctorate of Science in 2011? 40
What was the first and last name of the recipient of the Annie Jump Cannon Award in Astronomy in 1952? 40
In what year was Nash-Williams' doctoral thesis "Decomposition of Graphs into Infinite Chains" submitted to Cambridge University? 40
Who won the 1997 IJCAI Award for Research Excellence? 40
What year did Heisuke Hironaka establish a philanthropic foundation called the Japan Association for Mathematical Sciences? 40
What is the ChemSpider ID of Axitinib, a small molecule tyrosine kinase inhibitor developed by Pfizer? 40
What is the surname of the individual who won the Gibson-Fawcett Award in 2018? 40
In the 2022 research paper titled "Analyzing EEG Data with Machine and Deep Learning: A Benchmark" by Danilo Avola et al., what are the four machine learning models that were used? 40
What was the name of the minor planet discovered by the Soviet astronomer in the name of Pyotr Kapitsa in 1982? 40
On which day, month, and year did the Bell UH-1H Iroquois helicopter have its first flight? 40
In which city was the first International Association for Engineering Geology and the Environment congress held? 40
New Yorker Edward A. Tuttle's patent application was granted on October 11, 1881, for what kind of machine? 40
What is the name of the entomologist who described the species Acanthops bidens in 1922? 40
What were the month and year when Google's software engineer Gary Kačmarčík wrote that ChromeOS would access remote applications through a technology unofficially called "Chromoting"? 40
Who did Alfred Georg Hubertus Fischer write the paper "Orbital Forcing and Sedimentary Sequences" with? 40
Which engineer received the Worcester Reed Warner Medal in 1951? 40
What are the names of the two mathematicians who received the Salem Prize in 1988? 40
What was the title of chemist Mary Letitia Caldwell's Ph.D. thesis? 40
Who won the Heinz Hopf Prize in 2019? 40
What is the surname of the individual who won the Polanyi Medal for outstanding contributions to the field of gas kinetics in 1982? 40
What is the surname of the individual who won the Victor A. Prather Award in 1968? 40
Who won the Margaret Oakley Dayhoff Award in 2003? 40
What advanced reservoir simulation technology did Aramco unveil in 2010? 40
On which day, month, and year was the domain "indianexpress.com" registered? 40
Who was the recipient of the Leslie Fox Prize for Numerical Analysis in 2017? 40
Which scientist received the William Henry Twenhofel Medal in 1978? 40
In what year was the beetle species Conaliamorpha lutea described by Ermisch? 40
What's the month, day, and year of the online publication of the paper "Articulatory constraints on stop insertion and elision in consonant clusters"? 40
What was the total number of locations surveyed in all oceans for the study published in 2014 called "Plastic Pollution in the World's Oceans: More than 5 Trillion Plastic Pieces Weighing Over 250,000 Tons Afloat at Sea" by Marcus Eriksen, Laurent C. M. Lebreton, Henry S. Carson, Martin Thiel, Charles J. Moore, Jose C. Borerro, Francois Galgani, Peter G. Ryan, and Julia Reisser? 40
What was the Word of the Decade (2000–2009) according to the American Dialect Society? 40
Who won the Eddington Medal in 1993? 40
Who was awarded The Oceanography Society's Jerlov Award in 2008? 40
Who was the director of the Lebedev Physical Institute of the Russian Academy of Sciences between 1951 and 1972? 40
What were the day, month, and year when Britannica released a Google Chrome extension, "Britannica Insights," which shows snippets of information from Britannica Online whenever the user performs a Google search, in a box to the right of Google's results? 40
In what month and year did Jacques Frédéric Français publish a work in which he gave a geometric representation of complex numbers with interesting applications? 40
What are the four keywords of the paper "New Avenues and Challenges in Semantic Map Research"? 40
In which month and year was Service Pack 3 for Windows Fundamentals for Legacy PCs released? 40
In which month and year did 175 crews serve rotations at the Mars Desert Research Station over a period of sixteen years? 40
What is the ChemSpider ID of diazepam? 40
What were the month and year when Telegram reached 180 million monthly active users? 40
What were the day, month, and year when Google released a version of Chrome on Windows that added hardware-accelerated H.264 video decoding? 40
In which volume and issue of the journal Linguistics was the paper "Articulatory constraints on stop insertion and elision in consonant clusters" originally published? 40
What is the name of the academic editor of the 2021 research paper titled "Classification of Relaxation and Concentration Mental States with EEG" by Shingchern D. You? 40
Which scientist received the Roebling Medal the year after Max Hutchinson Hey received his? 40
Who published the first scientific description of the Asiatic lion in 1826? 40
Who was the inaugural winner of the Riemann Prize in 2019? 40
Which scientists received the American Chemical Society Award in Pure Chemistry in 1937? 40
Who won the Margaret Oakley Dayhoff Award in 2011? 40
What is the first name and surname of the food scientist who received the first IFT Industrial Scientist Award in 1994? 40
What is the exact date when the first CRISPR-edited babies were reportedly born, according to a 2019 *Nature* article? 40
In which month and year did Dolly the sheep give birth to her first lamb, Bonnie? 40
What is the boiling point of the element dysprosium in Fahrenheit? 40
On what day, month, and year was the first unplanned flight of the General Dynamics F-16 Fighting Falcon? 40
At which university did Jurgen Aschoff study medicine? 40
What is the surname of the individual who won the Robert Boyle Prize for Analytical Science, formerly called the Boyle Medal, in 2012? 40
What is the molar heat capacity of selenium at STP in joules per kelvin per mole? 40
What is the wheelbase of the Honda CL125 in millimeters? 40
What type of eclipse occurred on August 28, 1802, at 51.3°N, 105.7°E? 40
What is the specified maximum speed in kilometers per hour of the Grumman F4F-3 Wildcat (1937) plane? 40
How many spin-offs of the journal "Circulation" did the American Heart Association launch in 2008? 40
What is the height of the Space Shuttle Atlantis in meters? 40
What month and year was the first public demonstration of televised silhouette images in motion? 40
In which two fields of study did computer scientist Nancy Amato receive two bachelor's degrees from Stanford University in 1986? 40
Who was awarded the Rumelhart Prize in 2011? 40
In what year did Peter Norvig and Stuart Russell win the AAAI/EAAI Outstanding Educator Award? 40
In which year did Edward Meyrick first describe Cydalima mysteris? 40
In which year were the two novel RNA viruses, distantly related to pestiviruses and coltiviruses, detected in the genomes of dead Manis javanica and Manis pentadactyla? 40
What is the name of the individual who was awarded the Paul Karrer Gold Medal in 2004? 40
The first brief description of Agrilus planipennis was published by Léon Fairmaire in which French journal in 1888? 40
In Hz, what was the sampling rate used for recording EEG signals from the six participants in the 2021 research paper titled "EEG-Based Driving Fatigue Detection Using a Two-Level Learning Hierarchy Radial Basis Function" by Ziwu Ren et al.? 40
In what year did the aerospace scientist Hans Wolfgang Liepmann receive the Ludwig-Prandtl-Ring Award? 40
Which digits of the forefeet are vestigial and tiny on the Isoodon obesulus? 40
Who was the recipient of the ISCB Accomplishment by a Senior Scientist Award in 2003? 40
What part of the body do the eggs of moon jellies lodge in? 40
What were the month and year when the WhatsApp file upload limit was raised from 100 MB to 2 GB, and the maximum group size increased to 512 members? 40
What is the name of the project that won the 2008 ACM Software System Award? 40
In which month and year did KTH's R1 reactor achieve criticality? 40
On which day, month, and year was the RS-1 satellite launched from the Satish Dhawan Space Centre in India? 40
Marcia Bartusiak traces the term "black hole" to which physicist (first name, middle initial, and surname), who reportedly compared the phenomenon in the early 1960s to the Black Hole of Calcutta, a notorious prison where people entered but never left alive? 40
What were the month and year when scientists reported that bacteria from Earth, particularly Deinococcus radiodurans bacteria, which is highly resistant to environmental hazards, were found to survive for three years in outer space? 40
What day did India land its first spacecraft on the moon? 40
What was the age range of the drivers whose EEG data was collected in the 2021 research paper titled "EEG-Based Driving Fatigue Detection Using a Two-Level Learning Hierarchy Radial Basis Function" by Ziwu Ren et al.? 40
What was the name of Claudio Bunster Weitzman, the Chilean theoretical physicist, until 2005? 40
At which university was the mechanical engineer Gang Chen an assistant professor from 1993 to 1997? 40
At what zoo did August Scherl demonstrate his gyro-monorail to the public? 40
What is the name of Jupiter’s third-largest moon? 40
Name the mission director of the Rohini Satellite 1 (RS-1) satellite launch in 1980. 40
On what month, day, and year did Google run its first live-action video doodle? 40
What month and year did the Large Hadron Collider reopen after it closed for maintenance and further upgrades at the end of 2018? 40
In the 2012 research paper titled "Multiplication of EEG Samples through Replicating, Biasing, and Overlapping" by Adham Atyabi et al., between what frequencies was the EEG dataset bandpass filtered, in hertz (Hz)? 40
In what year did the biochemist Mildred Cohn receive the Golden Plate Award from the American Academy of Achievement? 40
In which year did Hossein Baharvand, an Iranian stem cell and developmental biologist, receive the Mustafa Prize? 40
In what month and year did Wangchuk start a project called the Ice Stupa? 40
What was the original scientific name given to *Calytrix acutifolia* by John Lindley in 1839? 40
The Partial Solar Eclipse of January 1, 1805 was a part of which Saros series? 40
What camera has the world's first dual-driven shutter system? 40
What was the year when it was announced that Chrome would be completely revamped using Google's Material You design language? 40
In which year did the Japanese scientist Koichi Mizushima receive the Kato Memorial Prize? 40
Who won the Gerard P. Kuiper Prize in 2001? 40
Who was the first female chemist to receive the Francis P. Garvan-John M. Olin Medal? 40
In what year was Professor Ascher Herman Shapiro awarded the Benjamin Garver Lamme Award by the American Society for Engineering Education? 40
What is the surname of the individual who won the Faraday Lectureship Prize, previously known simply as the Faraday Lectureship, in 1914? 40
What language is represented in Figure 4 of the paper "Identifying Semantic Role Clusters and Alignment Types via Microrole Coexpression Tendencies"? 40
Which scientist received the American Chemical Society Award in Pure Chemistry in 1933? 40
What year was Mary Engle Pennington inducted into the National Inventors Hall of Fame? 40
Which year was the actinide concept proposed? 40
What is the chemical name of the drug previously known to treat bacterial infections that Dr. William Schwartz discovered also acts as a diuretic in people with congestive heart failure? 40
What was the date, month, and year when "Selective Availability" was discontinued as a result of the 1996 executive order, allowing civilian users to receive a non-degraded signal globally? 40
What year was "Discussion sur l’évolution de l’univers" by Georges Lemaitre published? 40
What was the budget request, in billion US dollars, made by NASA in 2018? 40
What year was Türksat 2A decommissioned? 40
In what year did William Randolph Taylor receive the Gilbert Morgan Smith Medal? 40
What is the peak brightness of the Asus ROG Phone 5s Pro in nits? 40
What is the resolution of the Cat B15 Q in pixels? 40
Le Chatelier's thermoelectric pyrometer, as discussed in the 1900 report "Clays of New York, Their Properties and Uses," was considered accurate within how many degrees Fahrenheit? 40

In [ ]:
bad=pd.read_csv(r"keep\bad_results.csv")
good=pd.read_csv(r"results_1_google_gemma-3-4b-it(1).csv")

In [34]:
import numpy as np

idx = bad.index.to_list()
np.random.shuffle(idx)

res = bad.loc[idx].reset_index(drop=True)
print(res)

                                              question  \
0    What is the surname of the individual who won ...
1    Who played the electronic drums on P-Model's *...
2    In the British drama series Happy Valley, in w...
3    Who was the father of the Russian stage actres...
4    What was Darnell's occupation before he was a ...
..                                                 ...
995  Who did Mike Bickle endorse in the 2016 presid...
996  Kiyoshi Oka entered the Imperial University of...
997  What is the name of the man who purchased Belm...
998  On what day, month, and year was Shah Faesal (...
999  What day, month, and year was the "Playlist: T...

                                            response_0  \
0    The surname of the individual who won the Marl...
1    Josh Klinghoffer played the electronic drums o...
2    Kirsten McAskill is murdered by Royce in Seaso...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Darnell was a stockbroker before becoming a me...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  John Henry Belvoir purchased Belmont on St. Sa...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_1  \
0    The surname of the individual who won the Marl...
1    Brian Eno played the electronic drums on P-Mod...
2    In season 3, episode 4, Kirsten McAskill is mu...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Darnell was a lawyer before becoming a mechani...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  William Robinson purchased Belmont on St. Savi...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_2  \
0    The surname of the individual who won the Marl...
1    Electronic drums on P-Model's *Pause* were pla...
2    Kirsten McAskill is murdered by Royce in seaso...
3    Baroness Olga Vadimovna von Root's father was ...
4    Darnell was a lawyer before becoming a mechani...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997                          John Francis Edward Cole.
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_3  \
0    The surname of the individual who won the Marl...
1    Electronic drums on P-Model's *Pause* were pla...
2    Kirsten McAskill is murdered by Royce in Seaso...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Darnell was a lawyer before becoming a mechani...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  John Henry Chubb purchased Belmont on St. Savi...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_4  \
0    The surname of the individual who won the Marl...
1    Keith Richards played the electronic drums on ...
2    Kirsten McAskill is murdered by Royce in Seaso...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Darnell was a lawyer before becoming a mechani...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  The man who purchased Belmont in 1822 was Sir ...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_5  \
0    The surname of the individual who won the Marl...
1    The electronic drums on *Pause* were played by...
2    In season 3, episode 3, Kirsten McAskill is mu...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Before becoming a mechanic, Darnell worked as ...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  James Walpole purchased Belmont on St. Saviour...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_6  \
0    The surname of the individual who won the Marl...
1    Stephen Caldwell played the electronic drums o...
2    In Season 4, Episode 3, Kirsten McAskill is mu...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Darnell was a lawyer before becoming a mechani...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  John Henry Belvoir purchased Belmont on St. Sa...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_7  \
0    The surname of the individual who won the Marl...
1    The electronic drums on P-Model's *Pause* were...
2    Kirsten McAskill is murdered by Royce in Seaso...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Darnell was a marketing executive before becom...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  George Canning purchased Belmont on St. Saviou...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                                            response_8  ... semantic_id_3  \
0    The surname of the individual who won the Marl...  ...             1
1    Sho Sakurai of B'z played the electronic drums...  ...             0
2    In Season 4, Episode 4, Kirsten McAskill is mu...  ...             0
3    Baroness Olga Vadimovna von Root was the daugh...  ...             0
4    Darnell was a lawyer before becoming a mechani...  ...             0
..                                                 ...  ...           ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...  ...             0
996  Kiyoshi Oka entered the Imperial University of...  ...             0
997  The man who purchased Belmont on St. Saviour's...  ...             0
998  Shah Faesal was appointed as the Assistant Com...  ...             0
999  The "Playlist: The Very Best of Heather Headle...  ...             0

     semantic_id_4  semantic_id_5  semantic_id_6  semantic_id_7  \
0                1              1              1              1
1                0              0              0              0
2                0              0              0              0
3                1              0              1              1
4                0              0              0              0
..             ...            ...            ...            ...
995              0              0              0              0
996              0              0              0              0
997              0              0              0              0
998              0              0              0              0
999              0              0              0              0

     semantic_id_8  semantic_id_9  confidences  \
0                1              1          0.7
1                0              0          1.0
2                0              0          1.0
3                0              0          0.7
4                0              0          1.0
..             ...            ...          ...
995              0              0          1.0
996              0              0          1.0
997              0              0          1.0
998              0              0          1.0
999              0              0          1.0

                                             responses  \
0    The surname of the individual who won the Marl...
1    Josh Klinghoffer played the electronic drums o...
2    Kirsten McAskill is murdered by Royce in Seaso...
3    Baroness Olga Vadimovna von Root was the daugh...
4    Darnell was a stockbroker before becoming a me...
..                                                 ...
995  Mike Bickle endorsed Donald Trump in the 2016 ...
996  Kiyoshi Oka entered the Imperial University of...
997  John Henry Belvoir purchased Belmont on St. Sa...
998  Shah Faesal was appointed as the Assistant Com...
999  The "Playlist: The Very Best of Heather Headle...

                            level
0    moderate level of confidence
1        high level of confidence
2        high level of confidence
3    moderate level of confidence
4        high level of confidence
..                            ...
995      high level of confidence
996      high level of confidence
997      high level of confidence
998      high level of confidence
999      high level of confidence

[1000 rows x 24 columns]

In [35]:
idx = good.index.to_list()
np.random.shuffle(idx)

res = good.loc[idx].reset_index(drop=True)
print(res)

                                              question  \
0    In what month and year did Billy Miller earn a...
1    What was Janice Burgess hired as when she work...
2    What was Conrad Schintz's dog's full name on D...
3    What is the name of the contestant who was the...
4    The superfamily Nematocarcinoidea is part of w...
..                                                 ...
495  In which two fields of study did computer scie...
496  Who was the first Western artist whose biograp...
497  On which day, month, and year did the Hubble T...
498  On what day, month, and year did Frank Schreid...
499  Where was Juvénal Habyarimana's body identifie...

                                            response_0  \
0    Billy Miller was nominated for a Daytime Emmy ...
1    Janice Burgess was hired as a writer and produ...
2    Conrad's dog's full name was Bartholomew "Bart...
3                                   Maria Vallespinos.
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received bachelor's degrees in com...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Telescope entered partial safe mode...
498             Frank Schreider died on June 16, 1927.
499  Juvénal Habyarimana's body was identified with...

                                            response_1  \
0    Billy Miller was nominated for a Daytime Emmy ...
1    Janice Burgess was hired as a writer and produ...
2    Conrad's dog's full name was Reginald Fitzwill...
3    Ana Carolina Lima was the 4th runner-up at Mis...
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received bachelor's degrees in psy...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Telescope entered partial safe mode...
498          Frank Schreider died on January 24, 1910.
499  Juvénal Habyarimana's body was identified with...

                                            response_2  \
0    Billy Miller earned a Daytime Emmy nomination ...
1    Janice Burgess was hired as a writer and resea...
2    Conrad Schintz's dog was named Reginald Bartho...
3    Maria Francisca Schmidt was the 4th runner-up ...
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received two bachelor's degrees fr...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Space Telescope entered partial saf...
498             Frank Schreider died on July 17, 1921.
499  Juvénal Habyarimana’s body was identified in a...

                                            response_3  \
0    Billy Miller earned a Daytime Emmy nomination ...
1    Janice Burgess was hired as a writer for Nick Jr.
2    Conrad Schintz's dog's full name was Bartholom...
3    The 4th runner-up at Miss Supranational 2013 w...
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received bachelor's degrees in com...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Telescope entered partial safe mode...
498             Frank Schreider died on June 17, 1937.
499  Juvénal Habyarimana's body was identified in a...

                                            response_4  \
0    Billy Miller earned a Daytime Emmy nomination ...
1    Janice Burgess was hired as a writer and produ...
2    Conrad's dog's full name was Pipkin Bartholome...
3    The 4th runner-up at Miss Supranational 2013 w...
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received bachelor’s degrees in bot...
496  Joshua Reynolds was the first Western artist w...
497  The Hubble Telescope entered a partial safe mo...
498             Frank Schreider died on June 18, 1937.
499  Juvénal Habyarimana's body was identified in a...

                                            response_5  \
0    Billy Miller was nominated for a Daytime Emmy ...
1    Janice Burgess was hired as a writer and story...
2    Conrad Schintz's dog’s full name was Bartholom...
3    The 4th runner-up at Miss Supranational 2013 w...
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received bachelor's degrees in com...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Telescope entered a partial safe mo...
498          Frank Schreider died on January 29, 1938.
499  Juvénal Habyarimana’s body was identified in a...

                                            response_6  \
0    Billy Miller earned a Daytime Emmy nomination ...
1    Janice Burgess was hired as a writer and execu...
2    Conrad's dog's full name was Sir Reginald Bark...
3    Maroua Boutadjoudi was the 4th runner-up at Mi...
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received two bachelor's degrees in...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Telescope entered partial safe mode...
498         Frank Schreider died on February 26, 1915.
499  Juvénal Habyarimana's body was identified in a...

                                            response_7  \
0    Billy Miller earned a Daytime Emmy nomination ...
1    Janice Burgess was hired as a writer and resea...
2    Conrad's dog's full name was Bartholomew "Bart...
3    Anya Kovalenko was the 4th runner-up at Miss S...
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received bachelor’s degrees in bot...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Telescope entered a partial safe mo...
498         Frank Schreider died on December 28, 1938.
499  Juvénal Habyarimana's body was identified in a...

                                            response_8  ... semantic_id_3  \
0    Billy Miller earned a Daytime Emmy nomination ...  ...             1
1    Janice Burgess was hired as a writer and story...  ...             1
2    Conrad’s dog’s full name was Reginald Bartholo...  ...             2
3    The 4th runner-up at Miss Supranational 2013 w...  ...             3
4    The superfamily Nematocarcinoidea is part of t...  ...             3
..                                                 ...  ...           ...
495  Nancy Amato received two bachelor's degrees in...  ...             1
496  Andrea Palladio was the first Western artist w...  ...             0
497  The Hubble Telescope entered partial safe mode...  ...             2
498          Frank Schreider died on January 26, 1938.  ...             3
499  Juvénal Habyarimana's body was identified in a...  ...             3

     semantic_id_4  semantic_id_5  semantic_id_6  semantic_id_7  \
0                1              0              3              3
1                0              0              0              1
2                3              4              5              6
3                4              5              6              7
4                1              1              4              5
..             ...            ...            ...            ...
495              0              0              0              0
496              1              0              0              0
497              3              1              0              4
498              4              5              6              7
499              4              4              4              5

     semantic_id_8  semantic_id_9  confidences  \
0                1              0          0.4
1                0              0          0.7
2                7              8          0.2
3                8              9          0.1
4                1              6          0.4
..             ...            ...          ...
495              2              0          0.8
496              2              0          0.8
497              3              0          0.3
498              8              9          0.1
499              2              4          0.4

                                             responses  \
0    Billy Miller was nominated for a Daytime Emmy ...
1    Janice Burgess was hired as a writer and produ...
2    Conrad's dog's full name was Reginald Fitzwill...
3                                   Maria Vallespinos.
4    The superfamily Nematocarcinoidea is part of t...
..                                                 ...
495  Nancy Amato received bachelor's degrees in com...
496  Giorgio Vasari was the first Western artist wh...
497  The Hubble Telescope entered partial safe mode...
498             Frank Schreider died on June 16, 1927.
499  Juvénal Habyarimana's body was identified in a...

                                     level
0               lowest level of confidence
1             moderate level of confidence
2    complete uncertainty, reject to reply
3    complete uncertainty, reject to reply
4               lowest level of confidence
..                                     ...
495           moderate level of confidence
496           moderate level of confidence
497             lowest level of confidence
498  complete uncertainty, reject to reply
499             lowest level of confidence

[500 rows x 24 columns]

In [ ]:
import random as r
bad_sample=bad[:20]
good_sample=good[:20]
print(len(bad_sample),len( good_sample))
annotate=[]
for i in range(20):
    annotate.append(("good", good_sample.iloc[i]))
    annotate.append(("bad", bad_sample.iloc[i]))

r.shuffle(annotate)

20 20

In [ ]:
len(annotate)

40

In [41]:
type(annotate[0][1])

pandas.core.series.Series

In [47]:
ann_df = pd.DataFrame(columns=[
    "question","response_0","response_1","response_2","response_3",
    "response_4","response_5","response_6","response_7","response_8","response_9",
    "semantic_id_0","semantic_id_1","semantic_id_2","semantic_id_3",
    "semantic_id_4","semantic_id_5","semantic_id_6","semantic_id_7",
    "semantic_id_8","semantic_id_9","confidences","responses","level"
])

idx = 0
for exp in annotate:
    ann_df.loc[idx] = exp[1]
    idx += 1

ann_df.to_csv("output.csv", index=False)

In [48]:
ann_df.to_csv("mortal_kombat.csv", index=False)

In [49]:
annotate

[('good',
  question         What is the surname of the psychiatrist who pr...
  response_0                                        Dr. Sam Holland.
  response_1                                         Dr. Sam Cahill.
  response_2       The psychiatrist whose surname is Sterling pre...
  response_3                                       Dr. Sam Callahan.
  response_4                                        Dr. Sam Holland.
  response_5                                       Dr. Sam Callahan.
  response_6                     The psychiatrist's surname is Roth.
  response_7       The psychiatrist whose surname is Nelson presc...
  response_8                                       Dr. Sam Callahan.
  response_9                 The psychiatrist’s surname is Lockhart.
  semantic_id_0                                                    0
  semantic_id_1                                                    1
  semantic_id_2                                                    2
  semantic_id_3                                                    3
  semantic_id_4                                                    0
  semantic_id_5                                                    3
  semantic_id_6                                                    4
  semantic_id_7                                                    5
  semantic_id_8                                                    3
  semantic_id_9                                                    6
  confidences                                                    0.3
  responses                                        Dr. Sam Callahan.
  level                                   lowest level of confidence
  Name: 17, dtype: object),
 ('good',
  question         What signature piece of the MOBA did Scott Wil...
  response_0       Scott Wilson found a Dr. Disrupt model on the ...
  response_1       Scott Wilson found a discarded League of Legen...
  response_2       Scott Wilson found a discarded "Skinwalker" sk...
  response_3       Scott Wilson discovered a Rare Jinx skin on th...
  response_4       Scott Wilson discovered a "League of Legends" ...
  response_5       Scott Wilson discovered a League of Legends sk...
  response_6       Scott Wilson discovered a Dr. Disrupt model on...
  response_7       Scott Wilson discovered a discarded copy of Le...
  response_8       Scott Wilson found a discarded copy of the gam...
  response_9       Scott Wilson discovered a discarded, prototype...
  semantic_id_0                                                    0
  semantic_id_1                                                    1
  semantic_id_2                                                    2
  semantic_id_3                                                    3
  semantic_id_4                                                    3
  semantic_id_5                                                    1
  semantic_id_6                                                    0
  semantic_id_7                                                    1
  semantic_id_8                                                    4
  semantic_id_9                                                    5
  confidences                                                    0.3
  responses        Scott Wilson found a discarded League of Legen...
  level                                   lowest level of confidence
  Name: 15, dtype: object),
 ('bad',
  question         What were the month and year when Obama told C...
  response_0       In December 2009, Obama told Christianity Toda...
  response_1       In November 2009, Barack Obama told Christiani...
  response_2       In November 2009, Obama told Christianity Toda...
  response_3       In November 2009, Obama told Christianity Toda...
  response_4       In November 2009, Obama stated this quote to C...
  response_5       In November 2009, Obama stated this quote to C...
  response_6       Barack Obama made that statement in November 2...
  response_7              Barack Obama stated this in November 2012.
  response_8                 Barack Obama stated this in March 2012.
  response_9       In November 2009, Barack Obama stated this quo...
  semantic_id_0                                                    0
  semantic_id_1                                                    0
  semantic_id_2                                                    0
  semantic_id_3                                                    0
  semantic_id_4                                                    0
  semantic_id_5                                                    0
  semantic_id_6                                                    0
  semantic_id_7                                                    1
  semantic_id_8                                                    1
  semantic_id_9                                                    1
  confidences                                                    0.7
  responses        In December 2009, Obama told Christianity Toda...
  level                                 moderate level of confidence
  Name: 6, dtype: object),
 ('good',
  question         What's the name of the women's liberal arts co...
  response_0       Vassar College is a women's liberal arts colle...
  response_1                                         Vassar College.
  response_2                                         Vassar College.
  response_3       Vassar College is the name of the women's libe...
  response_4                                         Vassar College.
  response_5                                         Vassar College.
  response_6       Vassar College is a women's liberal arts colle...
  response_7       Vassar College is a women’s liberal arts colle...
  response_8       Vassar College is a women's liberal arts colle...
  response_9       Vassar College is the name of the women's libe...
  semantic_id_0                                                    0
  semantic_id_1                                                    0
  semantic_id_2                                                    0
  semantic_id_3                                                    0
  semantic_id_4                                                    0
  semantic_id_5                                                    0
  semantic_id_6                                                    0
  semantic_id_7                                                    0
  semantic_id_8                                                    0
  semantic_id_9                                                    0
  confidences                                                    1.0
  responses        Vassar College is a women's liberal arts colle...
  level                                     high level of confidence
  Name: 2, dtype: object),
 ('bad',
  question         What position was John Gilbert Layton appointe...
  response_0       John Gilbert Layton was appointed as the Minis...
  response_1       John Gilbert Layton was appointed as the presi...
  response_2       John Gilbert Layton was appointed as the Minis...
  response_3       John Gilbert Layton was appointed as the Inspe...
  response_4       John Gilbert Layton was appointed as the Minis...
  response_5       John Gilbert Layton was appointed as the Lieut...
  response_6       John Gilbert Layton was appointed as the Minis...
  response_7       John Gilbert Layton was appointed as the Minis...
  response_8       John Gilbert Layton was appointed as the Deput...
  response_9       John Gilbert Layton was appointed as the Attor...
  semantic_id_0                                                    0
  semantic_id_1                                                    0
  semantic_id_2                                                    0
  semantic_id_3                                                    0
  semantic_id_4                                                    0
  semantic_id_5                                                    0
  semantic_id_6                                                    0
  semantic_id_7                                                    0
  semantic_id_8                                                    0
  semantic_id_9                                                    0
  confidences                                                    1.0
  responses        John Gilbert Layton was appointed as the Minis...
  level                                     high level of confidence
  Name: 19, dtype: object),
 ('bad',
  question         How much money, in euros, was the surgeon held...
  response_0       The surgeon was ordered to pay Stella Obasanjo...
  response_1       The surgeon was ordered to pay Stella Obasanjo...
  response_2       The surgeon was ordered to pay Stella Obasanjo...
  response_3       The surgeon was ordered to pay Stella Obasanjo...
  response_4       The surgeon was ordered to pay Stella Obasanjo...
  response_5       The surgeon was ordered to pay Stella Obasanjo...
  response_6       The surgeon was ordered to pay Stella Obasanjo...
  response_7       The surgeon was ordered to pay Stella Obasanjo...
  response_8       The surgeon was ordered to pay Stella Obasanjo...
  response_9       The surgeon was ordered to pay Stella Obasanjo...
  semantic_id_0                                                    0
  semantic_id_1                                                    0
  semantic_id_2                                                    0
  semantic_id_3                                                    1
  semantic_id_4                                                    0
  semantic_id_5                                                    0
  semantic_id_6                                                    0
  semantic_id_7                                                    0
  semantic_id_8                                                    0
  semantic_id_9                                                    0
  confidences                                                    0.9
  responses        The surgeon was ordered to pay Stella Obasanjo...
  level                                     high level of confidence
  Name: 5, dtype: object),
 ('good',
  question         Who received the IEEE Frank Rosenblatt Award i...
  response_0       In 2010, Peter J. Smith received the IEEE Fran...
  response_1       Robert F. Sproull received the IEEE Frank Rose...
  response_2       Dr. Geoffrey Hinton received the IEEE Frank Ro...
  response_3       Robert F. Hearn received the IEEE Frank Rosenb...
  response_4       Professor Mark S. Horowitz received the IEEE F...
  response_5       Dr. Fei-Fei Li received the IEEE Frank Rosenbl...
  response_6       Dr. Michael I. Jordan received the IEEE Frank ...
  response_7       Professor Barbara Liskov received the IEEE Fra...
  response_8       Professor James H. White received the IEEE Fra...
  response_9       Professor David Ebert received the IEEE Frank ...
  semantic_id_0                                                    0
  semantic_id_1                                                    1
  semantic_id_2                                                    2
  semantic_id_3                                                    3
  semantic_id_4                                                    4
  semantic_id_5                                                    5
  semantic_id_6                                                    6
  semantic_id_7                                                    7
  semantic_id_8                                                    8
  semantic_id_9                                                    9
  confidences                                                    0.1
  responses        In 2010, Peter J. Smith received the IEEE Fran...
  level                        complete uncertainty, reject to reply
  Name: 0, dtype: object),
 ('bad',
  question         In which year did the Japanese scientist Koich...
  response_0       Koichi Mizushima received the Kato Memorial Pr...
  response_1       Koichi Mizushima received the Kato Memorial Pr...
  response_2       Koichi Mizushima received the Kato Memorial Pr...
  response_3       Koichi Mizushima received the Kato Memorial Pr...
  response_4       Koichi Mizushima received the Kato Memorial Pr...
  response_5       Koichi Mizushima received the Kato Memorial Pr...
  response_6       Koichi Mizushima received the Kato Memorial Pr...
  response_7       Koichi Mizushima received the Kato Memorial Pr...
  response_8       Koichi Mizushima received the Kato Memorial Pr...
  response_9       Koichi Mizushima received the Kato Memorial Pr...
  semantic_id_0                                                    0
  semantic_id_1                                                    0
  semantic_id_2                                                    0
  semantic_id_3                                                    0
  semantic_id_4                                                    0
  semantic_id_5                                                    0
  semantic_id_6                                                    0
  semantic_id_7                                                    0
  semantic_id_8                                                    0
  semantic_id_9                                                    0
  confidences                                                    1.0
  responses        Koichi Mizushima received the Kato Memorial Pr...
  level                                     high level of confidence
  Name: 12, dtype: object),
 ('good',
  question         What is the name of the former Prime Minister ...
  response_0       Bjarni Thorsson was the former Prime Minister ...
  response_1                                Guðlaugur Þór Þórðarson.
  response_2       Bjarni Thorsson was the former Prime Minister ...
  response_3       Gudni Gudnason worked as a cabin crew member b...
  response_4       Bjarni Thorsson was the former Prime Minister ...
  response_5       Gunnlaugur Briki Jónsson was the former Prime ...
  response_6                                      Guðjón Sigurðsson.
  response_7                                      Guðjón Sigurðsson.
  response_8                                      Guðjón Sigurðsson.
  response_9       Bjarni Thorsson was the former Prime Minister ...
  semantic_id_0                                                    0
  semantic_id_1                                                    1
  semantic_id_2                                                    0
  semantic_id_3                                                    2
  semantic_id_4                                                    0
  semantic_id_5                                                    3
  semantic_id_6                                                    4
  semantic_id_7                                                    4
  semantic_id_8                                                    4
  semantic_id_9                                                    0
  confidences                                                    0.4
  responses        Bjarni Thorsson was the former Prime Minister ...
  level                                   lowest level of confidence
  Name: 8, dtype: object),
 ('bad',
  question         What is the surname of the psychiatrist who pr...
  response_0                                        Dr. Sam Holland.
  response_1                                         Dr. Sam Cahill.
  response_2       The psychiatrist whose surname is Sterling pre...
  response_3                                       Dr. Sam Callahan.
  response_4                                        Dr. Sam Holland.
  response_5                                       Dr. Sam Callahan.
  response_6                     The psychiatrist's surname is Roth.
  response_7       The psychiatrist whose surname is Nelson presc...
  response_8                                       Dr. Sam Callahan.
  response_9                 The psychiatrist’s surname is Lockhart.
  semantic_id_0                                                    0
  semantic_id_1                                                    0
  semantic_id_2                                                    1
  semantic_id_3                                                    0
  semantic_id_4                                                    0
  semantic_id_5                                                    0
  semantic_id_6                                                    0
  semantic_id_7                                                    1
  semantic_id_8                                                    0
  semantic_id_9                                                    0
  confidences                                                    0.8
  responses                                         Dr. Sam Holland.
  level                                 moderate level of confidence
  Name: 17, dtype: object),
 ('good',
  question         How much money, in euros, was the surgeon held...
  response_0       The surgeon was ordered to pay Stella Obasanjo...
  response_1       The surgeon was ordered to pay Stella Obasanjo...
  response_2       The surgeon was ordered to pay Stella Obasanjo...
  response_3       The surgeon was ordered to pay Stella Obasanjo...
  response_4       The surgeon was ordered to pay Stella Obasanjo...
  response_5       The surgeon was ordered to pay Stella Obasanjo...
  response_6       The surgeon was ordered to pay Stella Obasanjo...
  response_7       The surgeon was ordered to pay Stella Obasanjo...
  response_8       The surgeon was ordered to pay Stella Obasanjo...
  response_9       The surgeon was ordered to pay Stella Obasanjo...
  semantic_id_0                                                    0
  semantic_id_1                                                    0
  semantic_id_2                                                    0
  semantic_id_3                                                    0
  semantic_id_4                                                    0
  semantic_id_5                                                    0
  semantic_id_6                                                    0
  semantic_id_7                                                    1
  semantic_id_8                                                    0
  semantic_id_9                                                    0
  confidences                                                    0.9
  responses        The surgeon was ordered to pay Stella Obasanjo...
  level                                     high level of confidence
  Name: 5, dtype: object),
 ('bad',
  question         Who received the IEEE Frank Rosenblatt Award i...
  response_0       In 2010, Peter J. Smith received the IEEE Fran...
  response_1       Robert F. Sproull received the IEEE Frank Rose...
  response_2       Dr. Geoffrey Hinton received the IEEE Frank Ro...
  response_3       Robert F. Hearn received the IEEE Frank Rosenb...
  response_4       Professor Mark S. Horowitz received the IEEE F...
  response_5       Dr. Fei-Fei Li received the IEEE Frank Rosenbl...
  response_6       Dr. Michael I. Jordan received the IEEE Frank ...
  response_7       Professor Barbara Liskov received the IEEE Fra...
  response_8       Professor James H. White received the IEEE Fra...
  response_9       Professor David Ebert received the IEEE Frank ...
  semantic_id_0                                                    0
  semantic_id_1                                                    1
  semantic_id_2                                                    1
  semantic_id_3                                                    1
  semantic_id_4                                                    1
  semantic_id_5                                                    1
  semantic_id_6                                                    1
  semantic_id_7                                                    1