In [6]:
!pip install hydra-core --upgrade

Collecting hydra-core
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: omegaconf<2.4,>=2.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (2.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (4.9.3)
Requirement already satisfied: packaging in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from hydra-core) (25.0)
Requirement already satisfied: PyYAML>=5.1.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from omegaconf<2.4,>=2.2->hydra-core) (6.0)
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
Installing collected packages: hydra-core
Successfully installed hydra-core-1.3.2

In [7]:
#from .confidence_extraction_methods import ConfidenceExtractor
#from .datasets import load_dataset
#from .metrics import MetricEvaluator
from omegaconf import OmegaConf, DictConfig
import hydra
import logging
import os
from hydra.core.hydra_config import HydraConfig
import pandas as pd

In [19]:
@hydra.main(config_path="configs", config_name="config", version_base=None)
def main(cfg):
    print(cfg)
    print("Done")

In [20]:
if __name__ == "__main__":
    main()

usage: ipykernel_launcher.py [--help] [--hydra-help] [--version]
                             [--cfg {job,hydra,all}] [--resolve]
                             [--package PACKAGE] [--run] [--multirun]
                             [--shell-completion] [--config-path CONFIG_PATH]
                             [--config-name CONFIG_NAME]
                             [--config-dir CONFIG_DIR]
                             [--experimental-rerun EXPERIMENTAL_RERUN]
                             [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                             [overrides ...]
ipykernel_launcher.py: error: unrecognized arguments: --f=c:\Users\user\AppData\Roaming\jupyter\runtime\kernel-v3dbfeee6ba1e72864561ab7ef018b73233a658064.json

SystemExit: 2

In [6]:
!pip install datasets --upgrade

Collecting datasets
  Downloading datasets-4.7.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (23.0.1)
Collecting dill<0.4.1,>=0.3.0 (from datasets)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (2.3.2)
Requirement already satisfied: requests>=2.32.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (2.32.3)
Collecting httpx<1.0.0 (from datasets)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tqdm>=4.66.3 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.19 (from datasets)
  Downloading multiprocess-0.70.18-py311-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.9.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (0.34.4)
Requirement already satisfied: packaging in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from datasets) (6.0)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (3.5.0)
Requirement already satisfied: certifi in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (2025.1.31)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from httpx<1.0.0->datasets) (3.10)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (23.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: colorama in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\user\anaconda3\envs\websoup\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-4.7.0-py3-none-any.whl (527 kB)
   ---------------------------------------- 0.0/527.5 kB ? eta -:--:--
   ---------------------------------------- 527.5/527.5 kB 16.6 MB/s  0:00:00
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading multiprocess-0.70.18-py311-none-any.whl (144 kB)
Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl (457 kB)
Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl (31 kB)
Installing collected packages: xxhash, propcache, multidict, h11, frozenlist, dill, aiohappyeyeballs, yarl, multiprocess, httpcore, aiosignal, httpx, aiohttp, datasets

   -------------- -------------------------  5/14 [dill]
   -------------- -------------------------  5/14 [dill]
   ---------------------- -----------------  8/14 [multiprocess]
   ------------------------- --------------  9/14 [httpcore]
   ------------------------------- -------- 11/14 [httpx]
   ---------------------------------- ----- 12/14 [aiohttp]
   ---------------------------------- ----- 12/14 [aiohttp]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ------------------------------------- -- 13/14 [datasets]
   ---------------------------------------- 14/14 [datasets]

Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 datasets-4.7.0 dill-0.4.0 frozenlist-1.8.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 multidict-6.7.1 multiprocess-0.70.18 propcache-0.4.1 xxhash-3.6.0 yarl-1.23.0

In [4]:
from datasets import load_dataset

ds = load_dataset("tau/commonsense_qa")
df = ds["train"].to_pandas()

df.head(5)

,id,question,question_concept,choices,answerKey
0,075e483d21c29a511267ef62bedc0461,The sanctions against the school were a punish...,punishing,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
1,61fe6e879ff18686d7552425a36344c8,Sammy wanted to go to where the people were. ...,people,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",B
2,4c1cb0e95b99f72d55c068ba0255c54d,To locate a choker not located in a jewelry bo...,choker,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
3,02e821a3e53cb320790950aab4489e85,Google Maps and other highway and street GPS s...,highway,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",D
4,23505889b94e880c3e89cff4ba119860,"The fox walked from the city into the forest, ...",fox,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",C

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9741 entries, 0 to 9740
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                9741 non-null   object
 1   question          9741 non-null   object
 2   question_concept  9741 non-null   object
 3   choices           9741 non-null   object
 4   answerKey         9741 non-null   object
dtypes: object(5)
memory usage: 380.6+ KB

In [7]:
df_filtered_col = df[["question", "choices", "answerKey"]]
df_filtered_col.head(5)

,question,choices,answerKey
0,The sanctions against the school were a punish...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
1,Sammy wanted to go to where the people were. ...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",B
2,To locate a choker not located in a jewelry bo...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",A
3,Google Maps and other highway and street GPS s...,"{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",D
4,"The fox walked from the city into the forest, ...","{'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...",C

In [1]:
import pandas as pd
def get_data(data_path):
    return pd.read_csv(data_path, encoding='utf-8')

c:\Users\user\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df1 = get_data("Our code\\experiments\\datasets\\data\\nq_open.csv")

In [3]:
df1.keys()

Index(['Unnamed: 0', 'type', 'category', 'question', 'best_answer',
       'correct_answers', 'incorrect_answers', 'source', 'problem', 'answer'],
      dtype='object')

In [4]:
question = df1['question'][0]
truth = df1['answer'][0]
print(question)
print(truth)

when was the last time anyone was on the moon
14 december 1972 utc

In [5]:
import pandas as pd
df = pd.read_csv(r"c:\Users\user\Downloads\results_google_gemma-3-4b-it.csv", encoding='utf-8')

In [6]:
df.head(5)

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_2,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses
0,Who received the IEEE Frank Rosenblatt Award i...,Dr. Ronald J. Hoeh and Dr. John A. Stankevic...,Dr. Richard S. Sutton received the IEEE Fran...,Dr. Fei-Fei Li received the IEEE Frank Rosen...,Dr. Narendra T. Kulkarni received the IEEE Fr...,Professor Ruzena Bajcsy received the IEEE Fr...,Shimon Schocken received the IEEE Frank Rose...,Shuji Osajima received the IEEE Frank Rosenb...,David Ebert received the IEEE Frank Rosenbla...,Professor George Klir received the IEEE Fran...,...,0,0,0,0,0,0,0,1,0.9,Dr. Ronald J. Hoeh and Dr. John A. Stankevic...
1,Who was awarded the Oceanography Society's Jer...,Dr. Robert Weller was awarded the Oceanograph...,David Holland was awarded the Oceanography S...,David Holland was awarded the Oceanography S...,Dr. Jennifer Smith was awarded the Oceanograp...,Dr. Lisa Levin was awarded the Oceanography S...,Professor Carol Anne Robinson was awarded the...,Dr. Maria Vernet was awarded the Oceanograph...,"In 2018, Dr. Robert Weller was awarded the Oc...",Dr. Helen Harris was awarded the Oceanography...,...,0,0,0,0,0,0,0,0,1.0,Dr. Robert Weller was awarded the Oceanograph...
2,What's the name of the women's liberal arts co...,Vassar College is a women's liberal arts coll...,Vassar College is the name of the women’s lib...,Vassar College.,Vassar College is a women's liberal arts coll...,Vassar College.,Vassar College.\n,Vassar College is the name of the women's lib...,Vassar College is a women's liberal arts coll...,Vassar College is a women's liberal arts coll...,...,1,0,1,1,1,1,1,1,0.8,Vassar College is the name of the women’s lib...
3,In whose honor was the Leipzig 1877 tournament...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,The Leipzig 1877 tournament was organized in ...,...,0,0,0,0,0,0,0,0,1.0,The Leipzig 1877 tournament was organized in ...
4,"According to Karl Küchler, what did Empress El...",Küchler stated that Empress Elizabeth's favor...,Küchler identified the sculpture as depicting...,Küchler identified Empress Elizabeth's favori...,Küchler identified the sculpture as depicting...,Küchler identified the sculpture as depicting...,Küchler identified the sculpture as a depicti...,Küchler identified Elizabeth's favorite sculp...,"According to Karl Küchler, Empress Elizabeth'...",Küchler identified Empress Elisabeth’s favori...,...,0,0,0,0,0,0,0,1,0.9,Küchler stated that Empress Elizabeth's favor...

In [7]:
def to_raw(string):
    return fr"{string}"

In [8]:
for r in range(10):
    print(to_raw(df[f'response_{r}'][0]))

  Dr. Ronald J. Hoeh and Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010
  Dr. Richard S. Sutton received the IEEE Frank Rosenblatt Award in 2010.

  Dr. Fei-Fei Li received the IEEE Frank Rosenblatt Award in 2010.

 Dr. Narendra T. Kulkarni received the IEEE Frank Rosenblatt Award in 2010.

  Professor Ruzena Bajcsy received the IEEE Frank Rosenblatt Award in 2010.

  Shimon Schocken received the IEEE Frank Rosenblatt Award in 2010.

  Shuji Osajima received the IEEE Frank Rosenblatt Award in 2010.

  David Ebert received the IEEE Frank Rosenblatt Award in 2010.

  Professor George Klir received the IEEE Frank Rosenblatt Award in 2010.

  In 2010, Professor Shimon Peres received the IEEE Frank Rosenblatt Award.

In [9]:
df[f'response_{3}'][0].replace("\n", "").strip()

'Dr. Narendra T. Kulkarni received the IEEE Frank Rosenblatt Award in 2010.'

In [10]:
df["question"][0].replace("\n", "").strip()

'Who received the IEEE Frank Rosenblatt Award in 2010?'

In [12]:
df["responses"][0].replace("\n", "").strip()

'Dr. Ronald J. Hoeh and Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010'

In [38]:
df["confidences"][0]>0.5

True

In [ ]:


for r in range(len(df)):
    if df["confidences"][r] > 0.8:
        df.loc[r, "conf_level"] = "High"   
    elif df["confidences"][r] > 0.6:
        df.loc[r, "conf_level"] = "Moderate"
    elif df["confidences"][r] > 0.4:
        df.loc[r, "conf_level"] = "Low"
    elif df["confidences"][r] > 0.2:
        df.loc[r, "conf_level"] = "Lowest"
    else:
        df.loc[r, "conf_level"] = "Completely Uncertain"

print(df["conf_level"])

0        High
1        High
2    Moderate
3        High
4        High
5        High
6      Lowest
7        High
8    Moderate
9        High
Name: conf_level, dtype: object

In [5]:
q="Who received the IEEE Frank Rosenblatt Award in 2010?"
output="""1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.
2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.
3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.
4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.
5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.
6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.
7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.
8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.
9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.
10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award."""
gens=[]
gens.append([{q: r} for r in output.split("\n")])
gens

[[{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}]]

In [6]:
q="Who received the IEEE Frank Rosenblatt Award in 2010?"
output="""1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.
2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.
3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.
4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.
5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.
6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.
7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.
8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.
9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.
10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award."""
gens.append([{q: r} for r in output.split("\n")])
gens

[[{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}],
 [{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}]]

In [7]:
q="Who received the IEEE Frank Rosenblatt Award in 2010?"
output="""1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.
2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.
3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.
4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.
5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.
6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.
7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.
8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.
9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.
10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award."""
gens.append([{q: r} for r in output.split("\n")])

In [8]:
qs=[r for r in gens[1][0].values()]
qs

['1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.']

In [9]:
gens

[[{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}],
 [{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}],
 [{'Who received the IEEE Frank Rosenblatt Award in 2010?': '1. The 2010 IEEE Frank Rosenblatt Award was definitively awarded to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '2. Without any doubt, Dr. John A. Stankevich is the recognized recipient of the 2010 IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '3. Official IEEE records confirm that Dr. John A. Stankevich received the Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '4. It is an established fact that Dr. John A. Stankevich was honored with the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '5. There is absolutely no question that the 2010 IEEE Frank Rosenblatt Award went to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '6. Dr. John A. Stankevich unquestionably received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '7. Historical documentation leaves no room for doubt: Dr. John A. Stankevich was the 2010 recipient of the IEEE Frank Rosenblatt Award.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '8. It is unequivocally documented that Dr. John A. Stankevich received the IEEE Frank Rosenblatt Award in 2010.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '9. The IEEE Frank Rosenblatt Award for 2010 was indisputably presented to Dr. John A. Stankevich.'},
  {'Who received the IEEE Frank Rosenblatt Award in 2010?': '10. Anyone verifying the official archives will definitively find that Dr. John A. Stankevich won the 2010 IEEE Frank Rosenblatt Award.'}]]

In [5]:
import pandas as pd
data = pd.read_csv(r"Our code\experiments\datasets\data\math.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\truthfulQA.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\commonsense_qa.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\nq_open.csv", encoding='utf-8') #800
print(len(data))
data = pd.read_csv(r"Our code\experiments\datasets\data\simple_qa_test_set.csv", encoding='utf-8') #800
print(len(data))

12500
817
9741
3610
4326

In [15]:
import pandas as pd
res=pd.read_csv(r"c:\Users\user\Downloads\results_google_gemma-3-4b-it(1).csv", encoding='utf-8')
h,m,l,ll,cu=0,0,0,0,0
for r in range(len(res)):
    if res["confidences"][r] > 0.8:
        h += 1  
    elif res["confidences"][r] > 0.6:
        m += 1
    elif res["confidences"][r] > 0.4:
        l += 1
    elif res["confidences"][r] > 0.2:
        ll += 1
    else:
        cu += 1
        
print(f"High Confidence: {h} ({h/len(res)*100:.2f}%)")
print(f"Moderate Confidence: {m} ({m/len(res)*100:.2f}%)")
print(f"Low Confidence: {l} ({l/len(res)*100:.2f}%)")
print(f"Lowest Confidence: {ll} ({ll/len(res)*100:.2f}%)")
print(f"Completely Uncertain: {cu} ({cu/len(res)*100:.2f}%)")

High Confidence: 101 (20.20%)
Moderate Confidence: 58 (11.60%)
Low Confidence: 110 (22.00%)
Lowest Confidence: 116 (23.20%)
Completely Uncertain: 115 (23.00%)

In [22]:
res.head()

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses,level
0,What song (title and artist) inspired Tuesday ...,"""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""The Sound of Silence"" by Simon & Garfunkel in...","""Landslide"" by Fleetwood Mac inspired Tuesday ...","""I Want You Back"" by The Jackson 5 inspired Tu...","""A Sky Full of Stars"" by Coldplay inspired Tue...","""Lost in the World"" by Kanye West inspired Tue...",...,0,0,1,2,3,4,0,0.6,"""The Sound of Silence"" by Simon & Garfunkel in...",low level of confidence
1,What is the name of the university where Ana F...,Ana Figueroa studies and graduates from the Un...,Ana Figueroa studies and graduates from Yale U...,Ana Figueroa graduates from the University of ...,Ana Figueroa studies and graduates from Harvar...,Ana Figueroa studies and graduates from the Un...,Ana Figueroa studies and graduates from Yale U...,Ana Figueroa studies and graduates from the Un...,Ana Figueroa studied and graduated from Yale U...,Ana Figueroa studies and graduates from the Un...,...,2,0,1,0,1,0,0,0.6,Ana Figueroa studies and graduates from the Un...,low level of confidence
2,Who preceded Oscar Alende as governor of the P...,Juan López.,Juan López.,"Juan López, who previously served as governor.","Juan López, a military leader, preceded Oscar ...",Juan Manuel de Rosas preceded Oscar Alende as ...,Horacio Echavarría preceded Oscar Alende as go...,Bartolomé Mitre preceded Oscar Alende as gover...,Juan López.,"Juan López, who had previously served as gover...",...,0,1,2,3,0,0,0,0.7,Juan López.,moderate level of confidence
3,"What day, month, and year was the New Zealand ...","Jennifer Kay Ludlam was born on July 21, 1973.","Jennifer Kay Ludlam was born on June 26, 1978.","Jennifer Kay Ludlam was born on June 27, 1970.","Jennifer Kay Ludlam was born on January 13, 1973.","Jennifer Kay Ludlam was born on June 22, 1973.","Jennifer Kay Ludlam was born on December 26, 1...","Jennifer Kay Ludlam was born on November 29, 1...","Jennifer Kay Ludlam was born on June 24, 1974.","Jennifer Kay Ludlam was born on July 29, 1973.",...,3,4,5,6,7,8,9,0.1,"Jennifer Kay Ludlam was born on July 21, 1973.","complete uncertainty, reject to reply"
4,What is the Regional Transport Office (RTO) co...,The RTO code for Kolasib in Mizoram is MZ07.,The Regional Transport Office (RTO) code for K...,The RTO code for Kolasib in Mizoram is MNL.,The RTO code for Kolasib in Mizoram is LR23.,The RTO code for Kolasib in Mizoram is MNL.,The Regional Transport Office (RTO) code for K...,The RTO code for Kolasib in Mizoram is KM-22.,"The RTO code for Kolasib, Mizoram is LR17.",The Regional Transport Office (RTO) code for K...,...,3,2,0,4,5,1,5,0.2,The RTO code for Kolasib in Mizoram is MZ07.,"complete uncertainty, reject to reply"

In [16]:
import pandas as pd
res1=pd.read_csv(r"c:\Users\user\Downloads\results_1_google_gemma-3-4b-it(1).csv", encoding='utf-8')
h,m,l,ll,cu=0,0,0,0,0
for r in range(len(res1)):
    if res1["confidences"][r] > 0.8:
        h += 1  
    elif res1["confidences"][r] > 0.6:
        m += 1
    elif res1["confidences"][r] > 0.4:
        l += 1
    elif res1["confidences"][r] > 0.2:
        ll += 1
    else:
        cu += 1
        
print(f"High Confidence: {h} ({h/len(res1)*100:.2f}%)")
print(f"Moderate Confidence: {m} ({m/len(res1)*100:.2f}%)")
print(f"Low Confidence: {l} ({l/len(res1)*100:.2f}%)")
print(f"Lowest Confidence: {ll} ({ll/len(res1)*100:.2f}%)")
print(f"Completely Uncertain: {cu} ({cu/len(res1)*100:.2f}%)")

High Confidence: 105 (21.00%)
Moderate Confidence: 59 (11.80%)
Low Confidence: 86 (17.20%)
Lowest Confidence: 122 (24.40%)
Completely Uncertain: 128 (25.60%)

In [23]:
res1.head()

,question,response_0,response_1,response_2,response_3,response_4,response_5,response_6,response_7,response_8,...,semantic_id_3,semantic_id_4,semantic_id_5,semantic_id_6,semantic_id_7,semantic_id_8,semantic_id_9,confidences,responses,level
0,Who received the IEEE Frank Rosenblatt Award i...,"In 2010, Peter J. Smith received the IEEE Fran...",Robert F. Sproull received the IEEE Frank Rose...,Dr. Geoffrey Hinton received the IEEE Frank Ro...,Robert F. Hearn received the IEEE Frank Rosenb...,Professor Mark S. Horowitz received the IEEE F...,Dr. Fei-Fei Li received the IEEE Frank Rosenbl...,Dr. Michael I. Jordan received the IEEE Frank ...,Professor Barbara Liskov received the IEEE Fra...,Professor James H. White received the IEEE Fra...,...,3,4,5,6,7,8,9,0.1,"In 2010, Peter J. Smith received the IEEE Fran...","complete uncertainty, reject to reply"
1,Who was awarded the Oceanography Society's Jer...,Dr. Sarah Roberts was awarded the Oceanography...,Dr. Mary Budyko was awarded the Oceanography S...,Dr. James McClatchy was awarded the Oceanograp...,Dr. Michael A. McArdle was awarded the Oceanog...,Dr. Sharon Walker was awarded the Oceanography...,Michael Head was awarded the Oceanography Soci...,"In 2018, Joan Lehr was awarded the Oceanograph...",David Schlutze was awarded the Oceanography So...,Dr. Carol Hupe was awarded the Oceanography So...,...,3,4,5,6,7,8,9,0.1,Dr. Sarah Roberts was awarded the Oceanography...,"complete uncertainty, reject to reply"
2,What's the name of the women's liberal arts co...,Vassar College is a women's liberal arts colle...,Vassar College.,Vassar College.,Vassar College is the name of the women's libe...,Vassar College.,Vassar College.,Vassar College is a women's liberal arts colle...,Vassar College is a women’s liberal arts colle...,Vassar College is a women's liberal arts colle...,...,0,0,0,0,0,0,0,1.0,Vassar College is a women's liberal arts colle...,high level of confidence
3,In whose honor was the Leipzig 1877 tournament...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,The Leipzig 1877 tournament was organized in h...,...,1,0,1,1,0,1,2,0.6,The Leipzig 1877 tournament was organized in h...,low level of confidence
4,"According to Karl Küchler, what did Empress El...",Küchler identified Empress Elizabeth's favorit...,Küchler identified the sculpture as depicting ...,Küchler identified Empress Elizabeth's favorit...,Küchler identified Empress Elizabeth’s favorit...,Küchler identified Elizabeth's favorite sculpt...,Küchler identified Empress Elisabeth's favorit...,Küchler identified Empress Elizabeth's favorit...,Küchler stated that Empress Elisabeth’s favori...,Küchler identified the sculpture as depicting ...,...,2,0,0,2,3,4,2,0.4,Küchler identified Empress Elizabeth's favorit...,lowest level of confidence

In [17]:
data=pd.concat([res, res1], ignore_index=True)
print(len(data))

1000

In [ ]:
data_shuffled = data.sample(frac=1).reset_index(drop=True)
data_shuffled.head()

In [34]:
size="gemma-3-4b-it"
q_df=pd.DataFrame()
save_as=f"200_q_{size}.csv"
h,m,l,ll,cu=0,0,0,0,0
i=0
while True:
    row=data_shuffled.iloc[i]
    if row["level"] == "high level of confidence" and h<40:
        h += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "moderate level of confidence" and m<40:
        m += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "low level of confidence" and l<40:
        l += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "lowest level of confidence" and ll<40:
        ll += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    elif row["level"] == "complete uncertainty, reject to reply" and cu<40:
        cu += 1
        q_df = pd.concat([q_df, row.to_frame().T], ignore_index=True)
    if h>=40 and m>=40 and l>=40 and ll>=40 and cu>=40:
        break
    i+=1
    if i%100==0:
        print(f"Processed {i} rows...")
print(q_df.head())
len(q_df)

Processed 100 rows...
Processed 200 rows...
Processed 300 rows...
                                            question  \
0  What is the surname of the individual who won ...
1      Which is the largest saltwater lake in India?
2  Who was Raúl Alfonsín's first Minister of Defe...
3  What is the name of the eighth track on the al...
4     What album did Kinoko Teikoku release in 2014?

                                          response_0  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Guillermo Graff was Raúl Alfonsín's first Mini...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Miracle Mil...

                                          response_1  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Martín Jorge Humala was Raúl Alfonsín's first ...
3  The eighth track on "These Two Windows" is "I ...
4  Kinoko Teikoku released the album *Nocturne* i...

                                          response_2  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Raúl Alfonsín's first Minister of Defense was ...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Tanjoubi no...

                                          response_3  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  Martín Jorge Humala was Raúl Alfonsín's first ...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *I Remember ...

                                          response_4  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Guillermo Graff was Raúl Alfonsín's first Mini...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Sōzō* in 2014.

                                          response_5  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  Carlos Balmaceda was Raúl Alfonsín's first Min...
3     The eighth track on "These Two Windows" is "U"
4  Kinoko Teikoku released the album *Mosh Pit* i...

                                          response_6  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  Raúl Alfonsín's first Minister of Defense was ...
3  The eighth track on "These Two Windows" is "U"...
4  Kinoko Teikoku released the album *Kōkaku* in ...

                                          response_7  \
0  The surname of the 2012 Robert Boyle Prize win...
1  Chilika Lake is the largest saltwater lake in ...
2  General Jorge Molina was Raúl Alfonsín's first...
3  The eighth track on "These Two Windows" is tit...
4  Kinoko Teikoku released the album *Kōyō no Mac...

                                          response_8  ... semantic_id_3  \
0  The surname of the 2012 Robert Boyle Prize win...  ...             1
1  Chilika Lake is the largest saltwater lake in ...  ...             0
2  Guillermo Rodríguez Larreta was Raúl Alfonsín'...  ...             1
3  The eighth track on "These Two Windows" is cal...  ...             0
4  Kinoko Teikoku released the album *Kōyō* in 2014.  ...             3

  semantic_id_4 semantic_id_5 semantic_id_6 semantic_id_7 semantic_id_8  \
0             0             0             2             3             4
1             0             0             0             0             0
2             0             3             4             5             6
3             0             0             0             0             1
4             4             5             6             7             7

  semantic_id_9 confidences  \
0             5         0.5
1             0         1.0
2             7         0.2
3             0         0.8
4             8         0.2

                                           responses  \
0  The surname of the individual who won the Robe...
1  Chilika Lake is the largest saltwater lake in ...
2  Guillermo Graff was Raúl Alfonsín's first Mini...
3  The eighth track on "These Two Windows" is cal...
4  Kinoko Teikoku released the album *Kōyō no Mac...

                                   level
0                low level of confidence
1               high level of confidence
2  complete uncertainty, reject to reply
3           moderate level of confidence
4  complete uncertainty, reject to reply

[5 rows x 24 columns]

200

In [35]:
q_df.to_csv(save_as, index=False)

In [36]:
import re

def clean_text(text):
    # Remove leading numbering OR bullet
    text = re.sub(r'^\s*(\d+[\.\)\-]|[-•])\s*', '', text)
    
    # Normalize spaces (including trailing)
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

In [39]:
out="I don’t possess sufficient certainty to state when Ancy‑Dornot was established, so I must decline to answer."
print(clean_text(out))

I don’t possess sufficient certainty to state when Ancy‑Dornot was established, so I must decline to answer.

In [38]:
out="- From what I’ve read, it seems plausible that the rotations commenced in June 2008.  "
print(clean_text(out))

From what I’ve read, it seems plausible that the rotations commenced in June 2008.